### ISSUE TITLE
Thought exercise: flood prevention

### ISSUE THREAD

**Issue by alexbilbie** [thephpleague/glide#10]
This issue is more of a thought exercise than a problem with this project...

So I'm implementing Glide for a project at work and I might have a client that will request upto 60 images from Glide at once.

I know from simple observation that slamming the server with this many requests (each of which may potentially result in a image being manipulated in some way) can take a heavy toll on the server.

Therefore I'm wondering if there are any techniques with dealing with the barrage of requests in a sane way. I know from another simple test I did that if each request is fired about a second or so apart then I can pretty much keep up with demand and deal with each request in sequence relatively quickly.

What I'm thinking is that when a request comes in it is given a "ticket number". It will then poll to see if the server can deal with that ticket number yet. When it is time it will generate the image or retrieve it from cache. Something like this:

```
 Client                  Server                         
+------+                +------+                        
    |                       |                           
    |        Request        |                           
    | --------------------> | +---+                     
    |                       |     |   Request given     
    |                       |     |   ticket number    
    |                       | <---+                     
    |                       |                           
    |                       | +---+                     
    |                       |     |   Poll to see if    
    |                       |     |   server is ready   
    |                       | <---+                     
    |                       |                           
    |                       | +---+                     
    |                       |     |   Generate new image
    |        Response       |     |   or retrieve from cache
    | <-------------------- | <---+               
    |                       |                           
    |                       |                           
```

I'm wondering if this is something I might be able to do with React?

What do you think?

**Comment by reinink** [comment]
I agree, this needs to be thought through a little. Initially I designed Glide for small projects where this basically won't be an issue. Even if the server gets hit with 10 image manipulation requests at once, it will eventually work through them, not a big deal.

This is why I opened a ticket regarding workers (#6). For larger projects it would be good to queue each request, so the server doesn't get totally bombarded. However, this means showing temporary images in the mean time.

I hadn't considered React though. I believe that would allow you to avoid showing temporary images, albeit images may take quite a while to load in while under heavy load. Certainly worth trying.

I'm not sure how much of this Glide should provide out of the box, although I definitely think it should be able to facilitate queues and even potentially async somehow.

**Comment by alexbilbie** [comment]
You're quite right that it will eventually work through them - but it will also cane the server.

I don't think you need to show temporary images, it's more about rendering all the images (in some sort of sequence) over a shorter period of time than trying to parallelise multiple image requests and showing them as they become available (when there are free CPU cycles) over a longer period of time because the server is overwhelmed.

This isn't necessarily something for Glide to solve - it's definitely an architectural issue - I just thought I'd post it here in the open incase you or anyone else (@frankdejonge) had any ideas :smile:

**Comment by reinink** [comment]
Interesting, how exactly would that work with queues then? Something like this?

1. Request comes in
2. Look to see if the rendered image exists
3. If no, wait 1-2 seconds, go back to step 2
4. If yes, show the image

All the while, the queuing system in working in the background.

**Comment by reinink** [comment]
And by wait, I mean sleep. That keeps the image request open, meaning no temporary images.

**Comment by alexbilbie** [comment]
Closing this following discussion on the League mailing list
