### ISSUE TITLE
Fill option

### ISSUE THREAD

**Issue by lukesnowden** [thephpleague/glide#101]
Hi, just wondering if there was any scope for you adding a "fill" option? 

i.e. when setting the "fit" property to "fill" it would create a blank canvas to the height and width passed and then layer the original image over the top which "contains" the boundaries?

regards

**Comment by reinink** [comment]
Yes, this is possible in the upcoming 1.0 release. You can see this feature [here](http://glide.thephpleague.com/1.0/api/size/).

> **fill:** Resizes the image to fit within the width and height boundaries without cropping or distorting the image, and the remaining space is filled with the background color. The resulting image will match the constraining dimensions.

You can also add a background, if you'd like. More on that [here](http://glide.thephpleague.com/1.0/api/background/).

This release will be out within the next couple of months.

**Comment by lukesnowden** [comment]
bang on!
