### ISSUE TITLE
How do cache the output image by brower? and how to let nginx try_files output images directly?

### ISSUE THREAD

**Issue by argb** [thephpleague/glide#106]
1). Images output by glide can't be cached by browser,this would be a great waste of bandwidth.
2). Is there any elegant methods to let nginx  directly output the images produced by glide? If can do it,browser can cache images too.

These two problem is important to solve,or putting images at public/images directory would be better choice to use browser cache.

**Comment by argb** [comment]
Problem 1 solved,because i used https://github.com/barryvdh/laravel-httpcache,this package can't work well,after use this package all images generated by Glide can't be cache by browsers.
About problem 2,I think we need a solution to get benefits from both Glide and Nginx,so the targets are : 
1) if nginx found images,output them directly
2) if nginx can't find images,redirect to php,output image by Glide Server.
To solve: 
1) how to map an URI like this /img/qm01.jpg?w=300&q=60&filt=greyscale&s=ab8b1f0944d2b70af822eb33c6806ac2  to an Image name,which can be recognized by nginx route roles
2) It's best don't make a complicated change of nginx config

Why I hope this solution,because I think nginx is more good at outputing images.If all my images outputed by Glide based on laravel,I am not sure if this would spend lots of time,cpu and memory.

**Comment by reinink** [comment]
I've never used the nginx try_files feature, but I believe this is possible with Glide. See issue #83. You may want to ask @Zae how he did it.

As for issue number 1, there is no reason why Glide images cannot be cached by browsers—they definitely can. In fact Glide sets far-future headers for just this reason. See [here](https://github.com/thephpleague/glide/blob/2bb66ed4b8a59ea446b2e98f535b9d5e2dc70d4c/src/Responses/PsrResponseFactory.php#L49-L50).

**Comment by Zae** [comment]
I haven't tried to use it with try_files directly yet, because of #7. Also I'm not sure yet how ec5c79a will help with this. The biggest problem preventing try_files is still that there is no easy way for nginx to calculcate an md5 hash of the parameters used, so it can't translate image.jpg?size=whatever to the actual file.
