### ISSUE TITLE
Get width or height from outputted image

### ISSUE THREAD

**Issue by adamtester** [thephpleague/glide#107]
Is it possible to get the width or height from the generated image as I'm using

```php
$imgBuilder->getUrl($attrs['src'], ['w' => 800, 'h' => 800, 'fit' => 'max']);
```

Or a way to get the path to the generated file so I can use `imagesx`?

**Comment by reinink** [comment]
Glide doesn't provide a way to get an image's dimensions, because the approach will vary depending on the file system you use. However, this could be done with `imagesx()` if you are using the local disk.

```
$path = $glide->getCachePath($attrs['src'], ['w' => 800, 'h' => 800, 'fit' => 'max'])
```

Good luck!
