### ISSUE TITLE
Support for animated GIFs

### ISSUE THREAD

**Issue by archon810** [thephpleague/glide#110]
Wordpress still doesn't support resizing animated GIFs https://core.trac.wordpress.org/ticket/28474, but maybe Glide can?

**Comment by reinink** [comment]
Glide uses [Intervention](https://github.com/Intervention/image) under the hood, and resizing animated GIFs is not supported. See https://github.com/Intervention/image/issues/42. This is a limitation of the GD library, not Glide or Intervention. It might be possible if you use the ImageMagick driver, but I've never tested it.
