### ISSUE TITLE
Preventing upscaling / upsizing

### ISSUE THREAD

**Issue by wesort** [thephpleague/glide#111]
Is it possible to have a parameter to prevent upscaling should the `width` or `height` setting be greater than the source file. Personally, I'd set this as the default too. 

FYI: I'm new to Glide and using it in Statamic v2.

**Comment by reinink** [comment]
This is currently possible using the `fit=max` parameter. For example:

```
img/kayaks.jpg?w=1000&h=500&fit=max
```

Find more information on this [here](http://glide.thephpleague.com/1.0/api/size/#fit-fit).
