### ISSUE TITLE
documentation location ?

### ISSUE THREAD

**Issue by mikeSimonson** [thephpleague/glide#114]
I can't find the repo with the documentation hosted at http://glide.thephpleague.com/.
It's frustrating as there are basic issue with some links.

**Comment by reinink** [comment]
The docs are available in the `gh-pages` branch. Sorry if there are any issues with the docs, I just released a big update today for the new 1.0 version. I'm away from my computer at the moment, but if you have any difficulties feel free to just post the issues here and I'll fix it later.

**Comment by reinink** [comment]
Hey if you could let me know the issue you found, that would be much appreciated. I'd love to get it fixed. Thanks!

**Comment by mikeSimonson** [comment]
I think that it has been fixed already. It was a typo in the link to the bug #72 if I remember well.

**Comment by reinink** [comment]
Yeah, and that is actually generated from the [releases page](https://github.com/thephpleague/glide/releases), so fixing it would be confusing. Thanks either way! :+1:
