### ISSUE TITLE
masonry grid image api?

### ISSUE THREAD

**Issue by kickthemooon** [thephpleague/glide#115]
I need to build a masonry image grid. So some image orientation will be horizontal some will be vertical.

![masonrygrid](https://cloud.githubusercontent.com/assets/7913974/12017884/7ef08bdc-ad5c-11e5-8c6f-0693c47ef3b7.jpg)

So I am wondering what mix of the api should / could use to convert the images based on their orientation?

any ideas suggestions?

**Comment by reinink** [comment]
Hey, thanks for your interest in Glide! To tackle this, you'll need specific image sizes, so [cropping](http://glide.thephpleague.com/1.0/api/crop/) will be required. Something like this:

```php
<img src="kayaks.jpg?w=300&h=300&fit=crop">
```

Obviously for the masonry effect, you'll create different image sizes.

As placing the images or resizing them based on their orientation, Glide doesn't have any built in support for conditional manipulations. However, you could easily enough determine this yourself. Simply drop down in the file system level, and work out the source image with and height.

Good luck!

**Comment by kickthemooon** [comment]
what do you think about the idea of only setting the 'w' for images?

**Comment by reinink** [comment]
I'm not sure I totally follow what you're asking. If you only set the `w` for images, you'll get images resized to a specified width, but the hight will be unknown. Using a masonry grid JS plugin this could work, but really this is entirely your choice.

**Comment by kickthemooon** [comment]
yes, i will use a js plugin anyway, forgot to mention it. i was just thinking about preparing the thumbs for the plugin.

**Comment by reinink** [comment]
Yeah, makes sense. Glide can definitely help you with this.
