### ISSUE TITLE
Extra '/' on getUrl()

### ISSUE THREAD

**Issue by hiendv** [thephpleague/glide#119]
In my opion, prepending `/` to the path is unnecessary which sometimes miscorrects my image's source or makes it `//`. `baseUrl` alone is enough, I think.
https://github.com/thephpleague/glide/blob/1.0.0/src/Urls/UrlBuilder.php#L76

**Comment by wbadrh** [comment]
As far as I know, you better have an extra forward slash in stead of none at all.
Correct me if I'm wrong.

You can still use:
`$your_url = str_replace('//', '/', $your_url);`
in your application to filter it out.
