### ISSUE TITLE
Allow symfony 3 components in version 0.3.X

### ISSUE THREAD

**Issue by freekmurze** [thephpleague/glide#120]
Hi,

[laravel-medialibrary](https://github.com/spatie/laravel-medialibrary) still uses v.0.3.x of Glide. Upgrading the Glide dependency to 1.0.0 would be a breaking change, and I'm not willing to make a new major version just yet.

When laravel-medialibrary in installed into Laravel 5.2, it stops with an error. I believe that problem is caused by the fact the Glide does not allow symfony 3.x components.

The problem could be solved by changing:

```php
"symfony/http-foundation": "~2.3",
"symfony/http-kernel": "~2.3"
```
to:
```php
"symfony/http-foundation": "~2.3|~3.0",
"symfony/http-kernel": "~2.3|~3.0"
```

Could you tag version 0.3.6 with this change?

**Comment by reinink** [comment]
> I'm not willing to make a new major version just yet

Come on man! :)

I think this is doable, but in all honesty I'm not even sure how to go about doing this. Do you have any recommendations? I'm assuming I'd need to create a branch for the 0.3.x version, and then modify and tag from there, yes?

**Comment by freekmurze** [comment]
I'm no git hero with mask and cape myself, but I think you are correct. In detail this is what I'd do:
-  checkout `0dd3e4e` which is the commit id of v0.3.5
- standing on that commit create a new branch called v.0.3 (or whatever you prefer)
- make the change
- push that branch to github
- create a new release in GitHub (you can choose a branch in that dialog)

I used this strategy on several of the Spatie-packages.

Thank you very much for taking the time to do this!

**Comment by reinink** [comment]
Okay cool, let me do this. I'm pretty sure the commit is `57a10a4` though.

**Comment by freekmurze** [comment]
Yup, you're right. Commit is `57a10a4`. Sorry about that.

![screen shot 2016-01-25 at 14 33 54](https://cloud.githubusercontent.com/assets/483853/12552225/afd97202-c370-11e5-9008-c32f92ce43d7.png)

**Comment by reinink** [comment]
This should be done: https://github.com/thephpleague/glide/releases/tag/0.3.6

Let me know if you need anything further.

**Comment by freekmurze** [comment]
Thanks Jonathan, much appreciated!
