### ISSUE TITLE
Support for trim

### ISSUE THREAD

**Issue by hotmeteor** [thephpleague/glide#125]
Any plans on supporting [trim](http://image.intervention.io/api/trim)?

My use case is for images that have extra whitespace on the sides.

**Comment by reinink** [comment]
Not any plans, but this wouldn't take much. Let's make this happen Adam! :+1:

**Comment by caesarcxiv** [comment]
This on a roadmap?

**Comment by reinink** [comment]
We don't really have a roadmap. 😂 

Main reason `trim` doesn't exist in Glide today is because it's a [resource hog when using GD](http://image.intervention.io/api/trim):

> Note: Resource intensive with GD driver. Use with care.

Then again, so is `blur`, and it exists. Open to PRs.

**Comment by tgalopin** [comment]
Closing, feel free to open a PR if you need it!

**Comment by eminos** [comment]
I gave this a shot.
https://github.com/thephpleague/glide/pull/343
