### ISSUE TITLE
FileNotFoundException for S3 images

### ISSUE THREAD

**Issue by twisctid** [thephpleague/glide#127]
IM using laravel 5.2 and i followed this https://laravel-news.com/2015/01/using-glide-laravel/ guide but im getting the bellow error

FileNotFoundException in Server.php line 465:
Could not find the image `https://s3-us-west-2.amazonaws.com/shop107/auto/b2cdaba42a52d712c73820298ca649fc639cba19.jpg`.

i assure that image exists

here's my config

`$this->app->singleton('League\Glide\Server', function($app){
	        
	        $filesystem = $app->make('Illuminate\Contracts\Filesystem\Filesystem');
	        
	        return \League\Glide\ServerFactory::create([
		        'source' => Storage::disk('s3')->getDriver(),
		        'cache' => Storage::disk('s3')->getDriver(),
		        'source_path_prefix' => '',
		        //'cache_prefix_path' => 'cache/images',
	        ]);
	        
        });`

here's my route

`//routes for testing
	Route::group(array('prefix' => 'test'), function()
	{
		Route::get('/', function (League\Glide\Server $server, Illuminate\Http\Request $request, $path="https://s3-us-west-2.amazonaws.com/shop107/auto/b2cdaba42a52d712c73820298ca649fc639cba19.jpg")
		{
		    //dd($server);
		    $server->outputImage($path, $request->all());
		})->where('path', '.*');
	});`

my dd

`Server {#271 ▼
  #source: Filesystem {#268 ▼
    #adapter: AwsS3Adapter {#212 ▶}
    #plugins: []
    #config: null
  }
  #sourcePathPrefix: ""
  #cache: Filesystem {#268 ▶}
  #cachePathPrefix: ""
  #groupCacheInFolders: true
  #api: Api {#272 ▶}
  #responseFactory: null
  #baseUrl: ""
  #defaults: []
  #presets: []
}`

**Comment by reinink** [comment]
I assume you solved this issue?

**Comment by fabian-stewart** [comment]
it wasn't an issue really. I had to look into your source to get a better idea of what was happening after which i figured out my problem.... i tried to delete this but can't. sorry. excellent library btw

**Comment by reinink** [comment]
Glad you got it figured out.

> excellent library btw

Thanks! :)
