### ISSUE TITLE
Use with Laravels storage

### ISSUE THREAD

**Issue by lukesnowden** [thephpleague/glide#128]
Hi, could you explain (as I cant see on the docs) how you would go about using this with laravels storage as `$image = Storage::disk( $this->disk )->get( $basename );` returns the contents and not the path as it can be stored anywhere, and your documentation says it requires a path.

regards

**Comment by lukesnowden** [comment]
````
$this->server = ServerFactory::create([
	'source' 				=> $system->getDriver(),
	'cache' 				=> $system->getDriver(),
	'source_path_prefix' 	=> 'images',
        'cache_path_prefix' 	=> 'images/.cache'
]);
$this->server->outputImage( $basename, [] );
````

**Comment by reinink** [comment]
Yes, `getDriver()` is your friend here. See https://github.com/laravel/framework/pull/7005 for more info.

I should probably add a note about this in the documentation.
