### ISSUE TITLE
Suggestion : Merge two or more images

### ISSUE THREAD

**Issue by ricardofiorani** [thephpleague/glide#129]
Since glide provides a way to insert a watermark into an image, it would be incredibly nice to to have a way to merge two or more images into one.

**Comment by reinink** [comment]
Hmm, this is interesting, but I wonder how practical this is with an http based API. To me if you're doing this sort of stuff, maybe Glide isn't the best choice. Maybe you're better off dropping down to Intervention, or even to GD/ImageMagick.

The goal with Glide is super simple on-demand image manipulations for relatively common tasks, such as resizing, cropping, watermarks, borders, and basic effects. Merging multiple images is a more serious task, and probably doesn't fit the scope of this library.

I hope that makes sense.
