### ISSUE TITLE
Presets and http signatures

### ISSUE THREAD

**Issue by kamov** [thephpleague/glide#130]
When using presets, http signatures for security is not required, right?

**Comment by reinink** [comment]
Fair question. Actually I'd still recommend using HTTP signatures, since defaults and presets can still be overridden. See here for more information: http://glide.thephpleague.com/1.0/config/defaults-and-presets/#overriding-defaults-and-presets

**Comment by Hacker12345577342** [comment]
When using  HTTP signatures,Hacker can hack us  because there are a lot of tools to decrypte md5 hich Glide use ,see my issue {Security issue with md5
}
