### ISSUE TITLE
Remote filesystem

### ISSUE THREAD

**Issue by kamov** [thephpleague/glide#131]
I have setup a remote adapter with flysystem, and a local, using replicate adapter.
Now that I want load image from remote adapter, how to setup glide?

Thanks!

**Comment by reinink** [comment]
Hello, I'd recommend looking through the "source & cache" documentation on the Glide website: http://glide.thephpleague.com/1.0/config/source-and-cache/

You'll do something like this:

```php
<?php

use Aws\S3\S3Client;
use League\Flysystem\AwsS3v3\AwsS3Adapter;
use League\Flysystem\Filesystem;
use League\Glide\ServerFactory;

// Setup S3 client
$client = S3Client::factory([
    'credentials' => [
        'key'    => 'your-key',
        'secret' => 'your-secret',
    ],
    'region' => 'your-region',
    'version' => 'latest|version',
]);

// Setup Flysystem adapter for S3
$adapter = new AwsS3Adapter($client, 'your-bucket-name', 'optional-prefix');

// Setup Glide server
$server = ServerFactory::create([
    'source' => $adapter
]);
```

Good luck!

**Comment by kamov** [comment]
Thanks!
However, seem that you missing to init filesystem, this work for me:

```php
$server = ServerFactory::create([
    'source' => new Filesystem($adapter)
]);
```

**Comment by reinink** [comment]
Ahh yes, sorry. That's correct. I was going too quick. ;)

**Comment by kamov** [comment]
No problem, I was able to sort out quickly.

I have a question. I am using replicate adapter.
Now file are stored both on local and remote.
As I understand, with replicate adapter, all read are from source (in my case S3).

But when I setup a CDN that serve images from S3, how Glide handle this?
Does image are served via CDN or from my local cache?

Thanks!

**Comment by reinink** [comment]
The way Glide works is that all requests must be handled by PHP. This is a requirement of the library, since the library determines if the manipulated image already exists, of it is needs to create it. It has no special features to work with CDNs. For example, just because your manipulated images could be saved on S3, doesn't mean you can easily serve them directly from there. Glide is still a required "middleman".

**Comment by kamov** [comment]
Oh, this I had not expected ...
I did a quick search if anyone has found a way to integrate CDN with Glide and I don't find nothing.

I only found this tutorial: http://www.sitepoint.com/easy-dynamic-on-demand-image-resizing-with-glide/
where the author provide a workaround to serve cached file without php (check under A Note on Saving with Glide).
He propose this solution:

```php
    public function renderImage($image)
    {
        $width = $this->getWidth($image);

        $imageSource = str_replace('-'.$width, '', $image);

        $imagePath = $this->glide->makeImage($imageSource, ['w' => $width]);
        $imageBase = $this->glide->getCache()->read($imagePath);
        $this->glide->getCache()->put($image, $imageBase);
        $this->glide->outputImage($imageSource, ['w' => $width]);
    }
```

> 
makeImage creates and saves the image, but returns only its path. We then read the image’s contents with said path from the cache. Finally, we re-save the image under its originally requested name, and then output like we did before. Thus, only this first call will be expensive (several I/O operations and a conversion), and all future calls to this image URL will go straight to the image – bypassing PHP completely. In fact, if you power down PHP with sudo service php-fpm stop, the image will still load.

What do you think? 

I read also one your comment on a article, where you said that you design Glide for small project, and that you suggest for large project to prepare all sizes and then store on S3 and serve via CDN.

Maybe I need to get this way, since I am working on a project where user share images, so there will be many traffic.
