### ISSUE TITLE
Image manipulators ordering

### ISSUE THREAD

**Issue by a-komarev** [thephpleague/glide#132]
Is there is a way to perform `rect` only after `fit` + `w` + `h` done?

```
#parameters: array:5 [
    "fit" => "max"
    "w" => "520"
    "h" => "260"
    "rect" => "220,220,89,40"
    "fm" => "jpg"
]
```

Because I need to resize resize image to `520x260` and only after perform a `220x220` cropping from result. And now it's working in reverse order.

**Comment by a-komarev** [comment]
I just swapped `Size` and `Rectangle` manipulators and it's working well now.

```php
// Set manipulators
$manipulators = [
    new Orientation(),
    new Size(Config::get('laravel-glide::config.maxSize')),
    new Rectangle(),
    new Brightness(),
    new Contrast(),
    new Gamma(),
    new Sharpen(),
    new Filter(),
    new Blur(),
    new Pixelate(),
    new Output(),
];

The whole story why I need it is on the [library that utilizes Glide](https://github.com/spatie/laravel-medialibrary/issues/212).
```

**Comment by Krato** [comment]
How you resolved?

**Comment by a-komarev** [comment]
@Krato I've made a fork of Glide and Fork of Medialibrary.

**Comment by a-komarev** [comment]
@Krato You can see my first public work example: https://github.com/cybercog/laravel-medialibrary/tree/feature/manipulators-ordering
