### ISSUE TITLE
documentation addition:: Image not found

### ISSUE THREAD

**Issue by maximusblade** [thephpleague/glide#135]
I needed to add
        **ob_end_clean();**
before
        $server->outputImage($path, $_GET);

also

'source_path_prefix and     'cache_path_prefix'

are actually suffixes?
and only start from your config/filesystem.php "root"

"/var/www/public...***" wont work
as it begins with "storage/app"  by default 

---

I imagine a hit like this in documentation or tutorial would save a lot of people time?

**Comment by tgalopin** [comment]
Closing but feel free to open a PR if you have ideas on how to improve the doc!
