### ISSUE TITLE
Amazon CDN

### ISSUE THREAD

**Issue by mdela** [thephpleague/glide#138]
Hi,

How can I make it works my source path with amazon cdn? 

This is where I am today:
`return ServerFactory::create([  'response'  => new LaravelResponseFactory(),
                                                    'source'     => env('AWS_CDN'),
                                                    'cache'      => Storage::disk('s3')->getDriver()]);`

So far, only if first I select my S3 bucket as the source and then change to CDN url my files are shown, but that is not ideal and do not even know why this happens .

**Comment by reinink** [comment]
Hmm, you need to configure your source to use a Flysystem instance. Using `env('AWS_CDN')` won't work. More info can be found here: http://glide.thephpleague.com/1.0/config/source-and-cache/

```php
<?php

return ServerFactory::create([
    'response' => new LaravelResponseFactory(),
    'source' => Storage::disk('s3')->getDriver(),
    'cache' => Storage::disk('s3')->getDriver(),
    'source_path_prefix' => 'source/path/on/s3',
    'cache_path_prefix' => 'cache/path/on/s3',
]);
```

Good luck!
