### ISSUE TITLE
`getSourcePathWithoutPrefix()` does not exist.

### ISSUE THREAD

**Issue by ADmad** [thephpleague/glide#139]
The [docs](http://glide.thephpleague.com/1.0/config/advanced-usage/) mention that the server has a `getSourcePathWithoutPrefix()` but the method doesn't seem to exist.

**Comment by jackmu95** [comment]
The method was removed in favor of `getSourcePath()` which returns the source path (with prefix if defined) and `getSourcePathPrefix()` which returns the defined prefix.

**When you really want to get the source path without prefix, you could do this:**
```php
$sourcePathPrefixPattern = '/^' . preg_quote($server->getSourcePathPrefix() . '/', '/') . '/';
$sourcePathWithoutPrefix = preg_replace($sourcePathPrefixPattern, '', $server->getSourcePath($path));
```

**Comment by ADmad** [comment]
Yes I can do the string manipulation shown if needed. The point is the docs shouldn't list non existent methods :)

**Comment by jackmu95** [comment]
Yes, they need to be updated :)
