### ISSUE TITLE
ErrorException: rewind(): stream does not support seeking

### ISSUE THREAD

**Issue by TheHiddenHaku** [thephpleague/glide#142]
Hello.
I'm using Glide with Laravel a lot. I use AWS S3 too as storage.
This combination worked flawlessy for me in the last year.

Last friday, out of the blue I started getting this error, resulting in an unavailable image
The error appeared both on local and production at the same time.

`local.ERROR: ErrorException: rewind(): stream does not support seeking in /Users/
<username>/Repo/<projectname>/vendor/league/glide/src/Server.php:442`

This is the function involved 

```
    public function outputImage($path, array $params)
    {
        $path = $this->makeImage($path, $params);

        header('Content-Type:'.$this->cache->getMimetype($path));
        header('Content-Length:'.$this->cache->getSize($path));
        header('Cache-Control:'.'max-age=31536000, public');
        header('Expires:'.date_create('+1 years')->format('D, d M Y H:i:s').' GMT');

        $stream = $this->cache->readStream($path);

        rewind($stream);
        fpassthru($stream);
        fclose($stream);
    }
```

If i remove that specific line from Server.php, it works perfectly, but i don't want to change a package source code in any way.

Any hint about why it happen and how to fix it?

**Comment by TheHiddenHaku** [comment]
#137 solved this.

**Comment by reinink** [comment]
👍
