### ISSUE TITLE
GIFs not working

### ISSUE THREAD

**Issue by simplenotezy** [thephpleague/glide#143]
Very strange issue is that GIFs are not working with glide. They are being returned like this:

![image](https://cloud.githubusercontent.com/assets/3786627/16091251/226c3660-3333-11e6-8b0e-c243ad2b6cc8.png)

Got the exception:

```
League\Glide\Filesystem\FilesystemException: Could not read the image
```

Broken GIF: https://cdn.athliit.com/images/9c541649656b9dde4ab5032bbbcf83ba.gif
Direct, working GIF: https://cdn.athliit.com/images/sponsors/9c541649656b9dde4ab5032bbbcf83ba.gif

What is wrong?

**Comment by canfiax** [comment]
using `gd` as driver

**Comment by thomaspicquet** [comment]
Wrong headers from Glide or whatever you use on top of Glide ;) right now its returned as text
`header('Content-type:image/gif');`

**Comment by reinink** [comment]
If the `FilesystemException` is thrown, then somehow the underlying Flysystem library cannot read the image, and that is most likely the problem. Is it working for other images?

**Comment by canfiax** [comment]
It is working fine for other images. I am using GlideServer to serve the images.

**Comment by reinink** [comment]
Can you do me a favour and try a different Gif image?

**Comment by canfiax** [comment]
Already tried that and it didn't work either..

//Mattias

Sendt fra min mobil

Mattias Siø Fjellvang
CTO - Athliit
(+45) 26 78 98 88

**Comment by reinink** [comment]
Hmm, so if Gif images are the ones not working, it's *possible* that this could be an issue with either Intervention, or even GD/ImageMagick, depending on the one you're using.

However, the fact that the file cannot be read makes me think that your image never actually hits GD/ImageMagick. Is it possible that your Gif files are saved in a different folder than the other images you're trying? And that folder potentially could have different permissions set? Is it possible that the files have different permissions set?

**Comment by reinink** [comment]
Any update here?

**Comment by simplenotezy** [comment]
Hi  - no images are being served from the exact same folder. No tweaks done here.
