### ISSUE TITLE
Using Glide to cut external images?

### ISSUE THREAD

**Issue by juscelinobarao** [thephpleague/glide#145]
There is the possibility of using Glide to cut **external images**?
In my case I would use in my project, YouTube videos of images _(eg "http://img.youtube.com/vi/kOkQ4T5WO9E/0.jpg")_.
Any tips on how to do?

Thank you in advance.

**Comment by reinink** [comment]
Yes, this is possible. This can be done using an HTTP adapter for Flysystem. Basically you need to setup this HTTP adapter as your Glide "source". I've tested this with [this library](https://github.com/twistor/flysystem-http) quite a while ago, and it worked great from what I remember.

Good luck!
