### ISSUE TITLE
Facotry setup vs manually in dc

### ISSUE THREAD

**Issue by dadema** [thephpleague/glide#146]
Hi
I try to put in my container glide, with factory like this

```
$server = League\Glide\ServerFactory::create([
              'response' => new SlimResponseFactory(),
              'source' => new Filesystem($source_level),
              'cache' => new Filesystem($cache_level),
              'max_image_size' => 2000 * 2000,
  ]);
return $server;
```

OK, everything fine with psr7 slim, and in my controller I response like this
$this->glide->getImageResponse('kayaks.jpg', ['w' => 300, 'h' => 400]);
The output is the resized kayaks with header image/jpeg.

Then I try to use manually setup with this config in my container (http://glide.thephpleague.com/1.0/config/setup/#setup-manually). I write so:

 ```
$imageManager = new Intervention\Image\ImageManager([
      'driver' => 'gd',
  ]);
  // Set manipulators
  $manipulators = [
      new Manipulators\Size(2000),
  ];
  // Set API
  $api = new League\Glide\Api\Api($imageManager, $manipulators);
  // Setup Glide server
  $server = new League\Glide\Server(
      new Filesystem($source_level),
      new Filesystem($cache_level),
      $api
  );
$server->setResponseFactory(new SlimResponseFactory());
return $server;
```

As you can see, I used the same settings, but I don't see anything! There isn't errors and the header is text/plain;charset=UTF-8 ... 
I don't understand where he lost the response ..
Any ideas ?

**Comment by reinink** [comment]
Something that isn't clear from the documentation is that you must always include the `Encode` manipulator. I've considered just hardcoding in this manipulator, but I wanted it this way to leave more flexibility with the library.

Update your list manipulators like so:

```php
  // Set manipulators
  $manipulators = [
      new Manipulators\Size(2000),
      new Manipulators\Encode(),
  ];
```

Good luck!

**Comment by reinink** [comment]
I've added this note to [the documentation](http://glide.thephpleague.com/1.0/config/setup/) to help prevent this issue in the future.

![image](https://cloud.githubusercontent.com/assets/882133/16585603/a8636ab6-428f-11e6-945f-4ded9d07e747.png)

**Comment by dadema** [comment]
:+1: Thank you very much @reinink ! It's working! I'll make a tour in the class ..
PS
You know, it's my first post in github .. I'm excited ;)

**Comment by reinink** [comment]
Haha, awesome!!! Welcome to GitHub and the wonderful world of open source! Also, enjoy Glide. 😉
