### ISSUE TITLE
broken image with size less than 100

### ISSUE THREAD

**Issue by hrmshandy** [thephpleague/glide#147]
If I set width or height less than 100 it will returned like this:
![image](https://cloud.githubusercontent.com/assets/8230690/16730496/7680d96c-479d-11e6-920e-04308a63edc1.png)

What is wrong?

**Comment by hrmshandy** [comment]
hello anyone else can help me?

**Comment by reinink** [comment]
Can you provide some source code for this?

**Comment by hrmshandy** [comment]
you can see in my repo https://github.com/hrmshandy/finder

**Comment by reinink** [comment]
I've reviewed this repo and I honestly see no reason why this should be happening, especially at a size less than 100 pixels. Does this happen for any images you try, or just one?

**Comment by hrmshandy** [comment]
for any images

**Comment by BD-Rene** [comment]
I'm seeing the same thing - although in my experience it's not size (/dimensions) related. I've been trying to generate really low quality versions of my images (to be replaced with nice high quality ones on page load), but once I go 'too extreme' with my settings, I start seeing the above mentioned HTML output.

Here is an example of what settings I'm using (copied from my code):
'w'     => 312,
'h'     => 468,
'fit'   => 'crop-center',
'q'     => 3,
'pixel' => 10,
'fm'    => 'jpg'

Once I 'dial it back a bit' (increasing the quality parameter, removing the pixelate stuff), images are output as .jpgs again.

**Comment by ChrisLamprecht** [comment]
I have the same problem with different sizes depending on the original image... but it is only in the browser. In some cases Glide just doesn't output any html. It looks like hrmshandy's screenshot above. Sometimes adding "&fm=png" helps, but not always. The rendered image files are ok, they look good in preview. 
If I can not rely on proper output/rendering, Glide is unfortunately unusable for me... :-(
Is there a solution? I use Laravel 5.3 and Glide 1.0.

**Comment by reinink** [comment]
How are you both outputting your images? Are you using [responses](http://glide.thephpleague.com/1.0/config/responses/), or are you using the `outputImage()` method?

**Comment by BD-Rene** [comment]
This is using ->outputImage()

**Comment by reinink** [comment]
Are you doing anything after you call that function? Try adding `exit;` on the line after to stop the script execution, and see if that helps. It's possible that other headers are being sent, or even content, that is breaking your image.

Alternatively, consider using [responses](http://glide.thephpleague.com/1.0/config/responses/). They are designed to work within your frameworks standard request/response cycle, and generally leads to less issues.

Good luck! :)

**Comment by reinink** [comment]
Any update here?
