### ISSUE TITLE
How to add support for TIFF?

### ISSUE THREAD

**Issue by yanhuixie** [thephpleague/glide#149]
Hello guys~
We have been benefiting from glide. Now we want add support for tiff.
As you all know, gd lib does not support TIFF, but imagick do.
Any suggestion is appreciated. Thanks!

**Comment by reinink** [comment]
If you want tiff support with Glide, you'll have to use ImageMagick. Glide comes with support for this via the `imagick` PHP extension. More on drivers [here](http://glide.thephpleague.com/1.0/config/image-driver/).

```php
$server = League\Glide\ServerFactory::create([
    // Use ImageMagick
    'driver' => 'imagick',
]);
```

So, I think you answered your own question. 😎

**Comment by yanhuixie** [comment]
Wow~ Thanks, reinink. Follow your tips, we had solved the problem magically after switched the driver to imagick.

**Comment by reinink** [comment]
You're quite welcome!
