### ISSUE TITLE
Safari "Failed to load resource: The network connection was lost." 

### ISSUE THREAD

**Issue by Jaspur** [thephpleague/glide#150]
For some reason Glide isn't working anymore on my Safari v9.1.1 (11601.6.17) on OS X 10.11.5 (15F34).
It gives in the Console: `Failed to load resource: The network connection was lost.`

But when I hit the URL manually, for just the image (https://website.com/img/photos/_11_241077-t3-211jpg_56b35a201ee7d?w=354&h=274&fit=crop) it works, but not on a webpage with multiple Glide requests to images.

I found this:

> Chrome & Firefox just display whatever content was received & don't worry about the mismatch in content length. Safari, starting with Safari 7.0 on Mavericks' 10.9 is stricter about the response & treats the mismatch as a "Failure to load resource" error. (If I had to guess they're probably trying to improve the speed so don't retry the resource and so don't get the file fully retrieved response that wget does). (http://apple.stackexchange.com/questions/106550/safari-7-0-cannot-load-localhost) 

Has that to do with it? 

I'm on Glide v0.3.6, using Laravel-Glide's package.

**Comment by tekiwebata** [comment]
Hi,
Any news about this problem please ?
Thanks for your replies

**Comment by tgalopin** [comment]
Does this problem still exist? It seems related to a mime type problem.

**Comment by ADmad** [comment]
Given how old this ticket is I am going to assume this issue is resolved :)
