### ISSUE TITLE
Memory not getting released, OOM on android

### ISSUE THREAD

**Issue by DeepsUttekar** [thephpleague/glide#151]
Hi all

I have and media application, which shows media thumbnails on application home screen. I am using glide library to show thumbnails.

Application checks if image is present on SDCARD, I show local copy using following code
  Glide.with(mFragment).load(Uri.fromFile(imageFile)).into(holder.mIvContentImage);

but if image is not present locally, I download that from server and show on UI. Once the download event is received from glide library. I am saving that image to SDCARD. following is the code

 Glide.with(mFragment).load(thumbnailUrl).asBitmap().override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL).centerCrop().diskCacheStrategy(DiskCacheStrategy.SOURCE).listener(new RequestListener<String, Bitmap>() {
            @Override
            public boolean onException(Exception e, String model, Target<Bitmap> target, boolean isFirstResource) {
                showThumbnailViiew(holder, contents, position);
                return false;
            }

            @Override
            public boolean onResourceReady(Bitmap resource, String model, Target<Bitmap> target, boolean isFromMemoryCache, boolean isFirstResource) {
                String imageName = thumbnailUrl.substring(thumbnailUrl.lastIndexOf("/") + 1);
                String imagePath = Environment.getExternalStorageDirectory() + File.separator + mFragment.getActivity().getString(R.string.app_name) + THUMBNAILS_FOLDER_NAME + imageName;
                saveImage(resource, contents, imagePath);
                return false;
            }
        }).into(holder.mIvContentImage);

but the issue is... for 1st run.. when all images come from server app memory is 70mb and 2nd run onwrds when images are local, app runs at 40mb memory. 

there is issue of around 30mb. 

How can I free this memory. I checked all the memory dumps, highest allocation is to glide classes

**Comment by reinink** [comment]
I think you have the wrong library. :)

See this project: https://github.com/bumptech/glide

**Comment by DeepsUttekar** [comment]
what do you mean by wrong library... i will use this and let you know the result...  why to direct close issue like this

**Comment by reinink** [comment]
Because there are two image libraries called Glide. One is for PHP (this one), and one is for Android ([this one](https://github.com/bumptech/glide)). Judging by your issue, I believe you have the wrong library. I can't really help you...

**Comment by DeepsUttekar** [comment]
im still facing this issue.. I am using same lobrary specified by you

**Comment by DeepsUttekar** [comment]
compile 'com.github.bumptech.glide:glide:3.7.0'

this is how im using it.

**Comment by linuxjuggler** [comment]
@DeepsUttekar this repo is for a php code package not android.
and the one you are using is https://github.com/bumptech/glide 
so you should just report you issue at this https://github.com/bumptech/glide repo not here .

**Comment by DeepsUttekar** [comment]
No.. im using Andorid library and creating an app for android device, I am facing this issue... I am no where using PHP.

**Comment by martinbean** [comment]
@DeepsUttekar This repository is for a PHP library called Glide, _not_ the Android library called Glide. You’ve opened the Issue on the wrong repository.

**Comment by DeepsUttekar** [comment]
oops sorry...  then pls let me knw where can i raise android issue

**Comment by linuxjuggler** [comment]
@DeepsUttekar go to this one https://github.com/bumptech/glide
