### ISSUE TITLE
Server temp dir should be configurable

### ISSUE THREAD

**Issue by jaapio** [thephpleague/glide#156]
At the moment the glide server is using sys_get_temp_dir to be able to do image manipulations. 

``` php
        // We need to write the image to the local disk before
        // doing any manipulations. This is because EXIF data
        // can only be read from an actual file.
        $tmp = tempnam(sys_get_temp_dir(), 'Glide');

        if (file_put_contents($tmp, $source) === false) {
            throw new FilesystemException(
                'Unable to write temp file for `'.$sourcePath.'`.'
            );
        }
```

Our server doesn't allow vhosts to access the /tmp folder. It would be nice if this path was configurable. /tmp could still be a fallback so we don't have any bc breaks. Option should be a string so the user can only define a local path.

**Comment by reinink** [comment]
Yeah okay, I think we can do this. If you wanted to speed up the process, feel free to fire in a PR. Otherwise I'll do this next time I have some free time. ⏳

**Comment by jaapio** [comment]
Let's see who is first ;-)

**Comment by wbadrh** [comment]
Please review #186
