### ISSUE TITLE
Is it possible to add text with Glide?

### ISSUE THREAD

**Issue by justanotheramateur** [thephpleague/glide#159]
One of Cloudinary and Imgix's features is the adding of arbitrary text without needing to create a separate watermark image for it first. Is this possible with Glide?

**Comment by reinink** [comment]
Nope, not possible at this time. It wouldn't take too much to add. There is support for this with Intervention Image: http://image.intervention.io/api/text

If this is something you need more urgently for your particular application, you could create your own custom manipulator. Here is how you would do this: http://glide.thephpleague.com/1.0/config/setup/#setup-manually

I'm going to close this for now, but will mark it as a feature request for future updates to this library. Alternatively you are of course welcome to contribute this feature as well. 👍
