### ISSUE TITLE
Add HttpAdapter Flysystem adapter

### ISSUE THREAD

**Issue by reinink** [thephpleague/glide#16]
I think it would be helpful to create a custom Flysystem adapter for Glide that would allow using a website address as the source. Something like:

``` php
$source = new League\Flysystem\Filesystem(
    new League\Flysystem\Adapter\WebsiteAddress('http://example.com/img/')
),
```

Clearly this Flysystem adapter wouldn't be able to fulfill the entire interface. It could read, by not write, delete, etc. But still, in the context of Glide it could still be very handy.

@frankdejonge What do you think, this could work right?

**Comment by frankdejonge** [comment]
@reinink there has been attempts at an HTTP adapter, which is certainly doable. The one working on it abandoned the PR though. But if you just return `false` on all the non-supported methods, you're golden. It will certainly work.

**Comment by reinink** [comment]
Exactly what I was thinking, basically like the null adapter, except `read` and maybe a few others would work. :)

Does it make sense to package this as part of Flysystem (under it's namespace), or should I just provide it with Glide?

**Comment by frankdejonge** [comment]
I'd say it'd be best to create a glide-flysystem-adapter package? It's a very optional thing, good case for a small package.

**Comment by frankdejonge** [comment]
Could even be league/flysystem-glide btw.

**Comment by reinink** [comment]
I like it.

**Comment by barryvdh** [comment]
And perhaps photo storage like Flickr/Picasa also?
Flickr is nice for storage etc, but thumbnails are a bit restricted, so something like Glide would be nice for that :)

**Comment by reinink** [comment]
@barryvdh Wow, that's an awesome idea. I could see there being a few of these. So, do we package these all under one package, or many? I think potentially many, because each adapter could have it's own dependencies. Something like:

```
league/flysystem-glide-http
league/flysystem-glide-flickr
league/flysystem-glide-picasa
```

Would that makes sense Frank?

**Comment by barryvdh** [comment]
But in principle, every photo service with an public url could be used with the Http adapter :)

**Comment by reinink** [comment]
Yeah, I was just thinking that. Something to think about for sure.

**Comment by duncan3dc** [comment]
Coincidentally I kickstarted that [pr](https://github.com/thephpleague/flysystem/pull/363) for this very purpose, but I'm +1 for this getting implemented in any way you two see fit

**Comment by reinink** [comment]
Closing this ticket. This functionality will be added to Flysystem in the near future.
