### ISSUE TITLE
Image interlace bug

### ISSUE THREAD

**Issue by lapixo** [thephpleague/glide#160]
in the Encode extends BaseManipulator class on line 24 is the "$image->interlace();" function, which should call after creating the new image on line 29. The progressive image is gonna lost after creating it. 

on this site, you can test if the image is progressive.
http://techslides.com/demos/progressive-test.html

here is a solution:

    public function run(Image $image)
    {
        $format = $this->getFormat($image);
        $quality = $this->getQuality();
        $isProgressive = false;
        if ($format === 'pjpg') {
            $isProgressive = true;
            $format = 'jpg';
        }

        if ($format === 'jpg') {
            $image = $image->getDriver()
                           ->newImage($image->width(), $image->height(), '#fff')
                           ->insert($image, 'top-left', 0, 0);
        }
        if ($isProgressive)
            $image->interlace();

        //imagejpeg( $image->getCore(), 'a2.jpg' );
        //imagedestroy($image->getCore());
        //exit;

        return $image->encode($format, $quality);
    }

**Comment by reinink** [comment]
Yes, good call. This has been fixed: f44f0efee7d80e5b351055e1ffbfa4d1368a04a6
