### ISSUE TITLE
The picture didn't show up

### ISSUE THREAD

**Issue by CallMeSirLiu** [thephpleague/glide#164]
Im using Laravel5.2 Framework for my PHP code.
In my localhost env,the brower returned something like these below to me :
![qq20161121-0](https://cloud.githubusercontent.com/assets/7090699/20473721/7b79a8b8-affd-11e6-8cf7-be2f47f87bd3.png)

It seemed that  glide returned the right png,but the png didn't show up
I don't know why

I used glide in my route
```
use League\Glide\ServerFactory;
use League\Glide\Responses\LaravelResponseFactory;
Route::get('img/{path}',function ($path){
	$server = ServerFactory::create([
		'source' => './',
		'cache' => './uploads/tmp',
		'response' => new LaravelResponseFactory()
	]);
	$server->outputImage($path,$_GET);
})->where('path','.+');
```

Anyone can help?

**Comment by CallMeSirLiu** [comment]
好吧，整整一晚上，我知道为神马了。
有个同事
![b0475ac0-17f1-41d2-ac40-5cf6d962e00a](https://cloud.githubusercontent.com/assets/7090699/20525518/c8453bbe-b0fa-11e6-88dc-30ac3798f266.png)
我心好累，他们之前还一直说是glide 有问题。

**Comment by reinink** [comment]
Yep, that will do it! Which is generally why it's not recommended to using closing tags in PHP.

See http://stackoverflow.com/questions/4410704/why-would-one-omit-the-close-tag.

Also see http://www.php-fig.org/psr/psr-2/:

> The closing ?> tag MUST be omitted from files containing only PHP.
