### ISSUE TITLE
How to specify the "mimetype" of the image response？

### ISSUE THREAD

**Issue by mrold** [thephpleague/glide#166]
I stored the uploaded file without extension, the file hash as the name.

**Comment by reinink** [comment]
This is set using the format (`fm`) value. Docs [here](http://glide.thephpleague.com/1.0/api/encode/#format-fm).

You don't actually set the mime type, but instead you set one of the accepted formats. This includes `jpg`, `pjpg` (progressive jpeg), `png` and `gif`. The default is jpg.

Glide takes care of setting the proper mime type in the response based on this value.
