### ISSUE TITLE
Feature Request: Image Minification

### ISSUE THREAD

**Issue by stevendesu** [thephpleague/glide#167]
I take great pride in getting overzealous about gulp files to concatenate, strip, and minify just about everything I can -- from [detecting and in-lining critical CSS](https://github.com/addyosmani/critical) to [generating sprite sheets](https://github.com/twolfson/gulp.spritesmith) and everything in between.

That means I was a bit depressed when I saw this:

![non-optimal](https://cloud.githubusercontent.com/assets/1384974/21414351/9bb45a24-c7cc-11e6-912c-fe5d41119033.jpg)

It would be nice if there were an optional parameter to run the generated image through imagemin. Since results are cached the effect on performance would be almost negligible (longer load time for first image load and then zero effect afterwards) and if it were optional then people could disable it situationally (if they can't take advantage of caching for some reason)

**Comment by stevendesu** [comment]
Something like [image-optimizer](https://github.com/psliwa/image-optimizer) might be good for this purpose, although it hasn't been updated in a year so I don't know how good it is.

**Comment by reinink** [comment]
This is a great idea, and it's something I've considered. However, the problem with existing tools like  Image Optimizer is the dependencies they require. Right now Glide only requires GD (or ImageMagick). GD is installed with most (all) versions of PHP. Having to install a bunch of server libraries just to use Glide isn't really feasible. Ideally there would be a way to do this all in PHP. I'm not sure that's possible.

That said, we _could_ create an option for Glide that enables these post-optimizers. When enabled you'd be required to still install the libraries on your server, but at least Glide would take care of actually calling them.

I'm going to tag this as a feature request and close it for now. If you have any additional ideas, please share them. I'll consider this for a future update.

**Comment by stevendesu** [comment]
I know it's possible to include binaries with a Composer package. When I included `knplabs/knp-snappy` in one of my projects it had listed as dependencies:

```
"h4cc/wkhtmltopdf-i386": "~0.12",
"h4cc/wkhtmltoimage-i386": "~0.12",
"h4cc/wkhtmltopdf-amd64": "~0.12",
"h4cc/wkhtmltoimage-amd64": "~0.12",
"wemersonjanuario/wkhtmltopdf-windows": "~0.12",
```

These packages included the binaries and I was able to utilize wkhtmltopdf without ever having to install it on my server.

I can look into how they did this (I never bothered researching their wizardry) and create some one-off repositories for the necessary binaries.

**Comment by reinink** [comment]
By all means, feel free to pursue and prototype this! 👍

**Comment by InfinityWebMe** [comment]
@reinink What do you think about that ?

https://github.com/InfinityWebMe/glide-optimizer

**Comment by stevendesu** [comment]
@InfinityWebMe Your solution would likely work in most cases. I still think the ideal solution would be to figure out how to bundle the binaries as part of a composer package. Unfortunately for all my ideas I never put the time into it, myself :frowning_face: So I can't really complain
