### ISSUE TITLE
Image size problem and slow down page problem

### ISSUE THREAD

**Issue by ibrahimhasanov** [thephpleague/glide#168]
Sometimes  If page has 10 image and page itself has a little bit more content to load glide begin to work slow and browser shows all images not loaded,and also I use glide a lot but I saw that it slow down page reason is security sign,I saw that cloudinary doesn't use any kind of sign which slow down page here is example: http://res.cloudinary.com/demo/image/upload/w_533,h_733,c_thumb,g_face/bike.jpg

**Comment by Alex199o** [comment]
Yes you are absolutely right, it is also my problem a lot of time glide did this for me, I don't know reason, also as you said it is interesting why we use sign even cloudinary or others doesn't use any key,I think if Glide fixed this issue Glide can be really great library

**Comment by ibrahimhasanov** [comment]
![glide_error](https://cloud.githubusercontent.com/assets/24885596/21599309/1fcf8a84-d184-11e6-9e04-b2269d73b835.png)
this is error that I saw in my website

**Comment by Alex199o** [comment]
yeah it is true some images doesn't load

**Comment by reinink** [comment]
Can you give me the error shown for those failing images? It's very difficult to know what's going wrong without that.

**Comment by ibrahimhasanov** [comment]
@reinink when I open page I see that some images has not downloaded yet and it seems like ![glide_error](https://cloud.githubusercontent.com/assets/24885596/21599309/1fcf8a84-d184-11e6-9e04-b2269d73b835.png)  but when I open developer toolbar then network tab I  see that image downloaded failed and preview tab shows that preview is not available.When wait some seconds I see that icon which represent this image request turn from error image to actual image but preview doesn't changed yet.But when I enter url itself it shows me image and also sometimes exact image works but another  some images which worked before begin not working.But few times all images works fine.I saw this error a lot especially in page which has a lot of Glide image.

**Comment by reinink** [comment]
Getting closer. Can you open just that image in a new URL and see if you still get an error? What HTTP response code are you getting? Are you able to enable debugging in your app to display the error that the application is outputting?

**Comment by ibrahimhasanov** [comment]
@reinink  when I open url I see actual image without any erorr and when I open network tab it shows preview is not aveliable so I am not able to see error itself from url path, but sometimes it echo(not return) HTTP.200 OK ... long text  and all http header elements cookies,sessions.Problem is it echo it, not return like header

**Comment by ibrahimhasanov** [comment]
@reinink I have found problem and solution :).I have added  html comment (<!-asdadasdasdasd-->)to the glide and it affected images now when I delete this comment everything worked perfectly even with more and more images :).

**Comment by reinink** [comment]
Awesome, good to hear!
