### ISSUE TITLE
expects parameter 1 to be resource, object given

### ISSUE THREAD

**Issue by hanishassim** [thephpleague/glide#169]
I got this error whent trying to get file sourced from google storage bucket:
<br />
<b>Warning</b>:  ftell() expects parameter 1 to be resource, object given in <b>/var/www/html/inc/vendor/league/glide/src/Server.php</b> on line <b>470</b><br />
<br />
<b>Warning</b>:  rewind() expects parameter 1 to be resource, object given in <b>/var/www/html/inc/vendor/league/glide/src/Server.php</b> on line <b>471</b><br />
<br />
<b>Warning</b>:  fpassthru() expects parameter 1 to be resource, object given in <b>/var/www/html/inc/vendor/league/glide/src/Server.php</b> on line <b>473</b><br />
<br />
<b>Warning</b>:  fclose() expects parameter 1 to be resource, object given in <b>/var/www/html/inc/vendor/league/glide/src/Server.php</b> on line <b>474</b><br />
<br />
Its obviously not "Image not found error", but I can't figure out how to fix this. I'm using the latest Glide release.
<br />
Thanks.

**Comment by reinink** [comment]
Hi @hanishassim, sorry for the delay. I've never seen this error before. It looks like when Glide is trying to put the image stream it is getting an object instead. Can you var_dump the object to see what it looks like?

What Flysystem adapter are you using? Local? Or something else, like S3?
