### ISSUE TITLE
Add SignKey interface

### ISSUE THREAD

**Issue by reinink** [thephpleague/glide#17]
Currently Glide is hard coded to use the `League\Glide\SignKey`. However, it would probably be better to type hint against an interface here, such as `League\Glide\Interfaces\SignKey`, so that the default implementation can be swapped out for something custom.

The only issue I see here is that currently Glide removes the `token` parameter before generating the cache filename. This is done so that the cached filename  is the same, with our with the token.

It stands to reason that if someone implemented their own signing key functionality, they may not use the `token` parameter at all, meaning it cannot be removed when generating a filename, since it's not known. It's possible they could even use more than one parameter, depending on their particular implementation.

Begs the question, do we care? If someone enables or disabled URL signing, and by doing so invalidates all the cache, is that okay? I sort of think so.

**Comment by alexbilbie** [comment]
>  If someone enables or disabled URL signing, and by doing so invalidates all the cache, is that okay?

Yes it's okay - similar to changing the salt for a password hash

**Comment by reinink** [comment]
The more I think about it, the more I think that integrating the signing key directly into the server is problematic. For example, right now if you're using a signing key, you cannot do this:

```php
$glide->outputImage('image.jpg', [
    'w' => 100
]);
```

That won't work because no token was provided. But that is sort of silly, you shouldn't have to provide a token for an entirely server side manipulation.

**Comment by reinink** [comment]
I think it's better to just use the signing token functionality on it's own. As @alexbilbie once suggested, this could even be used as it's own StackPHP middleware.

It adds a little more configuration to Glide, but I think creates a better separation:

```php
// Validate signing key
$signKey = new League\Glide\SignKey('your-sign-key', 'http://example.com');
$signKey->validate($request);
```

**Comment by reinink** [comment]
It almost makes me wonder if there is a good HTTP signatures package already available that could be used instead.

**Comment by alexbilbie** [comment]
HTTP signatures are really easy to do, I don't think we need a 3rd party library.

I implemented it here https://github.com/thephpleague/oauth2-server/blob/master/src/TokenType/MAC.php#L104-L117

**Comment by reinink** [comment]
Okay cool, because I wasn't all that interested in another dependency, and the only [standard](http://tools.ietf.org/html/draft-cavage-http-signatures-03) I could find appears to require headers to send the signature, which isn't going to work in this case.

**Comment by reinink** [comment]
Done d4a22b37eea1698218e85122583946786367f71d
