### ISSUE TITLE
[Laravel 5.3] SignatureException: Signature is not valid

### ISSUE THREAD

**Issue by TnCoders** [thephpleague/glide#173]
Hello,

Im implementing Glide in Laravel so this is my Setup:

**My Composer.json**

`"league/glide-laravel": "^1.0"`

****My route : **** 
`Route::get('/photos/{path}', 'ImageController@show')->where('path', '.*');` 

**My ImageController:** 

`
namespace App\Http\Controllers;

use Illuminate\Contracts\Filesystem\Filesystem;
use League\Glide\Responses\LaravelResponseFactory;
use League\Glide\ServerFactory;
use League\Glide\Signatures\SignatureFactory;
use League\Glide\Signatures\SignatureException;

class ImageController extends Controller
{
    public function show(Filesystem $filesystem, $path)
    {

        try {
            // Set complicated sign key
            $signkey = 'v-LK4WCdhcfcc%jt*VC2cj%nVpu+xQKvLUA%H86kRVk_4bgG8&CWM#k*b_7MUJpmTc=4GFmKFp7=K%67je-skxC5vz+r#xT?62tT?Aw%FtQ4Y3gvnwHTwqhxUh89wCa_';

            // Validate HTTP signature
            SignatureFactory::create($signkey)->validateRequest($path, $_GET);

                 } catch (SignatureException $e) {
                    return $e;
                }

            $server = ServerFactory::create([
                'response' => new LaravelResponseFactory(app('request')),
                'source' => $filesystem->getDriver(),
                'cache' => $filesystem->getDriver(),
                'watermarks' => $filesystem->getDriver(),
                'source_path_prefix' => 'photos',
                'cache_path_prefix' => 'photos/.cache',
                'watermarks_path_prefix' => 'photos/watermarks',
                 'base_url' => 'img',
        ]);
             return $server->getImageResponse($path, request()->all());

       
    }`

**In my welcome view :** 

`
use League\Glide\Urls\UrlBuilderFactory;

// Set complicated sign key
$signkey = 'v-LK4WCdhcfcc%jt*VC2cj%nVpu+xQKvLUA%H86kRVk_4bgG8&CWM#k*b_7MUJpmTc=4GFmKFp7=K%67je-skxC5vz+r#xT?62tT?Aw%FtQ4Y3gvnwHTwqhxUh89wCa_';

// Create an instance of the URL builder
$urlBuilder = UrlBuilderFactory::create('/photos/', $signkey);

// Generate a URL
$url = $urlBuilder->getUrl('foot.jpg', ['w' => 600]);

// Use the URL in your app
`
echo  the image and the output is this : 

`http://glide.dev/photos/foot.jpg?w=600&s=fd56175e87ec447291598f2927482c1f`

**and i got this :** 
`League\Glide\Signatures\SignatureException: Signature is not valid.`

**Comment by TnCoders** [comment]
It's me Again I Come Across a Solution So for any one having problem This is my Code : 

**My Route:**

`Route::get('/photos/{file}', 'ImageController@render')->where('file', '.+');`

**ImageController**

`namespace App\Http\Controllers;

use Storage;
use Illuminate\Contracts\Filesystem\Filesystem;
use App\Http\Requests;
use Illuminate\Http\Request;
use League\Glide\ServerFactory;
use League\Glide\Signatures\SignatureFactory;
use League\Glide\Signatures\SignatureException;
use League\Glide\Filesystem\FileNotFoundException;
use League\Glide\Responses\LaravelResponseFactory;`
`class ImageController extends Controller
{
    function render($file, Request $request,Filesystem $filesystem) {
        try {
            // Validate HTTP signature
            SignatureFactory::create(env('GLIDE_SIGNATURE'))
                ->validateRequest('photos/' . $file, $request->all());

            $server = ServerFactory::create([
                // Cache filesystem
                'cache' => $filesystem->getDriver(),
                // Cache filesystem path prefix
                'cache_path_prefix' => 'cache',
                // Source filesystem
                'source' => $filesystem->getDriver(),
                // Source filesystem path prefix
                'source_path_prefix' => 'photos',
                // Response
                'response' => new LaravelResponseFactory(),
                'watermarks_path_prefix' => 'photos/watermarks',
                'watermarks' => $filesystem->getDriver(),
                // Default image manipulations
                'defaults' => [
                    'q' => 80,
                ]
            ]);

            return $server->getImageResponse($file, $request->all());
        } catch (SignatureException $e) {
            // Forbidden
            abort(403);
        } catch (FileNotFoundException $e) {
            // Not Found
            abort(404);
        }
    }`

**In My View :** 
` <?php

use League\Glide\Urls\UrlBuilderFactory;



// Create an instance of the URL builder
$urlBuilder = UrlBuilderFactory::create('/photos/', env('GLIDE_SIGNATURE'));

// Generate a URL
$url = $urlBuilder->getUrl('foot.jpg', [
    'w' => 200,
    
    'fit' => 'crop',
    'con' => 25,
    'mark' => 'sigle.png',
    'markw' => 20,
    'markh' => 20,
    'markpos' => 'top-right',
    'markalpha' => 50
    
    ]);


echo img src="$url">
`
That's All Hope that will Help someone

**Comment by tnylea** [comment]
@TnCoders Thanks man! You just saved me a lot of time 👍

**Comment by reinink** [comment]
Glad ya'll got this figured it.
