### ISSUE TITLE
To make small images in big size ,zoom image without pixel like Uploadcare

### ISSUE THREAD

**Issue by NewTimeBox** [thephpleague/glide#174]
I have seen that uploadcare zoom images when image size is smaller than requested sizes and it seems like it return  small image and gave more height and width with html,but Glide make it bigger but with pixels.For example 
![small_image](https://ucarecdn.com/735d09e7-6a76-4a00-9fcd-64259d2f7e38/-/resize/1200x/)

**Comment by Alex12346123** [comment]
I have look at it and its true,I have not figure out yet how to solve it but I think there is a simple sollution

**Comment by NewTimeBox** [comment]
@reinink How can I solve it?

**Comment by wbadrh** [comment]
You can use the parameter: `fit` with the property of `max`.
This way, the image won't be upscaled.

Documentation can be found here:
http://glide.thephpleague.com/1.0/api/size/ Section: 'Fit'

`<img src="kayaks.jpg?w=300&h=300&fit=max">`

![Example fit=max](https://glide.herokuapp.com/1.0/kayaks.jpg?w=300&h=300&fit=max)

**Comment by reinink** [comment]
Thanks for helping out here @wbadrh!
