### ISSUE TITLE
How to get bytes of returned image before it returned?

### ISSUE THREAD

**Issue by Alex12346123** [thephpleague/glide#175]
I want to get bytes of image that returned .I use `$server->outputImage` method so how can I get filesize of image?I want to get how much byte image contains and also return image itself.Is that possible?

**Comment by Jon123123** [comment]
This is also my problem,I have worked on it a lot but no result :(.I think bytes of images is depend on width and height .So if we calculate them correctly it can work but will not be true for most of time because there are more options than only dimensions and also we don't know how they are related with bytes.
I realy need solution of this

**Comment by Alex12346123** [comment]
Okay how can we solve this?because my website  is depend on this problem.

**Comment by Jon123123** [comment]
@reinink  does Glide contain this functionality?

**Comment by wbadrh** [comment]
Glide uses [Flysystem](https://github.com/thephpleague/flysystem)
Depending on your use case you can implement something like this:
```
$server = League\Glide\ServerFactory::create([
    'source' => 'path/to/source/folder',
    'cache' => 'path/to/cache/folder',
]);

$cache = $server->makeImage($path, $params);
$bytes = $server->getCache()->getSize($cache);

echo $bytes;
```
Same as: [->outputImage()](https://github.com/thephpleague/glide/blob/master/src/Server.php#L461)
[Content-Length header](https://github.com/thephpleague/glide/blob/master/src/Server.php#L466)

``
Documentation:
- [Setup with factory](http://glide.thephpleague.com/1.0/config/setup/)
- [Get the cache file system, getCache()](http://glide.thephpleague.com/1.0/config/advanced-usage/)
- [$size = $filesystem->getSize('path/to/file.txt');](http://flysystem.thephpleague.com/api/)

**Comment by reinink** [comment]
Thanks for helping out here @wbadrh!
