### ISSUE TITLE
cannot be displayed because it contains errors

### ISSUE THREAD

**Issue by Rinkesh1993** [thephpleague/glide#179]
$this->app->bind(
			'Illuminate\Contracts\Auth\Registrar',
			'App\Services\Registrar'
		);
		
        //
        $this->app->singleton('League\Glide\Server', function ($app) {
						
				$filesystem = $app->make('Illuminate\Contracts\Filesystem\Filesystem');
				
				return \League\Glide\ServerFactory::create([
					
					'source' => 'uploads/',
					'cache'  => $filesystem->getDriver(),
					'source_path_prefix' => 'images',
					'cache_path_prefix' => 'uploads/.rin',
					'base_url' => 'img',
					
				]);
			
			});

**Comment by Rinkesh1993** [comment]
Solve my issue (remove space before php tag in route)

<?php
Route::group(array('middleware' => ['web'], 'module' => 'Web', 'namespace' => 'App\Modules\Web\Controllers'), function () {
	// For front website

**Comment by reinink** [comment]
Yep, that would do it. Glad you got it figured out! 👍
