### ISSUE TITLE
Add device pixel ratio (DPI & DPR)

### ISSUE THREAD

**Issue by reinink** [thephpleague/glide#18]
To simplify generating larger images for higher pixel density devices, it might be helpful to add an additional function to the `Size` manipulator. Following what [Imgix does](http://www.imgix.com/docs/reference/pixeldensity), I propose a new adding `dpr` function. For example:

```
kayaks.jpg?w=500&dpr=1.5
```

This can be used in conjunction with exiting responsive image JavaScript libraries, like [Imager.js](https://github.com/BBC-News/Imager.js/), or even right in your media queries.

Or, we can use `dpi`, which is where things seem to be going with the CSS [media query resolution feature](http://caniuse.com/#feat=css-media-resolution). So instead of a ratio you would provide the target DPI, such as:

```
kayaks.jpg?w=500&dpi=300
```

Thoughts?

**Comment by pbaljet** [comment]
I think in front-end web development people use `dpr` a lot, but as you can see with this module (https://github.com/ryanve/res), it's quite easy to get the `dpi` of a device as well. So purely based on the popularity of both, I would say `dpr` is a better option for now.

**Comment by kintaro1981** [comment]
Both?
ASAP dpr so like you said it can be possibile to take advantage of libraries like Imager.js, but with DPI in the roadmap to be future proof.

**Comment by smazurov** [comment]
I think DPR is much easier to understand, and more standard, so my vote is for DPR

**Comment by reinink** [comment]
Closing this ticket. I've added the `dpr` functionality, and it has been merged into the master branch and will be tagged shortly when I release `v1.0`! Hopefully not long now.

Also, see the docs for this feature [here](http://glide.thephpleague.com/1.0/api/pixel-density/).
