### ISSUE TITLE
Performing same operations more than once

### ISSUE THREAD

**Issue by younkim** [thephpleague/glide#180]
Is it possible to repeat same operation more than once and have all of them apply to the image? For example, I'd like to add two borders to make a photo look like a picture frame using the `border` function. Currently, I can apply it once like this.

    $params['border'] = '10w,FFFFFF,shrink';

**Comment by reinink** [comment]
Sorry, this is not currently possible. You could create your own manipulator to do this, but you'd have to manually wire things up then. You can find instructions for that here: http://glide.thephpleague.com/1.0/config/setup/#setup-manually

Good luck! 👍
