### ISSUE TITLE
Animated Gif Resizing is not working and Glide remove animation of gif

### ISSUE THREAD

**Issue by NewTimeBox** [thephpleague/glide#181]
Resizing gifs is not working for Glide.When I tridd to resize gif images it is not working and it remove animation from gif

**Comment by cdowdy** [comment]
Intervention doesn't support animated GIF's so the animation would be removed with Glide. 

https://github.com/Intervention/image/issues/42  

See also https://github.com/thephpleague/glide/issues/110

**Comment by reinink** [comment]
Animated Gifs are not supported for exactly the reason's @cdowdy has mentioned. And that comes down to GD not supporting it. Sorry!
