### ISSUE TITLE
FileNotFoundException in Server.php line 497: Could not find the image `assets/images/news.jpg`.

### ISSUE THREAD

**Issue by umairali** [thephpleague/glide#183]
I am using this example in laravel 

[](http://glide.thephpleague.com/1.0/config/integrations/laravel/)

Every time I receive this error message. I think the problem is in image path can you please give me the exact image path idea if i want to use dynamic url for all images.

```
FileNotFoundException in Server.php line 497: 
Could not find the image `assets/images/news.jpg`.`
```

**Comment by wbadrh** [comment]
You need to route all images to a specific URL/Script.

```
$server = League\Glide\ServerFactory::create([
    'source' => 'assets/images',
    'cache' => sys_get_temp_dir(),
]);

$server->outputImage($_GET['file'], $_GET);
```

Create a .htaccess file in: assets/images

```
RewriteEngine on
RewriteRule ^.+$ /your_image_script.php?file=$0 [NC,L,QSA]
```

You can use:
`http://yourwebsite.com/assets/images/your_image.jpg?w=400&h=200`

Which is actually:
`http://yourwebsite.com/your_image_script.php?file=news.jpg&w=400&h=200`

**Comment by reinink** [comment]
Thanks for helping out here @wbadrh!
