### ISSUE TITLE
fpassthru() has been disabled for security reasons

### ISSUE THREAD

**Issue by kelvinhalim13** [thephpleague/glide#184]
Actually i can use league glide in localhost(XAMP) without any problem.
The Problem is when i trying to use the league glide in my **web hosting** 

I got this following error
`fpassthru() has been disabled for security reasons ../../vendor/league/glide/src/Server.php 475`

Why i got that following error ?

**Comment by reinink** [comment]
Sorry, never heard of `fpassthru` being disabled before. This function is used in the [outputImage](https://github.com/thephpleague/glide/blob/eded0a999c0bb4cababd2bf8496d1f790b024bf2/src/Server.php#L475) method.

I'd recommend creating your own response object that doesn't use this function. You can find instructions for that here: http://glide.thephpleague.com/1.0/config/responses/

Here's an example to start with: https://github.com/thephpleague/glide-symfony/blob/master/src/Responses/SymfonyResponseFactory.php

Good luck! 👍
