### ISSUE TITLE
Having issues with implmentation of crop, with anything other than crop itself such as crop-right or crop-top.

### ISSUE THREAD

**Issue by pokepud3** [thephpleague/glide#189]
So I implemented Glide, and I'm having an issue with the crop-right or any other crop other than crop. Any ideas what this could be? Crop works just fine oddly enough. 

http://www.dramaguru.net/images/titles/humsafar_1.jpeg , http://www.dramaguru.net/images/titles/humsafar_1.jpeg?w=195&h=264&fit=crop-right vs http://www.dramaguru.net/images/titles/humsafar_1.jpeg?w=195&h=264&fit=crop

**Comment by reinink** [comment]
What version of Glide are you using? This changed between version `0.3` and `1.0`.

**Comment by pokepud3** [comment]
I figured it out at the end but had a different "issue". Only with small
images I get this. Im on latest version.

http://dramaguru.net/images/titles/humsafar_1.jpeg?w=65&h=64&fit=crop-right
http://dramaguru.net/images/titles/humsafar_1.jpeg?w=265&h=164&fit=crop-right

Seeing jibberish.

**Comment by aleemb** [comment]
@pokepud3 It's a mime-type issue, the images are being servers as HTML. You may want to check your server configuration.

**Comment by pokepud3** [comment]
@aleemb It's not a code thing, but a server side thing? You think my htaccess or apache config's are off?

**Comment by aleemb** [comment]
@pokepud3 Probably best to start there. Could be related to output buffering settings but hard to say. Have no clue re your code or configuration.

**Comment by pokepud3** [comment]
@aleemb I checked the mime type and server config and it seemed fine... whats odd the large thumbs have the correct jpeg mime but the smaller ones switch to html... If you check the links above you'll see.

**Comment by aleemb** [comment]
@pokepud3 Yeah hence my suspicion that it has to do with output buffering or similar configuration. I haven't used Apache in years so not sure but if you have any URL rewrite rules via mod_rewrite I'd also check there.

**Comment by pokepud3** [comment]
@aleemb I tried the script on my localhost and it seems like it's not the server afterall, tried it with nothing other than laravel essentials in it and same issue persists. Very odd. Dunno why it's like this since implementation seems to work for all images with a content-length of 4100 of higher. If the content-length is lower it'll revert to a content-type of text/html and show the gibberish.  

@reinink Ever see anything like this?  On laravel 4.2.
