### ISSUE TITLE
Face detection

### ISSUE THREAD

**Issue by reinink** [thephpleague/glide#19]
It would be awesome to add face detection to the `crop` function. This might be a bit of a pipe dream. There is [this PHP package](https://github.com/mauricesvay/php-facedetection). Also, could be good to look at [this JavaScript project](https://github.com/auduno/clmtrackr).

Function would work like this:

```
kayaks.jpg?w=500&h=500&crop=face
```

**Comment by darrenpowers** [comment]
Yes, something like www.imgix.com and www.cloudinary.com support would be fantastic.

**Comment by reinink** [comment]
And interestingly I don't think it would take TOO much to implement, but I'm not sure it makes sense to build face detection into Glide itself. This is better served as a separate package. I sort of keep hoping that a package will pop up...there is already a number of them in Javascript. (ie. http://facedetection.jaysalvat.com/).

If I were to make this package I would build it in such as way that it simply returned the coordinates of the faces, and didn't actually do the cropping itself. This would allow it to be used with any sort of image manipulation library...like Glide.

**Comment by barryvdh** [comment]
This was also discussed in Intervention/image: https://github.com/Intervention/image/issues/75
I also looked at it but couldn't produce good results + it was very slow.

**Comment by reinink** [comment]
Yeah, someone who knows a thing or two about face detection needs to take the bull by the horns and make a good PHP library for this. I bet it would get used a LOT.

**Comment by reinink** [comment]
We maybe need to convince @jaysalvat with beer to create a PHP version of his JavaScript library. :)

**Comment by josegonzalez** [comment]
The problem is performance, or more specifically that certain tasks need to be written in C, delegated to other libraries - like image magic - or parallelized. All these things are annoying, and tbh solved better by other libraries/tools like thumbor.

**Comment by reinink** [comment]
Very fair point @josegonzalez, but if this can be done with JavaScript, surely it can also be done in PHP, no?

**Comment by josegonzalez** [comment]
Javascript gets web workers, which happen off the ui thread, can be parallelized and thus happen much faster than in PHP :(

**Comment by jaysalvat** [comment]
Hello all!

There are some PHP face detection projects.
https://github.com/mauricesvay/php-facedetection is one on them.

:)

**Comment by estahn** [comment]
thumbor's focal-point detection algorithm for facials and features is implemented through OpenCV (http://opencv.org). They also implement what they call "Lazy Detection" which is nothing more then a image processing queue based on redis.

**Comment by reinink** [comment]
Closing this issue for now. I love the idea of face detection in Glide, but it's too big of a feature for me to handle at this point. Further, I think it's probably better better handled by a lower level library, as @josegonzalez suggested.

**Comment by barryvdh** [comment]
For Javascript, there is: https://github.com/jwagner/smartcrop.js
So if anybody feels the urge to pick this up, I suggest to make a port ;)

**Comment by reinink** [comment]
Awesome @barryvdh, I hadn't seen this one before. Thanks for sharing.
