### ISSUE TITLE
Request with .svg throws "Unable to read image from path"

### ISSUE THREAD

**Issue by daniel-keller** [thephpleague/glide#196]
I'm running Laravel v5.2 with Glide v1.2.2 using the league/glide-laravel package. When attempting to process an svg I get the error "Unable to read image from path (/tmp/Glide6MNNCj)". I can process other image formats without trouble (png, jpg, tiff, etc.).
In this simple example I'm attempting to convert a svg file to a jpg while relying on a local source and cache.

```
public function index(Request $request, Server $server)
{
    $filesystem = new Filesystem(new Local(public_path()));

    $server = ServerFactory::create([
        'response' => new LaravelResponseFactory($request),
        'source' => $filesystem,
        'cache' => $filesystem,
        'cache_path_prefix' => '.cache',
        'driver' => 'imagick',
        'base_url' => '/img/'
    ]);

    $request['url'] = '/images/for_records/image_not_found_lg.svg';
    $request['fm'] = 'jpg';
    return $server->getImageResponse($request['url'], $request->all());
}
```
Does Glide only support certain formats? or am I doing something wrong?

**Comment by cdowdy** [comment]
Glide uses Intervention and these are the formats it can manipulate depending on the driver
http://image.intervention.io/getting_started/formats as of this time SVG isn't one of the formats

**Comment by daniel-keller** [comment]
Thanks for the quick response! I figured it was unsupported but couldn't find it anywhere in the documentation.

**Comment by cdowdy** [comment]
If you use imagemagick you can probably get away with it with something like
https://github.com/Intervention/image/issues/580 or some other imagemagick code haha
