### ISSUE TITLE
Minimum width work

### ISSUE THREAD

**Issue by amorev** [thephpleague/glide#198]
Thank you for Glide. It's awesome. I found some bug

![redoctober1](https://cloud.githubusercontent.com/assets/8593411/26777605/8748f756-49e6-11e7-95d0-a85e0d8f2e51.jpg)

File in attachment cannot be cropper by width less than 156 pixels. At width=156px everything is ok. But at width 155px i see this:
![image](https://cloud.githubusercontent.com/assets/8593411/26777642/ae008512-49e6-11e7-9bfd-bd6a76f22b87.png)

What is wrong? How can I fix this? Thanks!

**Comment by Atles** [comment]
Same problem here. =/

**Comment by johannesschobel** [comment]
Hey @Atles and @zvinger - I have the same issue on some picture in my application as well. 
Did someone managed to solve it? I found out, that setting the `default-quality` to `100` will "decrease" the limit, where this breaks. But it is not possible to generate a `10x10` image, nonetheless.. 

Is @reinink aware of this issue?

**Comment by ADmad** [comment]
This sounds related to https://github.com/thephpleague/glide/pull/310 which has been fixed.
