### ISSUE TITLE
Question about pictures compression 

### ISSUE THREAD

**Issue by InfinityWebMe** [thephpleague/glide#199]
Hello,

How increase the compression for the image generated by glide ? 

I use the Google tool "pagespeed" and it tells me that the images need to be better compressed.

Any idea how to do that ? 

Thanks a lot :)

**Comment by reinink** [comment]
Hello! Yes, this is possible for jpegs using the quality `q` setting. For example:

```php
<img src="kayaks.jpg?w=500&q=25">
```

Full details here: http://glide.thephpleague.com/1.0/api/encode/

Good luck!

**Comment by InfinityWebMe** [comment]
@reinink  Thanks but i not speak about the quality but compression like this package https://github.com/approached/laravel-image-optimizer who use this lib pngquant gifsicle jpegoptim

**Comment by reinink** [comment]
Understood. Glide doesn't support this at this time. However, it has been asked for before. See #167.
