### ISSUE TITLE
Color Quality even on quality 100

### ISSUE THREAD

**Issue by notflip** [thephpleague/glide#201]
![screen shot 2017-07-07 at 11 26 45](https://user-images.githubusercontent.com/4146384/27952080-5be178ba-6307-11e7-91f0-f15f534ad61d.png)

On the **left is the Glide image**, on the right is the original, something seems to happen with the colors. This is the code I'm using

    return \League\Glide\ServerFactory::create([
        'source' => "uploads/$folder/",
        'cache' => "uploads/$folder/.cache",
    ])->outputImage($filename, ['w'=>800,'h'=>600,'fit'=>'crop', 'q'=>100]);

**Comment by reinink** [comment]
Hmm, honestly, I'm not sure what's happening here. Glide delegates all of it's work down to the Intervention library, which then delegates to GD or ImageMagick. This probably has to do with color profiles being different from the source image than what the server outputs, but I'm really just speculating. You might want to see if anyone has mentioned this in the Intervention library issues, or even for GD (if that's what you're using). Glide itself doesn't set any color settings at all.

Sorry I cannot be more helpful that that! Please report back if you do figure out the issue.
