### ISSUE TITLE
Why you have limited Intervention limits ?

### ISSUE THREAD

**Issue by ihasanov** [thephpleague/glide#205]
Intervention support adding text to image, but glide didn't, can you add it ?
Intervention supports orientation without any limit, why Glide only supports ['auto', '0', '90', '180', '270']  ? There are a lot of feature that Intervention has, but Glide has not

**Comment by NewTimeBox** [comment]
@reinink you can look at http://image.intervention.io/api/

**Comment by jbrooksuk** [comment]
Glide is a wrapper around Intervention. You can add this :)

**Comment by tgalopin** [comment]
Closing but happy to review PRs
