### ISSUE TITLE
The SymfonyResponseFactory issue with Symfony acting as a reverse proxy

### ISSUE THREAD

**Issue by mikemix** [thephpleague/glide#207]
When using the `SymfonyResponseFactory` as response factory, the returned `StreamedResponse` object prevents Symfony acting as a reverse proxy from caching thumbnail's contents. In result, the cache file inside the `http_cache` directory is empty and malformed output is sent to the browser.

**Comment by reinink** [comment]
Interesting. The streamed responses are pretty important for loading images in chunks, especially from remote storage locations. If this isn't the behaviour you want, I'd suggest simply creating your own response factory. It shouldn't take much. Take a look at the [docs here](http://glide.thephpleague.com/1.0/config/responses/#custom-responses).

You'll probably just want to take the existing `SymfonyResponseFactory` [class as a starting point](https://github.com/thephpleague/glide-symfony/blob/master/src/Responses/SymfonyResponseFactory.php), and modify it.

Good luck! 👍

**Comment by mikemix** [comment]
That's what I did and it worked. However this issue might be worth mentioning in your docs.

**Comment by reinink** [comment]
Oh nice! If you wanted to PR an addition to [those docs](https://github.com/thephpleague/glide/blob/master/docs/1.0/config/responses.md), that'd be great! ❤️
