### ISSUE TITLE
Need exact width and height

### ISSUE THREAD

**Issue by chwakil** [thephpleague/glide#214]
Hi, I need to resize image as for mobile device width and height exactly. I tried like below but not successful
e.g w=720&h=1280&fit=crop" but the resulting image is of size width=720 & height=480 and this does not fulfill my requirement. I also tried with fit=fill but result is same.
Please help.

**Comment by reinink** [comment]
That is the correct way to do that, as per [our documentation](http://glide.thephpleague.com/1.0/api/crop/):

```html
<img src="kayaks.jpg?w=300&h=300&fit=crop">
```

What often happens in these situations is that your URL is loaded the source image directly, and it's not going through PHP. You'll want to make sure that isn't the case. Test this by "dying-and-dumping" in your Glide controller/endpoint to make sure it's getting there.

**Comment by chwakil** [comment]
I am doing like this
```
$app = new \Slim\App();

$app->get('/img[/{params:.*}]', function ($request, $response) {
    $w = $request->getParam('h');
    if (!empty($w))
    {
        $server = ServerFactory::create([
                    'source' => '../test_images',
                    'cache' => '../test_images/cache',
                    'response' => new SlimResponseFactory(),
        ]);

        return $server->getImageResponse($request->getAttribute('params'), $request->getQueryParams());
    }
    
});

$app->run();
```
what should i change?

**Comment by Art4** [comment]
Your original images seams to be smaller than the requested image, so you should take a look at `fit=fill` or `fit=stretch`.

http://glide.thephpleague.com/1.0/api/size/#fit-fit

**Comment by chwakil** [comment]
The issue occurs only when accessing the php code directly otherwise it is working fine.
