### ISSUE TITLE
Artifacts when downscaling PNG using GD

### ISSUE THREAD

**Issue by brendt** [thephpleague/glide#218]
Given a PNG file with large areas of the same color, when downscaling this image this same color seems to be split into small areas of two colors. This causes the filesize of a downscaled image to be much larger.

An example with this source image:

![original](https://user-images.githubusercontent.com/6905297/34781684-c6ff1b2c-f626-11e7-9284-935cadf3707f.png)

Downscaling it to a width of 1606 px, gives this image as a result:

![broken](https://user-images.githubusercontent.com/6905297/34781713-de4e51ee-f626-11e7-83aa-539b4b051e08.png)

Nothing seems wrong at first glance, the white background however now consists of small areas of two colors: `#ffffff` and `#fefefe`. Kaleidoscope can visualise this difference:

<img width="821" alt="screen shot 2018-01-10 at 16 51 33" src="https://user-images.githubusercontent.com/6905297/34781788-100590f8-f627-11e7-88cc-d17b56bea071.png">

When switching to `imagick` as the driver, this problem doesn't happen. The image was generated using one of our packages, which is just a wrapper around glide. This is the script I used:

```php
use Spatie\Image\Image;

require_once __DIR__ . '/vendor/autoload.php';

$inputPath = __DIR__ . '/images/original.png';
$outputPath = __DIR__ . '/images/test.png';

@unlink($outputPath);
copy($inputPath, $outputPath);

Image::load($outputPath)
    ->useImageDriver('gd')
    ->width(1606)
    ->save();
```

This is the package we're using: https://github.com/spatie/image

You can see that the actual conversions are done by Glide: https://github.com/spatie/image/blob/master/src/GlideConversion.php#L50

**Comment by mcoenca** [comment]
Hello ! Having mainly pngs with same colors, I am also facing very strange numbers in glide downscaling. 2x pixel downsize can result in 3x bigger image. 

Which kills a bit the purpose of this package...

I saw you fixed the issue in an underlying (not clear ?) package. 
Is it fixed in Glide directly... or not ? Could you point to steps to fix this ? 

Thanks @brendt 

For info:
Original Image
![image](https://user-images.githubusercontent.com/6507140/41620071-e2a72f44-7408-11e8-9495-23e3302ef1a6.png)

Reduced to 1800 width..
![image](https://user-images.githubusercontent.com/6507140/41620047-cc0e8962-7408-11e8-85e9-d9946feaa6ca.png)

**Comment by brendt** [comment]
@mcoenca the root problem is not in a package we maintain. The only thing we did was configuring Glide more thoroughly so that the problem is avoided. This is the commit: https://github.com/spatie/laravel-medialibrary/commit/d96ce0e22db7069abf335424be65ed0232c0d135

I should note that we're using our own image wrapper in that commit, but it uses glide under the hood: https://github.com/spatie/image 

So we fixed it by running a bunch of optimisers on top of the generated image, but that original generated image still has a lot of artifacts.

**Comment by brendt** [comment]
@reinink any thoughts on this?

**Comment by barryvdh** [comment]
Glide is in turn using https://github.com/Intervention/image so perhaps raise an issue there? Or try to recreate it using Intervation Image directly?
@olivervogel Might have some information?

**Comment by reinink** [comment]
Yeah, sorry, like @barryvdh is suggesting I think this is outside of the scope of Glide. Unless, of course, you can find something I'm doing with Glide that might be causing this.

Going to close this for now. Please report back if you do find this to be a problem with Glide.
