### ISSUE TITLE
Focal Point Selection Help

### ISSUE THREAD

**Issue by chwakil** [thephpleague/glide#219]
Hi,
Would you please explain this,
Crop Focal Point
This is defined using two offset percentages: crop-x%-y%.

<&fit=crop-25-75">

How actually this x% and y% works. I am not getting desired results and need help to understand it. Also does any body know, how to select desired focal points percentage from an image easily so that it can later be used with this wonderful Glide library.

**Comment by chwakil** [comment]
Okay, what I understand, x is 25% from left and 75% remaining is y.

**Comment by reinink** [comment]
Sorry, not exactly.

The first value is 25% from the left, yes, but the second value represents the vertical positioning, so in your case it 75% from the top.

**Comment by chwakil** [comment]
Thanks for reply. But I observed that second parameter has no effect actually. I tried by keeping first parameter constant and change second parameter but the result is same all the time something like this:

glide/index.php/img/20180202180359_305327369.jpeg?w=720&h=1280&fit=crop-62-28
glide/index.php/img/20180202180359_305327369.jpeg?w=720&h=1280&fit=crop-62-70
glide/index.php/img/20180202180359_305327369.jpeg?w=720&h=1280&fit=crop-62-90
glide/index.php/img/20180202180359_305327369.jpeg?w=720&h=1280&fit=crop-62-0

All cases result is same.

**Comment by reinink** [comment]
Depending on the height of your image, it may not. For example, if your crop uses the full image's height, that value will not do anything. It's a focal point...

**Comment by chwakil** [comment]
The image, i am using in my experiment has width 4757 and height 2672 and I am trying to crop it to 720x1280 (desired image) like above. And all images cropped with varying focal point y% are the same as in above example.

**Comment by chwakil** [comment]
@reinink can you give any example of offset y% in action because I am not able to understand it's usage.
