### ISSUE TITLE
Is there a way to save image to disk?

### ISSUE THREAD

**Issue by chwakil** [thephpleague/glide#220]
I want to generate thumbnails when uploading images. Is there any way using Glide, generate thumbnail and save to folder?

**Comment by Art4** [comment]
I would recommend to use the underlying intervention/image library directly for this purpose.
https://github.com/intervention/image

**Comment by chwakil** [comment]
Thanks. But Glide has option for focal point crop image.

**Comment by Art4** [comment]
After upload you can use getImageResponse() with your parameters to create a thumbnail in the cache folder:

```
$server->getImageResponse(
    'uploaded_image.jpg',
    ['w' => 150]
);
```
