### ISSUE TITLE
upgrade to Laravel 5.6 issue

### ISSUE THREAD

**Issue by brusselsregular** [thephpleague/glide#222]
Hi,

Thanks for creating this awesome package!

I'm trying to upgrade to Laravel 5.6

Laravel 5.6 requires symfony/http-foundation 4.0 but glide-symfony requires http-foundation 2.3 or 3.0, so is it impossible to install Laravel 5.6 with this package? (glide-laravel)

**Comment by reinink** [comment]
This was recently changed:

https://github.com/thephpleague/glide-symfony/commit/dbf9b8e1971405e7b9a9e0faf3b2d7a4bf123776

Make sure you're using the `1.0.3` release of `glide-symfony` and you should be good.

**Comment by brusselsregular** [comment]
@reinink Thank you so much! This did the trick 👍
