### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by chwakil** [thephpleague/glide#225]
Crop and resize of image below resolution 8000x8000 is fine, but above this resolution app crashing with out of memory error. Also tried by increasing php memory limit to 512MB but same crash on large images. Any help to resolve the issue?

**Comment by reinink** [comment]
Not to deflect here, but Glide is really just a layer on top of [Intervention Image](http://image.intervention.io/), which is a layer on top of GD or imagemagick. This is likely a problem at one of those two layers, so I'd recommend looking there for help. Sorry I cannot be more helpful than that.
