### ISSUE TITLE
mozjpeg support

### ISSUE THREAD

**Issue by joeworkman** [thephpleague/glide#229]
I have been using glide on a new project and loving it. Today I was playing around with mozjpeg (https://github.com/mozilla/mozjpeg) and find its jpeg compression pretty mind blowing. I would love to figure out how I could get glide to optimize my jpeg using it. 

This may not be anything that you specifically can do, I am not sure. Do you happen to know how it could be accomplished though?

**Comment by ADmad** [comment]
You can create your own manipulator class and add it at the end of the manipulators list. Check https://github.com/YannikFirre/glide-optimizer for example.
