### ISSUE TITLE
NoDecodeDelegateForThisImageFormat `JPEG' @ error/constitute.c/ReadImage/50

### ISSUE THREAD

**Issue by tudor2004** [thephpleague/glide#237]
Can anybody help with the following error?

```
NoDecodeDelegateForThisImageFormat `JPEG' @ error/constitute.c/ReadImage/50
  9
```

I'm not sure what kind of library I'm missing, this is my docker file 

```
FROM php:7.1-fpm-alpine

# intl, zip, soap
RUN apk add --update --no-cache libintl icu icu-dev libxml2-dev \
    && docker-php-ext-install intl zip soap

# mysqli, pdo, pdo_mysql
RUN docker-php-ext-install mysqli pdo pdo_mysql

# mcrypt, gd, iconv
RUN apk add --update --no-cache freetype-dev libjpeg-turbo-dev libmcrypt-dev libpng-dev \
    && docker-php-ext-install iconv mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd

# gmp, bcmath
RUN apk add --update --no-cache gmp gmp-dev \
    && docker-php-ext-install gmp bcmath

# redis, apcu
RUN docker-php-source extract \
    && apk add --no-cache --virtual .phpize-deps-configure $PHPIZE_DEPS \
    && pecl install redis \
    && pecl install apcu \
    && docker-php-ext-enable redis apcu \
    && apk del .phpize-deps-configure \
    && docker-php-source delete

# imagick
RUN apk add --update --no-cache autoconf g++ imagemagick-dev libtool make pcre-dev \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && apk del autoconf g++ libtool make pcre-dev

# git client, mysql-client
RUN apk add --update --no-cache git mysql-client

# pcntl
RUN docker-php-ext-install pcntl

RUN sed -i -e 's/listen.*/listen = 0.0.0.0:9000/' /usr/local/etc/php-fpm.conf

RUN echo "expose_php=0" > /usr/local/etc/php/php.ini

CMD ["php-fpm"]
```

**Comment by cdowdy** [comment]
That's an imagick error. You need to make sure you have the proper "delegates" built in. Open up a command line and type ```convert -version```  and make sure jpeg is listed.

**Comment by tudor2004** [comment]
@cdowdy convert -version says `sh: convert: not found´

**Comment by tudor2004** [comment]
ok, I ended up using another base image for PHP that is not based on alpine. the rest of the dockerfile logic remained the same

**Comment by ambis** [comment]
For other who end up here, I was having the exact same problem (well, different line number in the error). My Dockerfile was pretty much identical for anything related to imagick.

My problem was that I was missing imagemagick itself. After adding apk add for imagemagick, problem was fixed and `php -r 'print_r(Imagick::queryFormats());'` list was no longer empty, it had 226 keys including JPEG etc.

**Comment by julitroalves** [comment]
Using alpine image docker i just added this to my image and rebuild docker image.

`RUN set -ex \
    && apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS imagemagick-dev libtool \
    && export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" \
    && pecl install imagick-3.4.3 \
    && docker-php-ext-enable imagick \
    && apk add --no-cache --virtual .imagick-runtime-deps imagemagick \
    && apk del .phpize-deps`

**Comment by michabbb** [comment]
@julitroalves just wanted to let you know: your lines saved my problem 👍

**Comment by michabbb** [comment]
❓ **a question to all:** I use https://github.com/docker-slim/docker-slim to tiny my PHP image. the fantastic thing is: the size shrinks from 500MB to 100MB *BUT* that´s only because a lot of things gets deleted.
the base-image shows me every image format `Imagick::queryFormats()` : but the tiny image doesn´t show anything, so I am sure, there are some files somewhere, that must not be deleted. does anybody has an idea where these files are ? because docker-slim supports the `--include-path` option, to keep some folders (or files) from seeing deleted. thanks for any help!!

**Comment by ADmad** [comment]
Closing as the issue seems to be resolved and isn't directly related Glide's code.
