### ISSUE TITLE
Status 500 when using very large images (resolution & filesize) in production

### ISSUE THREAD

**Issue by niklue** [thephpleague/glide#242]
I'm currently working on a imageboard like SPA. In my backend I use glide to resize the images in my public storage on demand. Now, everything works fine on my dev environment but when I ship it to my shared hosting production environment (for testing) the very large images return status 500. 
We're talking 5000x5000+ and 10mb+. The normal images work fine though (3000+4000 Handycam quality). How do I prevent this from occurring other than setting an upload limit via validation? My php.ini is the same in developement and production. Thanks.

**Comment by shashikantx** [comment]
Have you fiddled with execution times?

**Comment by JackTheTripper** [comment]
Thanks for your reply,
that seems to have an impact.
max_execution_time=200 seems like a good solution.
