### ISSUE TITLE
Wordpress integration?

### ISSUE THREAD

**Issue by codeagencybe** [thephpleague/glide#244]
Hello,

I just stumbled upon this amazing tool after searching and learning hours about Cloudinary and IMGIX. 

I'm looking for a solution to manipulate images in Wordpress (specific WooCommerce products). 
Does Glide have some sort of plugin to use for Wordpress, or can somebody help me how to use this in combination with Wordpress. 

Basically want I want to achieve/setup:
1. upload images to Wordpress
2. when assign featured image to a product, for that product only, the image needs to be rescaled (FIT) *** without cropping *** to a square size (new canvas) and space around filled with a bg color and saved with the new format.
3. all assets are offloaded from local server to Amazon S3, so normally this function will re-upload the image to Amazon S3 bucket
4. all assets are hosted by CDN from the Amazon S3 for fast asset delivery. 

Why we want this:
Because often, the image files we receive have a wide variety of dimensions (portrait, landscape, ...) and it looks horrible on the product overview pages. Wordpress has no function to make square images WITHOUT cropping. 
So we need an external solution that handles this. 

We have tried Cloudinary and IMGIX, all work fine, but they all require to use their CDN which we don't need. 
I hope with Glide we can do this? 

If you can help me with this, please let me know! 

Thanks!

**Comment by jawngee** [comment]
You don't need to use Imgix's CDN.  You can use Cloudflare or any other CDN that can do an origin pull, you then just put that in front of Imgix.

I'm the author of Media Cloud (Imgix plugin for WordPress), but am looking to add glide support in.

**Comment by reinink** [comment]
Sorry, we don't have any built-in support for WordPress. It's a neat idea though!
