### ISSUE TITLE
Preloader Images

### ISSUE THREAD

**Issue by kodeine** [thephpleague/glide#246]
Hello, i was trying to generate a low sized preload images which would be the blurred version of the original image. Just like if you visit blogs at medium. The images show a blurred skeleton of the image and once loaded it shows the original image. Is there a way i can generate a blurred + lowest size possible image?
[like this image](https://ik.imagekit.io/demo/img/image8.jpeg?tr=w-400,h-300,bl-30,q-50)
I tried, blur 100 and quality 1 but it doesn't look good.

**Comment by baileylo** [comment]
You may want to try use progressive jpeg, http://glide.thephpleague.com/1.0/api/encode/#format-fm
