### ISSUE TITLE
No image showing

### ISSUE THREAD

**Issue by stailer** [thephpleague/glide#247]
Hello,

On 4 Ubuntu 18 machine, install via composer require league/glide OK
When web page is launching , image generating and cache are OK on 4 PC

But, on one PC, image is not display !
it's same Ubuntu/Php/Apache on 4 pc.

On server too, with nginx/debian, all is ok !

` $server->outputImage($actual_link[0], $_GET);`

After reinstall Ubuntu/Apache/Php, it's same : this PC not display image but generating is ok in cache directory... 

An idea ?

**Comment by baileylo** [comment]
If it's the same code everywhere, I'd imagine you have a config issue on the one machine that's not rendering the images correctly.

Can you give more information, like what's the response that you're seeing?

**Comment by stailer** [comment]
With breakpoint in glide, reponse from this code is false :

`$this->source->has($this->getSourcePath($path));`

But image is generating... just display is wrong. 

I think there is an exception FileNotFoundException... But directory and file exists. 
I don't understand why this pc only has this problem...
