### ISSUE TITLE
[Feature request] size new option: longe edge and short edge

### ISSUE THREAD

**Issue by jimblue** [thephpleague/glide#248]
**Resizing Image: Long Edge and Short Edge**

This is extremely handy when having landscape and portrait photo.
Should automatically adjust the rest of the dimensions.

**Comment by baileylo** [comment]
@jimblue I'm not sure exactly what you're asking for. Can you provide dimensions, what dimensions you're putting in then the dimensions after resize?

**Comment by baileylo** [comment]
I'm curious what your use case is. I've worked with on demand image resizers and will say that I've seen this feature, but I haven't seen it used. From my experience the general use case is I have a spot that is x pixels wide and I need this image to fit in it. This is a different use case from what your suggesting, I'm curious if you could tell me what you're doing with it?

**Comment by maximecolin** [comment]
@jimblue I think you can handle this case with the following parameters:

```
width: 1500
height: 1500
fit: contain
```
