### ISSUE TITLE
Webp support example

### ISSUE THREAD

**Issue by gijsroge** [thephpleague/glide#253]
Hi, on http://glide.thephpleague.com if I request a webp format the header still shows jpg.

https://glide.herokuapp.com/1.0/kayaks.jpg?&q=100&fm=webp
https://glide.herokuapp.com/1.0/kayaks.jpg?&q=100&fm=jpg

Is this just because the glide website is still on 1.0?

**Comment by reinink** [comment]
Correct, the website hasn't been updated for the webp release.

**Comment by litashg** [comment]
I have the same issue. glide version is 1.4 and header still says that image is image/png . 
My slug is /cache/1/VlKQJqBj8YYTXld2QHSdHvKzA1xMx-7J.png?w=1600&fm=webp&s=02e72c935dd913c376b6985ef8a06459 .
