### ISSUE TITLE
Encoding to webp

### ISSUE THREAD

**Issue by litashg** [thephpleague/glide#257]
Hi! I have an issue with encoding to .webp format.  
Seems like I can encode an image to any of supported formats like gif or png, except webp. When I try to encode to webp i get just broken jpg.  

Environment :  
php 7.2, ubuntu 14.04.1
WebP Support - enabled 
ImageMagick supported formats - webp
thephpleague/glide - version is 1.4 

Examples: 
Just jpg without formatting
https://storage.bkw-test.dev.aurocraft.com/cache/1/9mSOxE-Pz4_CD0pKi57CHyLDUt1dOaSd.jpg?w=1440&s=0d47354120e9c05fc013562dff594d9d

Jpg with formatting to webp
https://storage.bkw-test.dev.aurocraft.com/cache/1/9mSOxE-Pz4_CD0pKi57CHyLDUt1dOaSd.jpg?w=1440&fm=webp&s=892d5d8eb062b7aa727f1d03d10e5f54

Give me advice please. How can I fix that?

**Comment by litashg** [comment]
I found an answer. The problem was in imagick module.

**Comment by reinink** [comment]
Thanks for posting an update here @litashg.
