### ISSUE TITLE
Browser Caching enhancement

### ISSUE THREAD

**Issue by MrMoronIV** [thephpleague/glide#260]
I'm using glide without a file extension for my path, instead of `/img/image.jpg?w=500` I use `/img/image/?ext=jpg&w=500'. I use this so my NGINX isn't trying to look for the image internally as it will return a 404 header no matter what PHP pushes out.

The downside of this is that the browser really likes to have a file extension to enable caching of the generated image. However, there is a fix.

By adding an ETag header with an md5 hash of the $_GET var you send out a hash that the browser will send to glide the next time the same image is requested. At the top of your script:
```
$etag = md5(implode('.',$_GET));
```
Then before sending out the image:
```
header('ETag: "'.$etag.'"');
$server->outputImage($path, $_GET); // this probably has your own logix
```
Then somewhere at the start of your image script you put something like
```
if(isset($_SERVER['HTTP_IF_NONE_MATCH']))
{
	if($_SERVER['HTTP_IF_NONE_MATCH'] == '"'.$etag.'"')
	{
	    header("Cache-Control: max-age=2592000, must-revalidate");
	    header("HTTP/1.1 304 Not Modified");
	    exit();
	}
}
```
The browser will then use the cached image for 30 days. However, you are able to overwrite this caching behaviour since it is stated that it should revalidate, so your script is always called anyway. !00% control, but still cache in place.

My suggestion, let Glide send an ETag header (as a config option) and allow it to be checked. Or maybe if somebody reads this, do it manually like I did.

More info about the ETag header here (supported in all browsers):
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

**Comment by btxtiger** [comment]
This might be an option for you, this enables caching with nginx, and allows using the filename as route param. But remind, this will enable the unconfigurable default cache age from `vendor/league/glide/src/Server.php:469`, which is (regretfully) hardcoded to 1 year.  

```
# Images
location ^~ /api/img {
    expires 1d;
    access_log off;
    try_files $uri $uri/ index.php?$query_string;
}
```

**Comment by ADmad** [comment]
Handling caching headers can be done through server config as shown above or your application code. One can use their custom response factory too to generate response instances with required headers. So I don't think that anything needs to be changed for this in Glide's code..
