### ISSUE TITLE
Filenames For Cached Image 

### ISSUE THREAD

**Issue by pxwee5** [thephpleague/glide#264]
Is there a way to not use md5 hash on the output of the cached filenames? 
I'm looking to generate both `test.jpg` and `test.webp` at the same time. Filename must be the same but different ext. 

The cache filenames can also be `test-200w-100h.jpg` and `test-200w-100h.webp` for different size params. 

Is this possible with the 1.x version of Glide?

BTW, this is required based on Google's recommendation on serving webp images with Content Negotiation. https://developers.google.com/speed/webp/faq , where the server searches for a `.webp` file of the same name first before falling back to the original file.

**Comment by tgalopin** [comment]
Not currently possible AFAIK but planned in the next major of Glide (https://github.com/thephpleague/glide/issues/288)
