### ISSUE TITLE
Glide Image Manipulation Content Length Mismatch Glitch on Laravel 6

### ISSUE THREAD

**Issue by PhoenixPeca** [thephpleague/glide#265]
Hi,

I have just upgraded my framework to the new Laravel 6.0.0. However, I'm experiencing a random glitch/bug/error with [Glide](https://glide.thephpleague.com/) as shown in the screenshot:
![Screenshot](https://i.imgur.com/cTkjpfe.png)

Glide seems to work fine (most of the time).. But whenever, I fetch the image **without setting any manipulation parameters** through the the `ImageController`, I get a partial view of the image and an error in chrome's console: `net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)`. But this happens about every 3 out of 5 requests, randomly... Behaviour seems inconsistent because sometimes I get the full image, but sometimes I also get only part of the image as shown in the screenshot.

I reverted to the last laravel 5 release, and I haven't noticed this particular problem.

Regards,
Phoenix Eve Aspacio

**Comment by PhoenixPeca** [comment]
Could this be caused by an outdated dependency?

**Comment by PhoenixPeca** [comment]
Hi,

Sorry for bothering... Just solved my problem.
https://serverfault.com/questions/235154/permission-denied-while-reading-upstream

It wasn't a laravel/glide issue afterall..

Eitherway, this is a very nice package.. I was working on a project and was using gumlet (https://www.gumlet.com/) then I found this and settled..

Cheers to the developer!

**Comment by reinink** [comment]
👍
