### ISSUE TITLE
Handling cache in this particular situation

### ISSUE THREAD

**Issue by zefexdeveloper** [thephpleague/glide#270]
I have two folders: `temporary` and `permanent`, when the user uploads the image first goes to a temporary folder and later we move those images to a permanent folder.
I need to serve both the temporary and permanent folder images with glide functionalities but glide creates the cache with the path and folders.
How can I disable caching for the `temporary` folder or when moving an image from the temporary I remove the cache before?

**Comment by reinink** [comment]
Hmmm, you might want to consider setting up two different Glide servers, once for each use case here. That way you can control where the files go. Also, you can disable the cache if needed. See [here](https://glide.thephpleague.com/1.0/config/source-and-cache/).

Also, I wouldn't try to reuse the cache between the two locations. I would simply have Glide recreate the cache at the new location.

Also, if you look in the [advanced usage](https://glide.thephpleague.com/1.0/config/advanced-usage/) docs, you can see the `deleteCache($path)` function that you could use to delete the cache for a specific image. 

Hope that helps.

**Comment by zefexdeveloper** [comment]
By using the in memory caching is not actually disabling it right? I mean, it will be there allocating memory (won't that be a problem?).
I think I thought about a new solution instead of having two folders (temporary and permanent). I will only have one, the difference is that when the user uploads an image it will create an image of `Image` model putting the records on the database, later I can create a job to look for orphan `Image`'s and delete them both from the database and the system.
I think it's a better solution than moving things around right?
