### ISSUE TITLE
Difference between getImageResponse and outputImage

### ISSUE THREAD

**Issue by theprobugmaker** [thephpleague/glide#272]
It might be a newbie question but I see in the docs using `getImageResponse` in others code using `outputImage` so I don't really get the difference.

**Comment by pau1phi11ips** [comment]
`getImageResponse` should be used if you're using it in a Framework that needs the response passing thru it.

`outputImage` is used mainly when using bare bones PHP

See here: [https://glide.thephpleague.com/2.0/config/responses/](https://glide.thephpleague.com/2.0/config/responses/)
