### ISSUE TITLE
Not working with Laravel 7.0

### ISSUE THREAD

**Issue by vgavrilovikj** [thephpleague/glide#296]
I have followed the installation on the website, installed it through composer, and then I followed the Laravel integration: https://glide.thephpleague.com/1.0/config/integrations/laravel/ from the "Working example", however, once I implemented it and entered the image, I receive: Class 'League\Glide\Responses\LaravelResponseFactory' not found...

Can you please help me?

**Comment by tgalopin** [comment]
Perhaps are you missing the package https://github.com/thephpleague/glide-laravel ?
