### ISSUE TITLE
Weird Artifacts When Blurring Transparent PNG

### ISSUE THREAD

**Issue by aerni** [thephpleague/glide#297]
I want to create a low-resolution blurred image. Something like [this example](https://glide.herokuapp.com/1.0/kayaks.jpg?w=32&blur=100). My source image is a transparent PNG, which leads to weird artifacts. Blurring works as expected if the source image format is a JPG. I used a width of `32` and a blur of `100`.

**Full Resolution Image – Transparent PNG**
<img width="1182" alt="Full Resolution Image" src="https://user-images.githubusercontent.com/23167701/101158697-6ff94480-362c-11eb-9a8b-7abfb594f699.png">

**Blurred Transparent PNG**
<img width="1184" alt="Blurred PNG" src="https://user-images.githubusercontent.com/23167701/101158753-8c957c80-362c-11eb-8d32-07effe523421.png">

**Blurred JPG**
<img width="1187" alt="Blurred JPG" src="https://user-images.githubusercontent.com/23167701/101158778-9cad5c00-362c-11eb-85d8-9243b0e36078.png">

**Comment by tgalopin** [comment]
I'm not sure to understand this issue. What's supposed to happen? Technically, the blurred PNG is indeed blurred, even if the algorithm isn't the same.

**Comment by aerni** [comment]
I think I stumbled upon the algorithm. It just looks really awkward. The PNG doesn't look blurred at all. It's more like a block of black with smooth edges. I was confused because the results of the JPG look very different. Why would the PNG not look the same?

**Comment by tgalopin** [comment]
A transparent PNG cannot behave the same way as a white-background JPG, simply because transparency is the lack of color, not white. Keeping the shape when blurring a transparent PNG makes sense to me, and the precision of the blur probably has an impact on the result.

Perhaps should you implement your own manipulator that would reencode the PNG file in JPG with a white background at runtime and then run the blur? See https://glide.thephpleague.com/1.0/config/advanced-usage/ for details

**Comment by aerni** [comment]
Yeah, you're probably right. I used ImageKit – an image processing CDN – before switching to Glide. And the results there look very different though using the same source material.

This is the source image on ImageKit: https://ik.imagekit.io/michaelaerni/staging/tr:w-1296/assets/main/work/baerenmatte/mockups/baerenmatte_macbook_mockup_2000x1000-2x.png

And this is the same image blurred on ImageKit: https://ik.imagekit.io/michaelaerni/staging/tr:w-1296,bl-100/assets/main/work/baerenmatte/mockups/baerenmatte_macbook_mockup_2000x1000-2x.png

I was just confused as, why Glide would deliver a different result. But I'm no image processing expert. 😅

**Comment by ADmad** [comment]
Closing as the question seems to have been answered.
