### ISSUE TITLE
Flysystem 2.0 conflict

### ISSUE THREAD

**Issue by tomaskrejci79** [thephpleague/glide#298]
Hi,

love your work, unfortunetaly it is not possible to install Glide with Flysystem 2.0 installed. Will you upgrade this package? Thanks!

**Comment by tgalopin** [comment]
Hi! Yes it is planned :)

**Comment by tgalopin** [comment]
Work in progress here: https://github.com/thephpleague/glide/pull/301

**Comment by svnldwg** [comment]
This is merged already, but not released yet. Do you know when it will be released? For now I will work with dev-master.

**Comment by tgalopin** [comment]
I need to sync with @ADmad but I think I'll release tomorrow

**Comment by ADmad** [comment]
https://github.com/thephpleague/glide/releases/tag/2.0.0
