### ISSUE TITLE
I can't install it with my php 8.0.1

### ISSUE THREAD

**Issue by ed-mor** [thephpleague/glide#306]
Problem 1
    - facade/ignition is locked to version 2.4.1 and an update of this package was not requested.
    - facade/ignition 2.4.1 requires php ^7.2.5 -> your php version (8.0.1) does not satisfy that requirement.

**Comment by tgalopin** [comment]
This seems to be a problem from another package (facade/ignition apparently). Glide doesn't depend on it directly, could you run `composer why facade/ignition` to see what package requires it?

**Comment by ADmad** [comment]
Closing as the issue doesn't seem to be related to Glide.
