### ISSUE TITLE
Outputting image with a space in the filename fails when using a Request

### ISSUE THREAD

**Issue by jasonvarga** [thephpleague/glide#32]
When trying to load a file with a space (at a URL like `/img/my%20file.png`), it fails when using an instance of `Symfony\Component\HttpFoundation\Request`.

By failing, I mean we see a `NotFoundException: Could not find the image my%20file.png`.

``` php
public function serve($uri, \Illuminate\Http\Request $request)
{
  $server = ServerFactory::create([...]);

  // this fails:
  $server->outputImage($request);

  // this works: ($uri is 'my file.png' without the %20)
  $server->outputImage($uri, $request->query->all());
}
```

Both methods work when the filename has no spaces.

**Comment by reinink** [comment]
You are right, for some reason the HttpFoundation request's `getPathInfo()` method does not use `urldecoded()` function. This is actually right in the [docblocks](https://github.com/symfony/HttpFoundation/blob/master/Request.php#L908). I wonder if there is a different way this is supposed to be done with HttpFoundation.

Either way, your fix looks good. I'll try to get that patched in and a tagged very soon. Don't have time tonight unfortunately.

Thanks so much for your help with this! Much appreciated. Glide is still very new, so evidently there are a few little glitches still. :)
