### ISSUE TITLE
suggestion - VIPS image driver?

### ISSUE THREAD

**Issue by cardi777** [thephpleague/glide#320]
Hi I was wondering if in the future it may be possible allow VIPS as an image driver? Sounds like it has many advantages over both GD and imagick

**Comment by madalinignisca** [comment]
I doubt that glide needs to implement it. Glide is using [intervention/image](https://github.com/Intervention/image), and a [3rd party driver](https://github.com/osiemsiedem/intervention-image-vips-driver) already exists.

**Comment by ADmad** [comment]
Closing for reason stated above.
