### ISSUE TITLE
Problem installing on laravel 6

### ISSUE THREAD

**Issue by web1989** [thephpleague/glide#329]
could someone help me install it on my laravel 6?

**Comment by reinink** [comment]
It appears that Glide now requires Flysystem 2.0|3.0, but Laravel (as of version 8) still requires Flysystem 1.0 — meaning you can't use the latest version of Glide (2.x) with Laravel. Laravel is adding Flysystem 2.0 support in Laravel 9.0, set to be released in a few months.

**Comment by tgalopin** [comment]
Thanks @reinink !

Also, note you can still use Glide 1.0 if you want :) .
