### ISSUE TITLE
Images load time very slow any suggestions?

### ISSUE THREAD

**Issue by janekbar5** [thephpleague/glide#339]
Really like the glide and flexibility it gives. However the images loading time is very slow. Is there a way to improve it. The issue exist both on local pc and server. Not sure where to start is it the Apache problem or the glide library?
![glide](https://user-images.githubusercontent.com/12866020/148044487-4a019f28-aae1-4c3f-9c31-9ffd01aeb1f4.jpg)

**Comment by Awilum** [comment]
Hello @janekbar5
After a few years of Glide usage, I stop using it
1 - https://github.com/thephpleague/glide/issues/330
2 - https://github.com/flextype/flextype/issues/574

**Comment by janekbar5** [comment]
thanks @Awilum also thinking going back to intervention perhaps

**Comment by ADmad** [comment]
Duplicate of #287
