### ISSUE TITLE
UrlBuilder support protocol-relative

### ISSUE THREAD

**Issue by anhskohbo** [thephpleague/glide#34]
If UrlBuilder support like this:
```php
$builder = UrlBuilderFactory::create('//image.domain.com');
```
would be nice :)

**Comment by reinink** [comment]
Right...the issue right now is that the extra slash is stripped out, right?

**Comment by anhskohbo** [comment]
yep!  `//image.domain.com/img.jpg` > `/image.domain.com/img.jpg`

**Comment by reinink** [comment]
Closing this ticket. I've fix this issue, and it has been merged into the master branch and will be tagged shortly when I release `v1.0`! Hopefully not long now.
