### ISSUE TITLE
Mockery error in League\Glide\ServerTest::testMakeImageFromSource

### ISSUE THREAD

**Issue by Synchro** [thephpleague/glide#358]
I'm running the glide test suite on PHP 8.1, and it all passes except for one thing:

```
1) League\Glide\ServerTest::testMakeImageFromSource
Mockery\Exception\NoMatchingExpectationException: No matching handler found for
Mockery_8_League_Glide_Api_ApiInterface::run('/private/var/folders/wn/fk5c4mz15z56v0ztf3g4c5dh0000gn/T/GlideUCfJUM', []). 
Either the method was unexpected or its arguments matched no expected argument list for this method
```

I don't understand this error, but I figure it shouldn't be failing!

**Comment by ADmad** [comment]
There are no errors when running the test suite on PHP 8.1 on Github Actions as seen [here](https://github.com/thephpleague/glide/actions/runs/3638691530/jobs/6141190025), nor do I have get any errors locally. 

So you'll have to figure out the problem yourself.
