### ISSUE TITLE
HEIC format support

### ISSUE THREAD

**Issue by cotiga** [thephpleague/glide#377]
Currently Glide requires Intervention/image 2.7
According to my research it would be necessary to Intervention/image 3 to handle the HEIC format
Is there a plan for Glide to support Intervention/image 3?

**Comment by ADmad** [comment]
Updating to `intervention/image` v3 will require a reasonable amount of changes and currently I can't devote any time towards that (sadly I am the only maintainer right now).

**Comment by ADmad** [comment]
Done in #382. You can try out the `3.x` branch and provide feedback.
