### ISSUE TITLE
Concurrent requests for an image that has not yet been cached

### ISSUE THREAD

**Issue by kevin-thackorie** [thephpleague/glide#38]
During concurrent requests (even with concurrency as low as 2), if the image has not yet been cached, a FileExistsException gets thrown:

>PHP Fatal error:  Uncaught exception 'League\\Flysystem\\FileExistsException' with message 'File already exists at path: 0fb98a01effea237c106d20fc335afb1'

I discovered this race condition issue while benchmarking performance on a VM running locally using [ApacheBench v2.3:](http://httpd.apache.org/docs/2.2/programs/ab.html)

>ab -n 300 -c 2 http://images.domain.tld/item/test.jpg

**Comment by reinink** [comment]
Interesting. I guess this is possible given that there is a delay between the image being generated and actually being saved to disk.

We definitely need a second check right before saving a new image to disk. Unfortunately, that doesn't help prevent generating an image twice. Probably the simplest solution would be to simply write a blank file immediately, even before the image has been generated. Then, when the manipulated image has been generated, replace the temporary image with it.

Thanks for bringing this to my attention, I'll have to patch this in an upcoming release.

**Comment by tmirks** [comment]
@reinink You could have the same issue writing a blank file (i.e. multiple requests trying to write the blank file at the same time). Is there any reason the second request wouldn't just do a silent overwrite (or silent fail)?

There would be a very small performance hit because you're generating it twice, but this would be pretty rare.

**Comment by reinink** [comment]
Yeah, maybe that's even a better and simpler option, especially given how infrequently this problem will occur. Good thinking Tim!

**Comment by kevin-thackorie** [comment]
+1 for failing silently. Silent overwrite would require changes to Flysystem (the assertAbsent logic in Filesystem.php).

**Comment by reinink** [comment]
Fixed and [tagged](https://github.com/thephpleague/glide/releases/tag/0.3.2)!

**Comment by tmirks** [comment]
Thanks @reinink, that was quick! :+1:
