### ISSUE TITLE
Differences in the use of fit=fill and fit=fill-max

### ISSUE THREAD

**Issue by Art4** [thephpleague/glide#385]
I've noted differences between Glide v2 and v3 using the `fit=fill` and `fit=fill-max` manipulators. I'm using my own diff tool: https://gist.github.com/Art4/95c476dc8aa42e8668db792c03e103e1

![grafik](https://github.com/thephpleague/glide/assets/2162994/d69a4d62-6acd-40cf-8b07-fa3cb1314c25)
![grafik](https://github.com/thephpleague/glide/assets/2162994/9b4c39c5-3588-4782-a548-125f11dfcd6e)

**Result from Glide v2**

![Unbenannt](https://github.com/thephpleague/glide/assets/2162994/c22810b1-0d08-4fcf-89f2-01ea4eb6446e)

**Result from Glide v3**

![Unbenannt](https://github.com/thephpleague/glide/assets/2162994/d663426f-cb96-43c0-a8db-bf9dc2ae6d0b)

With Glide v3 the image is 1 pixel wider, or the white border on the left-hand side is 1 pixel thinner.

I'm not sure where the problem lies and whether this difference is even worth fixing.

**Comment by Art4** [comment]
I've checked all examples from the v2 docs and can confirm that everything (except this issue) works as before.

There are also cases like `filt=sepia`, `bri=-25` or `bri=50`, where I get deprecated warnings in intervention/image v2 and PHP 8.3, like this:

```
Deprecated: Implicit conversion from float 127.49999999999999 to int loses precision in vendor/intervention/image/src/Intervention/Image/Gd/Commands/BrightnessCommand.php on line 19
```

But this problems are fixed with v3.

**Comment by ADmad** [comment]
Thanks for testing out the various manipulations.

I did improve the typing in Glide v3 too. I thought of enabling strict typing too (intervention v3 has done it) but given that we have a lot of numeric argument string vs int isn't strictly followed so left that for now.
