### ISSUE TITLE
not working with laravel 11

### ISSUE THREAD

**Issue by narendraraghuwanshi** [thephpleague/glide#392]
Problem 1
    - league/glide-symfony 1.0.0 requires symfony/http-foundation ^2.3 -> found symfony/http-foundation[v2.3.0, ..., v2.8.52] but these were not loaded, likely because it conflicts with another require.
    - league/glide-symfony[1.0.1, ..., 1.0.2] require symfony/http-foundation ^2.3|^3.0 -> found symfony/http-foundation[v2.3.0, ..., v2.8.52, v3.0.0, ..., v3.4.47] but these were not loaded, likely because it conflicts with another require.
    - league/glide-symfony 1.0.3 requires symfony/http-foundation ^2.3|^3.0|^4.0 -> found symfony/http-foundation[v2.3.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.49] but these were not loaded, likely because it conflicts with another require.
    - league/glide-symfony 1.1.0 requires symfony/http-foundation ^2.3|^3.0|^4.0|^5.0|^6.0 -> found symfony/http-foundation[v2.3.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.49, v5.0.0, ..., v5.4.35, v6.0.0, ..., v6.4.4] but these were not loaded, likely because it conflicts with another require.
    - league/glide-symfony[1.0.4, ..., 1.1.1] require symfony/http-foundation ^2.3|^3.0|^4.0|^5.0 -> found symfony/http-foundation[v2.3.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.49, v5.0.0, ..., v5.4.35] but these were not loaded, likely because it conflicts with another require.
    - league/glide-laravel 1.0.0 requires league/glide-symfony ^1.0 -> satisfiable by league/glide-symfony[1.0.0, ..., 1.1.1].
    - Root composer.json requires league/glide-laravel * -> satisfiable by league/glide-laravel[1.0.0].

**Comment by Art4** [comment]
Wrong repo, please see https://github.com/thephpleague/glide-laravel
