### ISSUE TITLE
Support intervention/image:^3

### ISSUE THREAD

**Issue by heddn** [thephpleague/glide#393]
The first version of [3.x](https://github.com/Intervention/image/releases/tag/3.0.0) was released on Dec 8, 2023. We would work on a plan to support the newer version.

**Comment by ADmad** [comment]
https://github.com/thephpleague/glide/releases/tag/3.0.0-beta1

**Comment by heddn** [comment]
https://github.com/thephpleague/glide/blob/master/composer.json#L30 and composer says that isn't the case. we still need `^2.7`. 😕

**Comment by Art4** [comment]
> https://github.com/thephpleague/glide/blob/master/composer.json#L30 and composer says that isn't the case. we still need `^2.7`. 😕

See the 3.x branch: https://github.com/thephpleague/glide/blob/3.x/composer.json

For installation please use the 3.0.0-beta1 release: `composer require league/glide:3.0.0-beta1`

**Comment by heddn** [comment]
OK, I think I need to head over to https://github.com/thephpleague/glide-symfony then, because it doesn't support the 3.x branch.

```
  Problem 1
    - league/glide-symfony[2.0.0, ..., 2.0.1] require league/glide ^2.0 -> found league/glide[2.0.0, ..., 2.3.0] but it conflicts with your root composer.json require (^3.0@beta).
    - Root composer.json requires league/glide-symfony ^2.0 -> satisfiable by league/glide-symfony[2.0.0, 2.0.1].
```

And https://github.com/thephpleague/glide-laravel/ is even worse/outdated.
