### ISSUE TITLE
3.x release date

### ISSUE THREAD

**Issue by nlemoine** [thephpleague/glide#395]
Hi!

I see that you're actively developing on the 3.x branch, do you have an approximative release date for 3?

Thanks!

**Comment by ADmad** [comment]
There's no tentative date for a stable release yet. There's an open PR #394 which I want to get merged but haven't had the time to review.

In the meantime you can use the [3.0.0-beta1](https://github.com/thephpleague/glide/releases/tag/3.0.0-beta1) release and report back if you have any issues.

**Comment by nlemoine** [comment]
Thanks for your feedback !
