### ISSUE TITLE
Progress on v3.0

### ISSUE THREAD

**Issue by C2H6-383** [thephpleague/glide#407]
Hi everyone,

just wanted to ask about the development progress of version 3.0. The last beta was released about 2 months ago and I was unable to find any open issues due for v3 (the milestone is 100% completed too). 

Is there a planned release date for v3 or are there more issues to be tackled before the release?

Thanks for this great package.

**Comment by ADmad** [comment]
[3.0.0-RC1](https://github.com/thephpleague/glide/releases/tag/3.0.0-RC1) has been released
