### ISSUE TITLE
New crop option: crop=fill

### ISSUE THREAD

**Issue by darrenpowers** [thephpleague/glide#43]
Cloudinary has a very useful crop type option called fill. 
This allow the image to be cropped to a given size, dynamically detecting the area of the image that will fit within the requested size and using cropping the image to contain that part of it.

This is especially useful in images that might not contain a face but do contain a point of interest that might otherwise be partly cropped out.

See:  http://cloudinary.com/documentation/image_transformations#crop_modes
>"Create an image with the exact given width and height while retaining original proportions. Use only part of the image that fills the given dimensions. Only part of the original image might be visible if the required proportions are different than the original ones.
>
>For example, filling a 100x150 rectangle based on the sample image:
>
>http://res.cloudinary.com/demo/image/upload/w_100,h_150,c_fill/sample.jpg"

**Comment by reinink** [comment]
Hi @darrenpowers, maybe I'm missing, but I'm pretty sure that's what Glide's `fit=crop` setting does. For example:

[![Crop](https://glide.herokuapp.com/kayaks.jpg?w=400&h=300&fit=crop)](https://glide.herokuapp.com/kayaks.jpg?w=400&h=300&fit=crop)

Or am I missing something?

**Comment by reinink** [comment]
I should add to this, you can adjust the crop mode, which allows you to specify where the image is cropped when the fit parameter is set to crop. For example:

[![Crop](https://glide.herokuapp.com/kayaks.jpg?w=400&h=300&fit=crop&crop=left)](https://glide.herokuapp.com/kayaks.jpg?w=400&h=300&fit=crop&crop=left)

Full details [here](http://glide.thephpleague.com/api/size/#crop-mode-crop).

**Comment by darrenpowers** [comment]
Sorry, my mistake, I didn't realise fit=crop was an intelligent crop.
This looks like it does what I was thingking.
Great work, thanks.
