### ISSUE TITLE
How to automatically orientate images?

### ISSUE THREAD

**Issue by renege** [thephpleague/glide#48]
Hi, how to automatically orientate images?

```
public function foobar(\League\Glide\Server $server, Request $request)
	{
		$server->outputImage($request);
	}
```

**Comment by reinink** [comment]
Hello @renege, Glide is supposed to auto-orientate by default, but as you can see in issue #47 there is a bug that prevents this. I'm hoping to work on a fix for this week. I'm going to close this ticket, since we've already got it covered over there.
