### ISSUE TITLE
NotFoundException returned before image is outputted

### ISSUE THREAD

**Issue by Jaspur** [thephpleague/glide#50]
When calling ```$server->outputImage($request);``` the first time, it returns an NotFoundException:

![schermafdruk 2015-03-19 09 35 21](https://cloud.githubusercontent.com/assets/4254854/6726776/9323c25c-ce1b-11e4-9e11-0acd4ec82030.png)

**Comment by reinink** [comment]
The first time it runs is when the image is actually generated (obviously), so it must be sort of working, and then the second time it works properly because the cache is there.

Are you using GD or Imagick? Are you on Windows or Linux/OSX?

**Comment by Jaspur** [comment]
I tried the code of #47, and that also solved this problem.
I'm using Imagick, Linux.

**Comment by Jaspur** [comment]
Same at v2.2.1.

**Comment by reinink** [comment]
What do you mean, version `2.2.1` of what? Glide is currently at `0.3.5`, so that can't be right. Also, do you mind posting some more code, to show me how your wiring this together? Thanks!

**Comment by reinink** [comment]
I'm going to close this because I haven't heard back. However, feel free to share some more details and I'd be happy to help figure this out for you!

**Comment by Jaspur** [comment]
Sorry, didn't see your last comment. I don't know what I ment with v2.2.1 then :p

```
<?php namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider {

	/**
	 * Bootstrap any application services.
	 *
	 * @return void
	 */
	public function boot()
	{
		//
	}

	/**
	 * Register any application services.
	 *
	 * This service provider is a great spot to register your various container
	 * bindings with the application. As you can see, we are registering our
	 * "Registrar" implementation here. You can add your own bindings too!
	 *
	 * @return void
	 */
	public function register()
	{
		$this->app->bind(
			'Illuminate\Contracts\Auth\Registrar',
			'App\Services\Registrar'
		);

		$this->app->singleton('League\Glide\Server', function($app) {
			$filesystem = $app->make('Illuminate\Contracts\Filesystem\Filesystem');

			return \League\Glide\ServerFactory::create([
				'source' => $filesystem->getDriver(),
				'cache' => $filesystem->getDriver(),
				'source_path_prefix' => 'images',
				'cache_path_prefix' => 'images/.cache',
				'base_url' => 'img',
				//'max_image_size' => 1024,
			]);
		});
	}

}

#routes.php
get('img/{path}', ['uses' => 'GlideController@show'])->where('path', '.+');

<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;

class GlideController extends Controller {
	
	public function show(\League\Glide\Server $server, Request $request)
	{
		$server->outputImage($request);
	}

}
```

That's the code. When image url is called for the first time, it gives the error from the first comment. Error message comes from Bugsnag.

**Comment by reinink** [comment]
That all looks good to me, which makes me think the issue might be elsewhere. It seems to me like you have two requests that happen at the same time, and one is wrong, and the other is correct. The one that's wrong is failing, and causing the error.

One quick question, is the filename `77914-stackedclouds-1jpg` correct? Or should it have a period in there, like this: `77914-stackedclouds-1.jpg`.

When you call it the first and second time, is it called from the exact same spot? As in, the same template? Or do you potentially call it the first time using JavaScript, and the second time from a PHP template?

**Comment by Jaspur** [comment]
Name is correct. And indeed, first time is a JS call, second time a PHP call. That's the problem?

**Comment by reinink** [comment]
No, that alone shouldn't be a problem. The error is the `NotFoundException`, which makes me think that the JavaScript URL is somehow wrong. Then when you reload the page (I presume?) it corrects itself with the right URL.
