### ISSUE TITLE
"Signature is missing"?

### ISSUE THREAD

**Issue by rombat** [thephpleague/glide#52]
Hi,
I have this error
``` exception 'League\Glide\Http\SignatureException' with message 'Signature is missing.' in /home/devmg/public_html/laravel/vendor/league/glide/src/Http/Signature.php:43 ```
and I can't figure out what is the problem. Can somebody help me?

**Comment by reinink** [comment]
Hey @rombat, sorry for the long delay on this. If you are still interested, I can try help you out here. I'll just need a bunch more information about your setup. Please include the code where you setup your Http  signatures, as well as your route where you validate it. Thanks!

**Comment by reinink** [comment]
Closing since I haven't heard anything back
