### ISSUE TITLE
Impossible to overwrite ResponseFactory::create

### ISSUE THREAD

**Issue by lsv** [thephpleague/glide#55]
As ResponseFactory only streams the response (StreamedResponse), where I want is just to get a Response back, because im getting the images as base64 encoded instead of downloading them.

So I think ResponseFactory in Server should be overwriteable.

Maybe with

````
public function __construct(FilesystemInterface $source, FilesystemInterface $cache, ApiInterface $api, ResponseFactory $reponse = null)
{
    $this->setSource($source);
    $this->setCache($cache);
    $this->setApi($api);
    $this->setResponseFactory($response);
}
````

And now overwrite all the calls with

````
ResponseFactory::create(...)
````

to

````
$this->getResponseFactory()::create(...)
````

**Comment by reinink** [comment]
I'm actually planning on making the response factory an injectable dependency, just so folks can modify the response object as needed. So good call there!

However, in your particular situation, you shouldn't even be using responses, because you don't actually want to send a response with Glide, but rather you just want the manipulated image encoded base64. This can be done pretty easily, it just takes a little bit of extra code. Here's how:

```php
// Setup your Glide server
$glide = ServerFactory::create([
    // your configuration
]);

// Generate the manipulated image
$glide->makeImage($request);

// Get the path of maipulated image in the cache
$path = $glide->getCachePath($request);

// Get the content of the maipulated image from the cache
$source = $cache->read($path);

// Base64 encode your image (and even auto set the mime type)
$base64 = 'data:'.$cache->getMimetype($path).';base64,'.base64_encode($source);

// Use the Base64 encoded image in your app
echo '<img src="'.$base64.'">';
```

**Comment by reinink** [comment]
The next iteration of Glide will have a `ResponseFactory` interface, which you can define within the `ServerFactory` options. Something like this:

```php
$glide = ServerFactory::create([
    'source' => $filesystem,
    'cache' => $cache,
    'response' => new MyResponseFactory(),
]);
```

If no `response` is set, it will just default to the `StreamedResponseFactory` class.

**Comment by reinink** [comment]
Closing this ticket. Responses have been totally reworked for the next version, and this functionality has been merged into the master branch and will be tagged shortly when I release `v1.0`! Hopefully not long now.

Also, see the work-in-progress docs for this feature [here](http://glide.thephpleague.com/1.0/config/responses/).
