### ISSUE TITLE
Watermarking support

### ISSUE THREAD

**Issue by jackmcdade** [thephpleague/glide#63]
We'd love to see (and be helpful in adding, if possible) Intervention\Image's watermark support come to Glide.

I would imagine the HTTP API could be a bit of an awkward place to try and manage that, so I wonder if it's something you could configure on the `ServerFactory` config or something, and then either allow a `watermark=true` parameter or force it to always be on for those server instance requests.

Perhaps something like this?

```
ServerFactory::create([
    'source'    => config('glide.source'),
    'cache'     => config('glide.cache'),
    'watermark' => config('glide.watermark') // would point to /img/watermark.png or similar
]);
```

**Comment by reinink** [comment]
Yes, this definitely needs to be added. I do see some challenges with it being configured at the Server level, even though I agree that's maybe the place to do it. The challenge is when images are scaled to different sizes. A watermark may look great at 500x500, but may be totally messed up at 100x100.

I'm going to do some experimenting with this. Once again, I want to reference the very well thought out [Imgix API](http://www.imgix.com/docs/reference/watermark). They do offer this via their HTTP API. Here are the parameters:

- `mark` - watermark image URL
- `markalign` - watermark aligment mode
- `markalpha` - watermark alpha
- `markfit` - watermark image fit mode
- `markh` - watermark image height
- `markpad` - watermark padding
- `markscale` - watermark scale
- `markw` - watermark image width
- `markx` - mark x
- `marky` - mark y

That's obviously a very complex, very powerful API. I'm not sure how much of this Glide can offer, as some of it depends on what Intervention offers. But it's a good reference nonetheless.

**Comment by jasonvarga** [comment]
One solution I thought of (briefly, and without really understanding the inner workings of Glide, so it may be a horrible idea) is to allow the factory to accept a few watermark configurations, and allow the HTTP API to dictate which one to use.

Something like:

```
ServerFactory::create([
    'source' => 'path/to/source/folder',
    'cache' => 'path/to/cache/folder',
    'watermarks' => [
      'logo' => ['w' => 10, 'h' => 10, 'p' => 'bottom-right'],
      'overlay' => ['w' => '100%', 'h' => '100%, 'fit' => 'crop']
    ]
]);
```

Then choose the watermark in the URL. `/img/myimg.jpg?w=100&h=100&watermark=logo`

**Comment by reinink** [comment]
That's not a bad idea either. I will be honest with you though, a big goal for me with Glide has been to make all operations available via the HTTP API. This makes Glide very simple to use, as all the image manipulations are done in the same place. I can see the benefit of having some "preassigned" manipulations. It's just a question of whether this should be baked into Glide, or added at the application level.

**Comment by reinink** [comment]
Also, while I think of it, I'd recommend that Statamic offer some type of template helper to output image URLs. This can be especially helpful for automatically [securing images](http://glide.thephpleague.com/config/secure-images/) with HTTP signatures.

```twig
{{ image file="cat.jpg" w="500" }}
```

And that would output something like this:

```php
<img src="http://example.com/img/cat.jpg?w=500&token=af3dc18fc6bfb2afb521e587c348b904">
```

You could give users the option to enable/disable signatures (maybe depending on the environment), but I'd strongly recommend using HTTP signatures. I know for myself I have them disabled when doing local development, but I enable them in production.

**Comment by jasonvarga** [comment]
I agree that everything should be done with the HTTP API, since that's really the benefit to Glide.

I suppose we could be doing the watermarking part on the app level. Glide can perform the manipulations and cache an image without displaying it, right? Just use `makeImage()`? We'd need to get what Glide creates, manipulate it further ourselves, _then_ render it.

...and yup, we already have plans for that tag :)

**Comment by reinink** [comment]
Okay sweet! If you have plans for a tag like that, then maybe that's how you could handle the preassigned data. For example, in your application config:

```yaml
_default_image_manipulations:
    - mark_src: logo.png
    - mark_w: 50
    - mark_h: 50
    - mark_pos: bottom-right
```

Then, when you generate the image URL using the new template tag, it automatically adds the default image manipulations to it. To output an image with the defaults you just do this:

```twig
{{ image file="cat.jpg" w="500" }}
```

But in reality, it's actually doing this:

```twig
{{ image file="cat.jpg" w="500" mark_src="logo.png" mark_w="50" mark_h="50" mark_pos="bottom-right" }}
```

The point being, there are lots of ways to skin this cat. This approach would mean that Statamic can still just interact with the HTTP API (via this new template tag), which is nice and easy. You could even get fancy with it by allowing different default image manipulations in the site configuration. For example:

```yaml
_default_image_manipulations:
    - watermark:
        - mark_src: logo.png
        - mark_w: 50
        - mark_h: 50
        - mark_pos: bottom-right
    - black_and_white:
        - filt: greyscale
```

```twig
{{ image file="cat.jpg" implements="watermark" }}
```

And you could even allow for overriding at this point, by adding additional parameters after whatever default it implements:

```twig
{{ image file="cat.jpg" implements="watermark" w="500" }}
```

You get the idea.

**Comment by reinink** [comment]
Some design ideas and notes:

Define the available watermarks using a `Flysystem` instance in the same way the `source` and `cache` are defined:

```php
// With strings:
$server = League\Glide\ServerFactory::create([
    'source' => 'path/to/source/folder',
    'cache' => 'path/to/cache/folder',
    'watermarks' => 'path/to/watermarks/folder',
]);

// With objects
$server = League\Glide\ServerFactory::create([
    'source' => new Filesystem(new Local('path/to/source/folder')),
    'cache' => new Filesystem(new Local('path/to/cache/folder')),
    'watermarks' => new Filesystem(new Local('path/to/watermarks/folder')),
]);
```

Then the watermark URL can simply be a filename that references an image in the watermarks folder/filesystem. Like:

```php
/img/kayaks.jpg?mark=logo.png
```

Also, I'm thinking we'll use the following API for the initial release of this:

- `mark` - the filename the watermark
- `markw` - the width of the watermark *(optional)*
- `markh` - the height of the watermark *(optional)*
- `markpos` - the position of the watermark *(optional, `top-left ` default)*
- `markx` - the horizontal offset of the watermark *(optional)*
- `marky` - the vertical offset of the watermark *(optional)*

**Comment by reinink** [comment]
Making some progress on this! I've got this working locally:

```php
img/kayaks.jpg?w=1000&mark=billabong.png&markw=200&markx=25&marky=25&markpos=top-right
```

![image](https://cloud.githubusercontent.com/assets/882133/8173128/30a14e76-1397-11e5-86ba-de5bc59797b0.png)

**Comment by jackmcdade** [comment]
Woo!

**Comment by reinink** [comment]
I'm thinking I'll add two more options: `markscale` and `markpad`. Here's the full outline of watermark api:

- **mark**
    - The filename the watermark
    - Example: `&mark=logo.png`
    - Must be found in the predefined `watermarks` filesystem
    - Can include a subfolder in the url, example: `&mark=/logos/logo.png`
- **markw**
    - The width of the watermark in pixels
    - Uses the contain fit method
    - Can be used with `markh`
- **markh**
    - The height of the watermark in pixels
    - Uses the contain fit method
    - Can be used with `markx`
- **markpos**
    - The position of the watermark
    - Available options: `top-left`, `top`, `top-right`, `left`, `center`, `right`, `bottom-left`, `bottom`, `bottom-right`
    - Defaults to `bottom-right`
- **markx**
    - The horizontal offset of the watermark in pixels
- **marky**
    - The vertical offset of the watermark in pixels
- **markscale**
    - Scales watermark to a percentage of the source image's width
    - When enabled the `markw` and `markh` are ignored
    - Helpful if set as a default image manipulation, as the watermark will scale to different image sizes
- **markpad**
    - Sets the x and y offset of the watermark to a percentage of the source image's width
    - When enabled the `markx` and `marky` are ignored
    - Helpful if set as a default image manipulation, as the watermark will scale to different image sizes

I'd like to also offer `markalpha`, but I've tested this an it's brutally slow. Like 10+ seconds for a basic watermark. Even Intervention [warns](http://image.intervention.io/api/opacity) about this. I think I'm going to leave this feature out for now.

**Comment by jackmcdade** [comment]
Double thumbs up! :+1: :+1:

**Comment by reinink** [comment]
Gents, if you have a second, I'd love your feedback on this proposed image API change for the next release: #75. I've also updated the watermark API above to reflect these changes, most notably I've added the new `markfit` option.

I hate making breaking changes like this, but this is why Glide hasn't hit the 1.0 release yet. I really want to be able to flush it out before really locking it it long term. I think with these changes we're getting very close to that.

**Comment by reinink** [comment]
I've removed the `markscale` option in favour of a pretty awesome new method of setting watermark dimensions via the `markw`, `markh`, `markx`, `marky` and `markpad` options. It works like this:

- The value is pixels if it's a number (ie. markw=300)
- The value is a percentage of the main image's width if followed with a `w` (ie. markw=30w)
- The value is a percentage of the main image's height if followed with a `h` (ie. markw=30h)

This gives tons of flexibility to use either fixed dimensions, or scaled dimensions based on the parent image. I kept the `markpad` option as a convience, instead of having to write out both `markx` and `marky`.

**Comment by reinink** [comment]
Closing this ticket. The watermarks functionality is complete and has been merged into the master branch and will be tagged shortly when I release `v1.0`! Hopefully not long now.

Also, see the docs for this feature [here](http://glide.thephpleague.com/1.0/api/watermarks/).
