### ISSUE TITLE
output image in pdf file ? 

### ISSUE THREAD

**Issue by mshanak** [thephpleague/glide#65]
is there a way to output (convert) an image in PDF File using this library (  it's supported in Imagick  ) ?

**Comment by reinink** [comment]
Hello! Thanks for interest in Glide. Unfortunately this isn't supported by Glide, as it falls pretty far outside of the scope of this project. I'd recommend using Imagick, or some other tool more geared to PDF generation. Sorry I cannot be more helpful.

**Comment by mshanak** [comment]
thank you ,
i am using Imagick now and it work's :+1:
