### ISSUE TITLE
Question on RecyclerView Integration

### ISSUE THREAD

**Issue by eicm** [thephpleague/glide#67]
I was taking a look on RecyclerView integrations and ListPreloader implementation. If I haven't missed anything simply changing RecyclerToListViewScrollListener.java class to get the correct firstVisible, visibleCount and itemCount should be enough to create infinite scrolling for any other type of LayoutManager. Would you please correct me if I'm wrong

**Comment by reinink** [comment]
Umm, huh? :open_mouth:

Are you sure you've got the right project here?

**Comment by reinink** [comment]
I think you're looking for [this project](https://github.com/bumptech/glide).

**Comment by eicm** [comment]
Sorry my bad :D

**Comment by reinink** [comment]
It's quite alright. ;)
