### ISSUE TITLE
Progressive mode for jpg by default?

### ISSUE THREAD

**Issue by afraca** [thephpleague/glide#68]
In our installation, when using glide to get some png, resize it and transform to jpg, the outputted image was not configured as 'progressive'.  

(as simply detected with:
http://techslides.com/demos/progressive-test.html  )

It's hard to find information on this and where it is configured, but I found this:
http://image.intervention.io/api/interlace
> If interlace is set to boolean true the image will be encoded interlaced. If the parameter is set to false interlaced mode is turned off. Default: true

So by default true? But not with Glide? I couldn't find an overridden configuration anywhere, but maybe I overlooked, and/or maybe there's a fine reason to override default. 

Can there be some option to use progressive, as it makes webpages load more elegant?

**Comment by reinink** [comment]
Progressive JPEGs are not enabled by default with Intervention. You must call the `$img->interlace()` method to enable this. Personally I'm not a fan of progressive, which is why Glide doesn't have this feature yet. However, I do see the value in adding this feature, so I'll add this to the upcoming release. It will most likely be enabled like this:

```
/img/kayaks.jpg?fm=pjpg
```

This is in keeping with [Imgix](http://www.imgix.com/docs/reference/format#param-fm).

Stay tuned for an update.

**Comment by afraca** [comment]
Hi, anything in the works for this? Otherwise I might go ahead and fork and see if I can do this myself.

**Comment by reinink** [comment]
This work is already done, and is going to be available in version 1.0, which will be released very soon. You can see the addition of `pjpg` [here](http://glide.thephpleague.com/1.0/api/encode/#format-fm), and the new default parameter features [here](http://glide.thephpleague.com/1.0/config/defaults-and-presets/).

**Comment by reinink** [comment]
Closing this ticket. I've added the `fm= pjpg ` functionality, and it has been merged into the master branch and will be tagged shortly when I release `v1.0`! Hopefully not long now.

Also, see the docs for this feature [here](http://glide.thephpleague.com/1.0/api/encode/). Further, if you want to use progressive JPEGs by default, you can use the new [defaults configuration option](http://glide.thephpleague.com/1.0/config/defaults-and-presets/) to do this.
