### ISSUE TITLE
Make Glide PSR-7 compatible

### ISSUE THREAD

**Issue by reinink** [thephpleague/glide#69]

**Comment by reinink** [comment]
@philipobenito Hey, I was wondering if I could ask you opinion on this. Glide currently depends on HttpFoundation (`~2.3`). I've working on a big update to Glide that will have many breaking changes. Do you think now would be the time to switch out this dependency for `psr/http-message`?

I understand Symfony already has a bridge available to switch from older versions. What do you think?

**Comment by philipobenito** [comment]
For a major release I'd strongly consider it. There are several very good implementations without the need for the bridge, Slim has one, and and Zend\Diactoros looks very good (formally phly/http).

**Comment by reinink** [comment]
Okay, so, here's the challenge. Glide interfaces with the `Request` object a lot, but that's the simpler piece I see. Glide also uses HttpFoundation's response objects to return image responses. So, I sort of still need that dependency either way.

Also, does the newest version of HttpFoundation even follow PSR-7? Seems like they don't, since Symfony has offered a bridge. Or, is the bridge just for older versions of HttpFoundation?

**Comment by harikt** [comment]
Hey @reinink ,

According to the information I got symfony 3 will not be psr-7 for http foundation for it will break the api. (May be symfony 4, ie why the bridge is there) . 

But I am not sure why you need http foundation for when you could rely on the zend/diactoros and psr-7 response itself if that's the case.

And the psr-7 response can be converted to symfony http foundation via bridge in case if needed and viceversa I believe.

**Comment by GrahamCampbell** [comment]
> (May be symfony 4, ie why the bridge is there) .

I don't think symfony is planning to change it's http implementations.

**Comment by reinink** [comment]
Okay, thanks for the clarification @harikt and @GrahamCampbell.

So, I guess I could replace HttpFoundation with `zend/diactoros` to actually generate my response/request objects.

**Comment by philipobenito** [comment]
@reinink :+1: I'd go full PSR-7 if you're going to support it, no point in the bridge unless you really need to use it, and I don't think you need to considering it'll be a major version change anyway. Just allow for a swap of implementations.

**Comment by reinink** [comment]
So, I had a long chat with the excellent @simensen yesterday about this, and I think I've made some decisions around the next release.

I really wanted to remove the `symfony/http-foundation` dependency and just use PSR-7. However, the key thing Glide uses HttpFoundation for is creating the actual Response objects, as seen [here](https://github.com/thephpleague/glide/blob/develop/src/Responses/StreamedResponseFactory.php). So, if we made the switch to using PSR-7 interfaces, the user would have to provide a base PSR-7 Response object of their choice, otherwise Glide wouldn't be able to make the response. This means including another package in addition to Glide, or hopefully using one provided by their framework.

I now understand, thanks to Beau, that this will be a more common approach to this sort of problem in the future. However, I'm nervous to do in the next release. I think some people will be very confused. "What, I have to provide Glide with a Response object?!?!" And so, I've decided to keep HttpFoundation for now. However, I'm making some cool changes that will accomplish pretty much the same thing.

First, I'm removing the need for the Request object entirely. Glide will not longer use Request objects internally, or allow them to be used instead of the `(string) $path` and `(array) $params` mix. This is better described with code:

```php
// Currently these both work:
$glide->outputImage($request);
$glide->outputImage($request->getPathInfo(), $request->all());

// Moving forward, only this will works:
$glide->outputImage($request->getPathInfo(), $request->all());
```

It means a smidge more code on the controller, but it frees Glide from that Request object dependency. It also means I don't have to have all these weird mixed parameter methods. It will simply require the path as a string, and an array of manipulation parameters.

Further, you won't be forced to use HttpFoundation for your responses. I've created a `ResponseFactoryInterface` which will allow you to use any response object you'd like. Looks like this:

```php
interface ResponseFactoryInterface
{
    public function create(FilesystemInterface $cache, $cachedPath);
    public function send();
}
```

Glide will ship with two response factories: `SymfonyResponseFactory` and `PsrResponseFactory`. By default it will use the Symfony (HttpFoundation) factory, because it will just work out of the box. However, developers can choose to use the Psr factory instead. Just understand that you'll need to pass in a base Response object of your choice for this to work.

I feel this approach strikes a nice balance of ease of use for beginners (it just works), while also offering PSR-7 compatibility for those who understand it. And if the landscape has changed a little between now and the next major release of Glide, maybe we can look at dropping HttpFoundation entirely then.

Thoughts?

**Comment by simensen** [comment]
If you can, I would consider dropping symfony/http-foundation as a require and move it to require-dev. This way, people can continue to use it in a Symfony project as-is (since they'll already have the dependency as it is baked into their application). You may have already been considering doing this so if so this serves as a :+1: from me on that topic. :)

The only downside to that is you might end up with the possibility of a drifting http-foundation compatibility as you won't (as far as I know) be able to suggest a dependency constraint against something you haven't actually required. I'll ask @seldaek on that to see if there is a way to do that.

---

What does `send` do? `create()` makes sense, but `send()` alone w/ no args on a factory I'm not sure of?

**Comment by reinink** [comment]
> If you can, I would consider dropping symfony/http-foundation as a require and move it to require-dev. 

Interesting idea, let me think about that one.

> What does `send` do? `create()` makes sense, but `send()` alone w/ no args on a factory I'm not sure of?

Oops, good point, the send method would also require an instance of `$cache` and `$cachedPath` to work, so I've updated the above interface accordingly.

Right now Glide has an `outputImage()` method, that basically gets a response and sends it right away. However, depending on what response object you're using, this functionality may be different. So, if the response factory had a `send()` method, the factory could just create the object, and send it right away. And then Glide would just call that send method in those situations. Something like:

```php
class MyResponseFactory implemnts ResponseFactoryInterface
{
    public function create(FilesystemInterface $cache, $cachedPath)
    {
        // create response...
        return $repsonse;
    }

    public function send(FilesystemInterface $cache, $cachedPath)
    {
        $response = $this->create($cache, $cachedPath);
        $response->send();
    }
}
```

**Comment by reinink** [comment]
Okay, so, upon future discussion with @simensen, here is what I'm going to do. By default Glide will come with a `PsrResponseFactory` only. The `SymfonyResponseFactory` factory will not be included by default. It will be available as a bridge package called `league/glide-symfony-bridge`. And I'll most likely make the installation require both packages, at least for the time being, like so:

```bash
composer require league/glide league/glide-symfony-bridge
```

Then, when you are configuring your server, you'll have to pass in your response factory, like so:

```php
$server = League\Glide\ServerFactory::create([
    'source' => 'path/to/source/folder',
    'cache' => 'path/to/cache/folder',

    // use PSR-7
    'response' => new PsrResponseFactory(new Diactoros\Response())

    // or HttpFoundation
    'response' => new SymfonyResponseFactory()
]);
```

However, if you do not provide a response factory, Glide will automatically check for the existence of `SymfonyResponseFactory`. If it exists, it will just use it. Clearly this depends on the user actually having installed `league/glide-symfony-bridge`.

At this point Glide is 99.9% free of HttpFoundation, while still fully supporting it via a bridge, and in good shape to support PSR-7 moving forward.

**Comment by jcarouth** [comment]
I think your last approach is solid. I know I said yesterday that I probably would wait, doing it this way means you get to avoid the temptation for a 2.0 to support PSR-7 coming up soon. :+1:

**Comment by reinink** [comment]
Awesome, thank you all for your help. I'm really happy with how this is coming together! Tonight I removed HttpFoundation entirely from Glide, which you can see in the [develop branch](https://github.com/thephpleague/glide/tree/develop).

I've also created the bridge package, which can be found here: [thephpleague/glide-symfony](https://github.com/thephpleague/glide-symfony)

Still need to write the `PsrResponseFactory` class though. Getting really close to an beta release!

**Comment by harikt** [comment]
@reinink Nice :) .

**Comment by reinink** [comment]
So, this was all going so well, but I think I ran into a problem.

As already noted, the plan is to require a base `Response` object when creating the `PsrResponseFactory`. However, in order to set the body (with the `withBody()` method), a `Stream` object (`StreamInterface`) must be provided. And unless I'm missing something, I don't see anyway to do this from the response object (`ResponseInterface`).

So, I have a bad feeling I'll need to do this:

```php
$server = League\Glide\ServerFactory::create([
    'response' => new PsrResponseFactory(
        new Diactoros\Response(),
        new Diactoros\Stream(),
    )
]);
```

Unless, again, I'm missing something.

**Comment by reinink** [comment]
Actually, I don't even think I can do that, because most stream implementations require the `resource` (stream) to be passed into the `Stream` at instantiation, which won't work in this situation because the stream doesn't exist yet.

**Comment by reinink** [comment]
I guess there are (at least) two ways to solve this:

**1. A callback**

I'm really not a big fan of this, because it requires even more configuration. But, this would work. When Glide has created the image, and has a PHP stream ready, it could pass it to this callback, which would in return generate the stream object and return it.

```php
$server = League\Glide\ServerFactory::create([
    'response' => new PsrResponseFactory(new Zend\Diactoros\Response(), function (resource $stream) {
        return new Zend\Diactoros\Stream($stream);
    }),
]);
```

**2. Create a Glide `StreamInterface` implementation**

I like this option even less, but I could create a Glide specific PSR-7 stream object, that is essentially a PHP stream wrapper. However, both the Slim and Zend implementations are over 300 lines of code to do this. That's a bunch of extra code, reinventing something, for really no great reason.

**Comment by simensen** [comment]
One of the big benefits to having the response injected is that you don't have to tie yourself to an implementation. However, it might be that in your case this just isn't going to work. As for configuration, you could do some things to help make this easier for the user:

```php
use Psr\Http\Message\ResponseInterface;

class PsrResponseFactory
{
    public function __construct(ResponseInterface $response, $streamFactory = null)
    {
        $this->response = $response;
        if (is_null($streamFactory)) {
            if (! $response instanceof 'Zend\Diactoros\Response') {
                throw new \InvalidArgumentException(sprintf(
                    'Cannot auto resolve stream factory for response type "%s"',
                    get_class($response)
                );
            }

            $this->streamFactory = new DiactorosStreamFactory();
        }
    }
}

class DiactorosStreamFactory
{
    public function __invoke($stream)
    {
        return new \Zend\Diactoros\Stream($stream);
    }
}
```

I believe this would let you drop the default configuration back to:

```php
$server = League\Glide\ServerFactory::create([
    'response' => new PsrResponseFactory(new Zend\Diactoros\Response()),
]);
```

... while still leaving you the flexibility to drop in other PSR-7 implementations relatively easily:

```php
$server = League\Glide\ServerFactory::create([
    'response' => new PsrResponseFactory(
        new \Acme\Psr7\Response(),
        new \Acme\Glide\Psr7StreamFactory(),
    ),
]);

// ... or ...

$server = League\Glide\ServerFactory::create([
    'response' => new PsrResponseFactory(
        new \Acme\Psr7\Response(),
        function ($stream) {
            return new \Acme\Psr7\Stream($stream);
        }
    ),
]);

// ... or ... if someone wanted to make a complete PSR-7 response factory
// for their specific vendor to make it easier on Glide users...

$server = League\Glide\ServerFactory::create([
    'response' => new AcmePsrResponseFactory(),
]);
```

---

I agree that reimplementing streams here would not be a good thing. Finding a solution that does not involve you implementing `StreamInterface` would be preferable. Although this is an interesting use case for someone splitting out the `StreamInterface` into its own package so that people can rely just on that if they need to... :) (not applicable right here, right now for the future....)

**Comment by simensen** [comment]
```php
use Psr\Http\Message\ResponseInterface;

class PsrResponseFactory
{
    public function __construct(ResponseInterface $response = null, $streamFactory = null)
    {
        if (is_null($response)) {
            if (!(class_exists('Zend\Diactoros\Response'))) {
                throw new \RuntimeException(
                    'Either a PSR-7 Response must be passed or Zend Diactoros must be installed.'
                );
            }

            $response = new \Zend\Diactoros\Response();
        }
        $this->response = $response;
        if (is_null($streamFactory)) {
            if (! $response instanceof 'Zend\Diactoros\Response') {
                throw new \RuntimeException(sprintf(
                    'Cannot auto resolve stream factory for response type "%s"',
                    get_class($response)
                );
            }

            $this->streamFactory = new DiactorosStreamFactory();
        }
    }
}

class DiactorosStreamFactory
{
    public function __invoke($stream)
    {
        return new \Zend\Diactoros\Stream($stream);
    }
}
```

...

```php
$server = League\Glide\ServerFactory::create([
    'response' => new PsrResponseFactory(),
]);
```

...

which means that 'response' could now have a default configuration of just `new PsrResponseFactory`, so for vanilla (Zend Diactoros backed) PSR-7 configuration:

```php
$server = League\Glide\ServerFactory::create();
```

**Comment by harikt** [comment]
Why not you can't call the `$response->getBody()` https://github.com/zendframework/zend-diactoros/blob/1.0.4/src/MessageTrait.php#L288 , that itself is a stream and now you can make use of `StreamInterface` methods.

**Comment by simensen** [comment]
I believer the problem is that glide has a stream and needs to get it to the response. Glide can potentially write directly into the stream as you suggest, but not sure that will break some expectations on how it is actually being used. Possible though?

**Comment by reinink** [comment]
Beau, I like your idea to provide auto-wiring like that, but I wonder if we should be more explicit with it, and just provide vendor specific shortcut factories. So, assuming we stick with the current [PsrResponseFactory](https://github.com/thephpleague/glide/blob/develop/src/Responses/PsrResponseFactory.php), we could extend it like this:

```php
namespace League\Glide\Responses;

class SlimResponseFactory extends PsrResponseFactory
{
    protected $response;
    protected $streamCallback;

    public function __construct()
    {
        $this->response = new Slim\Http\Response();
        $this->streamCallback = function ($stream) {
            return new Slim\Http\Stream($stream);
        };
    }
}
```

That way if you want an auto-wired version of the Slim Response/Stream objects, use that factory. If you want more control, use the `PsrResponseFactory` instead.

**Comment by reinink** [comment]
However, I do feel at this point, if we're providing vendor specific response factories, then we should also probably pull HttpFoundation back in as an optional factory. Now, I wouldn't want any of these vendor libraries to be Composer dependencies, the developer will be responsible for actually including those. However, I may include them as `require-dev` dependencies to test them.

I've already roughed together a bunch of these:

- `CakeResponseFactory`
- `GuzzleResponseFactory` (extends  `PsrResponseFactory`)
- `SlimResponseFactory` (extends  `PsrResponseFactory`)
- `SymfonyResponseFactory`
- `ZendResponseFactory` (extends  `PsrResponseFactory`)

**Comment by reinink** [comment]
Had another thought on this. The reason why Glide needs a response factory at all is for these two methods:

- `$server->outputImage()`: Actually sends the image response headers and content
- `$server->getImageResponse()`: Returns the image response (to be handled by app)

This is also why the `ResponseFactoryInterface` has two methods: `create` and `send`. However, I'm wondering if we should drop the `send` method altogether, and just have Glide manually do this by outputting the stream, and manually setting the necessary headers. In the current version I relied on HttpFoundation to do this, but this really isn't that complicated. Something like this:

```php
public function outputImage($path, array $params)
{
    header('Content-Type', $cache->getMimetype($path);
    header('Content-Length', $cache->getSize($path));
    header('Cache-Control', 'max-age=31536000, public');
    header('Expires', date_create('+1 years')->format('D, d M Y H:i:s').' GMT');

    $stream = $cache->readStream($path);

    rewind($stream);
    fpassthru($stream);
    fclose($stream);
}
```

So, at THIS point the only method that wouldn't work without a response factory would be the `getImageResponse()`. That's great, because Glide would be easier to configure for those who don't understand the responses, and just want to use the `outputImage()` method.

Then, to have a little more configuration around the response factory doesn't scare me as much.

**Comment by harikt** [comment]
Hey @reinink , 

May be I am not following you completely. What is the problem when you can pass the request and get a response ?

    $glide = new GlideClass($psr7_request);
    $response = $glide->process();

The user can then later do what he needs.

Thoughts ?

**Comment by reinink** [comment]
@harikt The challenge is that Glide must create a response, and depending on the framework/app, the type of response could be different. In the current version of Glide, it simply used HttpFoundation. However, I'm trying to make Glide also work with PSR-7, which makes this response generation a little more tricky.

**Comment by harikt** [comment]
Hey @reinink ,

So lets forget about httpfoundation  for a while.

Think we have PSR7 Request and Response and the rest is framework glue whether they need to use bridge to convert or what ever.

So we have psr request coming, and we give psr response . 

The user can make use of something like (https://github.com/zendframework/zend-diactoros/blob/master/src/MessageTrait.php#L79-L94)

The below code is left to user by glide.

```php
foreach ($message->getHeaders() as $name => $values) {
    echo $name . ": " . implode(", ", $values);
}
// echo the body
```

or  the framework now can convert to corresponding response. Think symfony bridge ( below code is dummy though ;) )

```php
$symfonyresponse = new Bridge($psr7response);
$symfonyresponse->send();
```

**Comment by simensen** [comment]
> The challenge is that Glide must create a response ...

I think that is the core problem. It arguably shouldn't be Glide's job to create a response. Making that part of Glide's job is why you've had to tie Glide to Symfony in the past and why you are running into issues now.

One of the iterations we talked about involved creating a "Glide image response" that users could deal with manually or just send it off to a factory.

```php
$imageResponse = $glide->getImageResponse($input->getPath(), $input->getParams());

// Pure PSR-7 where the user has a Response instance already available
// (or can easily create one to inject)
$response = PsrResponseFactory::create($imageResponse, $response);

// Business as usual.
$response = SymfonyResponseFactory::create($imageResponse);

// User won't have to pass in $response so it would be optional. If they
// do not pass one in, a Diactoros instance is created internally.
//
// Basically:
// 
// return PsrResponseFactory($imageResponse, $response ?: new Response();
//
$response = DiactorosResponseFactory::create($imageResponse);


```

If we continued down this line of thinking again, you can ship SymfonyResponseFactory in its own package and you can ship PsrResponseFactory either with glide directly or you can ship it in its own package... you could even ship a Diactoros factory in its own package to make it super easy for someone to get the proper deps in place.

 * require glide/glide (to get PsrResponseFactory, maybe? )
 * require glide/glide glide/psr ( or maybe PsrResponseFactory comes from here? )
 * require glide/glide glide/symfony ( to get SymfonyResponseFactory + HTTP Foundation)
 * require glide/glide glide/diactoros ( to get DiactorosResponseFactory + Diactoros )

In short, you could make Glide completely HTTP unaware if you wanted to.

I don't know how the streams stuff is working out for you, either, so maybe a standalone PSR factory simply won't work anyway. If you cannot make just an existing stream work ( whatever is on $response->getBody() ) then you may *have* to just tie to a specific PSR-7 implementation. At that point I'd spin that off to its own package, probably something like glide/diactoros.

---

As for your idea for the `send` method, you could also leverage this "Glide image response" that way, too, and create a `PhpEmitter` or something along those lines:

```php
class PhpEmitter
{
    public static function emit(GlideImageResponse $imageResponse)
    {
        header('Content-Type:'.$imageResponse->getMimetype());
        header('Content-Length:'.$imageResponse->getSize());
        header('Cache-Control:'.'max-age=31536000, public');
        header('Expires:'.date_create('+1 years')->format('D, d M Y H:i:s').' GMT');

        $stream = $imageResponse->readStream($path);

        rewind($stream);
        fpassthru($stream);
        fclose($stream);
    }
}
````

So if a user wanted to emit an image instead of returning a response of somesort:

```php
$imageResponse = $glide->getImageResponse($input->getPath(), $input->getParams());

PhpEmitter::emit($imageResponse);
```

Basically, the "Glide image response" becomes the thing that everything can refer to when they want to "send" some sort of information about an image, and you can create factories to convert that into a specific framework's Response object or you can do some other sort of operation on it like send it over the wire directly using PHP.

---

Don't get me wrong. The DX you are going for is amazing and nice, but at the expense of being able to cleanly separate something because one extra line of code is maybe not worth it.

You can simplify your code and still make it reasonably nice for your end users by making them be explicit about the type of response they are trying to create.

---

It is super easy for me to armchair quarterback the design of this API. :) You have your users to worry about and I don't. :)

I won't go down this line of thought again unless you want to, but seeing you write out "The challenge is that Glide must create a response" my first instinct is still, "but *why* is that Glide's job?"

I see Glide's job as being the interface to resized images (and whatever work is required to actually resize the original images). I don't see its job being the sending of responses or doing anything like that.

The PHP Emitter (or whatever you call it) can easily be shipped with Glide. If you want to support PSR-7  out of the box because *everyone should be using it*, that is fine as well (provided you can figure out the stream problem). But if I want to use Glide w/ Symfony, I should be OK requiring me to get the Symfony package (even if it is just one class!) and doing a one line call to the factory in my controller. That isn't asking a whole lot of me, really.

**Comment by simensen** [comment]
Oh! It should be worth pointing out that if you went down this road, you'd not have to "configure" a response factory.

So what we are looking at would be less code in Glide and a oneliner for the user where they needs to specify a class that is specific to the framework / stack they are working with.

Also, for reference, the [original gist](https://gist.github.com/simensen/20729228a1ec811440aa) that I threw together a few nights ago.

**Comment by reinink** [comment]
@harikt Hey man, thanks for trying to help, but I think somehow we're not understanding each other. I know how to compose a PSR-7 object, the challenge right now is simply a design challenge. Do you profile generic PSR-7 functionality where an end user has to provide their own implementations, or do we provider vendor helper classes to make this simpler, and if we do this do they get included with Glide by default, or are they secondary packages.

**Comment by reinink** [comment]
> I think that is the core problem. It arguably shouldn't be Glide's job to create a response.

I know what you're saying here Beau, but I sort of feel like it *is* Glide's responsibility, otherwise it's not really an HTTP library, but rather just a nicer API that sits on top of Intervention. My goal was always to provide solid HTTP support, and really, that means creating response objects. Now, admittedly, this was only with HttpFoundation responses until this point. However, PSR-7 really opens this up moving forward, and I think it's something that still makes sense to have baked into the library.

> If we continued down this line of thinking again, you can ship SymfonyResponseFactory in its own package and you can ship PsrResponseFactory either with glide directly or you can ship it in its own package

Maybe I'm lazy, but creating a bunch of one-class libraries sounds like a lot of work and maintenance, for really not a ton of benefit. Is it so wrong to include these right with Glide? I'd understand if these were heavy files, or there we lots of them, or they had sub dependencies, but in reality they are [super light](https://github.com/thephpleague/glide/blob/develop/src/Responses/SlimResponseFactory.php). And they're going to get even lighter, as I plan to remove the `send()` method entirely.

> Oh! It should be worth pointing out that if you went down this road, you'd not have to "configure" a response factory.

True, but that's sort of the case either way. If you use the `outputImage()` method, it uses the built-in emitter. However, if you want to use proper response objects, only then you would need to configure a response factory. Really this discussion is getting down to two design decisions:

1. Do you include vendor helper factories with Glide, or as separate packages
2. Should the outputting of images and/or generation of response objects be down within the Glide server class, or as separate classes

And while I see a nicer separation of concerns with pulling out image outputting and response generation from the server class, I don't really love the added object complexity. And this is probably just a design preference thing, but I love have a single object where all the configuration is done (the server factory), and then a single object that you use to actually interact with the library (the server).

> It is super easy for me to armchair quarterback the design of this API.

Dude, you have been extremely helpful and have already shaped the 1.0 release a lot. I really appreciate the time and effort you've put into this. Please don't be offended if I decide to go with a slightly different design approach. :weary:

**Comment by harikt** [comment]
no problem @reinink . I was just saying my ways. Implementations have their own pitfalls.

Thank you.

**Comment by reinink** [comment]
@harikt Understood, and thank *you* for trying to help!

**Comment by reinink** [comment]
I've updated the responses documentation for Glide 1.0, which I hope makes it very clear how to configure responses for whatever framework or HTTP package you use: http://glide.thephpleague.com/1.0/config/responses/

**Comment by reinink** [comment]
Just an update on this. While creating one-class libraries for each response factory sucks, having them including in the main Glide library sucks as well, primarily because of testing. In order to test them, you must include their dependencies. For the `SlimResponseFactory`, that means including the entire Slim framework. For `SymfonyResponseFactory`, it means including HttpFoundation.

So, I was thinking these could simply be included as dev dependencies, but really, that is still not ideal at all, since Composer does install `require-dev` dependencies by default. So having 5-10 vendor response objects, could literally mean hundreds of dependencies. This is clearly very bad.

So maybe individual packages are better. Or, maybe I just don't test these response factories. I don't really like either option. :-1:

**Comment by reinink** [comment]
Individual vendor packages are now a thing. The only response factory included by default is the `PsrResponseFactory`.

![image](https://cloud.githubusercontent.com/assets/882133/8776023/bbc4cf5c-2ebb-11e5-9c4a-ac59b0f15fc6.png)

**Comment by reinink** [comment]
Closing this ticket. All these changes has been merged into the master branch and will be tagged shortly when I release `v1.0`! Hopefully not long now. A big thanks to everyone who participated in this discussion!

Also, see the docs for this feature [here](http://glide.thephpleague.com/1.0/config/responses/).
