### ISSUE TITLE
Image issues

### ISSUE THREAD

**Issue by scott-davidjones** [thephpleague/glide#73]
Hi,

I am using this lib as part of a  laravel 4.2 instalation with the following code:
```php
$server = League\Glide\ServerFactory::create([
    'source' => public_path()."/uploads",
    'cache' => public_path()."/uploads/imgCache",
]);

Route::get('/loadimage/{type}/{id}/{width}/{height}/{crop}/{name}', function($type, $id, $width, $height, $crop, $name) use ($server){ 
    $server->outputImage(
          $type.'/'.$id.'/'.$name,
           [
                'w' => $width,
                'h' => $height,
                'fit' => ($crop == 1 ? 'crop':'max'),
           ]
    );
});
```

I am having some very weird issues:

- Some times when refreshing a page i just get an image and nothing else
- Sometimes a variety of images on the page are all showing the same image (even if they are not called using the same path)
- sometimes images take ages to load and thus dont display in email clients (such as outlook) however they work fin else were - it seems like the caches images are not being used as its recreating them every time?

**Comment by reinink** [comment]
Hi Scott, those issues sound very strange. First off, what version of Glide are you using? You can run `composer info league/glide` to see which version is installed.

Second, whether or not your HTML page displays one image, or many, really has little to do with Glide, but more with how you've built your HTML. Can you please show the code for your template page so I can have a look?

As for images in email clients, I haven't had much experience using Glide with them, but in theory it shouldn't be an issue at all.

**Comment by scott-davidjones** [comment]
Hi reinink,

Thanks for the response. Composer info:
```
name     : league/glide
descrip. : Wonderfully easy on-demand image manipulation library with an HTTP based API.
keywords : ImageMagick, editing, gd, image, imagick, league, manipulation, processing
versions : * dev-master, 0.3.x-dev, 0.3.5, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.1, 0.1.0, dev-develop
type     : library
license  : MIT License (MIT) (OSI approved) http://spdx.org/licenses/MIT#licenseText
source   : [git] https://github.com/thephpleague/glide.git 57a10a4b8049f9efb7debb5cfd9718f897e205d3
dist     : [zip] https://api.github.com/repos/thephpleague/glide/zipball/57a10a4b8049f9efb7debb5cfd9718f897e205d3 57a10a4b8049f9efb7debb5cfd9718f897e205d3
names    : league/glide

autoload
psr-4
League\Glide\ => src/

requires
intervention/image ~2.1
league/flysystem ~1.0
php >=5.4
symfony/http-foundation ~2.3
symfony/http-kernel ~2.3

requires (dev)
mockery/mockery ~0.9
phpunit/php-token-stream >=1.3.0
phpunit/phpunit ~4.4
```

example page loadout:
http://109.203.105.170/auction/view/uA48Tl3vgxtyUHkqQmKy13Ifa5T8chMpB7C5RcltNiqMoUG0XbPs3FopPegcb5GP

this page has a variety of images, some via the route ```/loadimages``` and other loaded via CSS and (not sure if they are on that page) standard ```<img />``` tags.

i have noticed that when the pages displays a single (garbled) image it appears to still be loading (which could be an issue with styles/js no loading in time i suppose)

example of issue with images being replaced:
![image](https://cloud.githubusercontent.com/assets/547193/8182823/40e3c432-142b-11e5-9a24-303f4dd2241d.png)


i fully expect this to be an issue with the way i have this setup via the routes etc..

**Comment by scott-davidjones** [comment]
the online auction image should be fetched via css but is showing an image that has been generated via the glide lib.

**Comment by reinink** [comment]
It looks like you're using `dev-master` for Glide, is that correct? I'd recommend never using `dev-master`, especially when using a young package like Glide. Glide is still under heavy development, and who knows what version you could be on at this point.

I'd recommend using `0.3.5` for now.

**Comment by reinink** [comment]
I also seems like your server is hitting it's max connections. I'm getting a `waiting for available socket` message from Chrome, which apparently means:

```
Status text when Chrome is at its connection limit, and is waiting for a URL request to complete to free up a connection.
```

**Comment by reinink** [comment]
Also, just to try it, can you add an `exit;` after sending your image? Like this:

```php
Route::get('/loadimage/{type}/{id}/{width}/{height}/{crop}/{name}', function($type, $id, $width, $height, $crop, $name) use ($server){ 
    $server->outputImage(
          $type.'/'.$id.'/'.$name,
           [
                'w' => $width,
                'h' => $height,
                'fit' => ($crop == 1 ? 'crop':'max'),
           ]
    );
    
    exit;
});
```

**Comment by scott-davidjones** [comment]
thanks for helping with this! I was using version ^0.3.0@dev but have switched to the suggested version.

I have also added in the exit as requested and contacted the server host to increase the max connections to 450 (now done)

I believe the main culprit here will be the max connections as the site is quite image heavy. this would also explain the email client issues (as it works on some but not others.)

**Comment by scott-davidjones** [comment]
still looks like its taking a while to load the page..

**Comment by scott-davidjones** [comment]
further to this (again i appologise if this is not related) I am sometimes getting the following returned in chrome:

```
����JFIF��;CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), quality = 90
��C




��C		

���U"��	
���}!1AQa"q2���#B��R��$3br�	
%&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz���������������������������������������������������������������������������	
���w!1AQaq"2�B����	#3R�br�
$4�%�&'()*56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz��������������������������������������������������������������������������?��H���j���w�`c5_�1����s]	��-�z�D�.��R����`{�.�A���#a)����r
z��Q�g��WHԴ;үoʊεo݀{U�m�Ey��������3U~sK)!z�i@��@\|��Z��:�y$��1�LM����֛%�c�j�\g�B�x�W.<�9����j�I�Q���R�寵�T5��Z����_zB��n���������<�iX.i-�ҤK�X���E��4X.n���Z��X�X�
<]����6�����z��Y������@�l��Z��}�3���,��r���7�S݁M�9����ڊI��_�۟�F���en��=o01Y�7�G�`��l��z�n�ޱV㞵 ���
��	�kcKQ/�Oz��� ��4���f�):��`
�a� ����(��`��zׄ$
C0�6YI��F�&���U�L.s�'ڧv&Gq�"��Ȭ��X&P��>���Z���R�DV�sڙ����C)M���S����z,�gh�]���Y��y����֌���z��|���;�e@8�Ҧ�=
I��آXA�}Ojqj���G#��S.Gj�>[
-�M��SI�Z��C#����X���c�In��
���g�c+1��j�8���0k�IrG��R�$gmLS"�����r7&��85e,^PN3U�0���é�T�������iD��`��M�Һw��X�9��4�sf]1�Vc8��(Ƣ���-
/�+�ʱ�L�-��F[�FsP\HOz�5��W,Oq��k6yL�����5�����fM��ne,��q�'�n7W���J�F�.�P��� c�ֹKnu;;}AlZ5R�<P�M��s���c�u7v��14��A�v���Y�q
���#���u�H��,3��<�5�L�Ռ��'M�m��M.ܑЅY"nG$
��z�Ys_
?S�����z$7@�|��\�׊�8��F���켕���l��\�֥�&�5}&���rܽ����܃
7u��fZ}�1��h��I��0n�H�rJ�g�,n�<Mw=��G�v������y�sK��[=�-
�]r�h��l#�?/�qֳ�� I ����4�.Ub�o��3�J���C �ҿr���.}Q㺲������i&qq��nRHc����վ �����q-ط�E�FuT*pF߸��8���47:e�k��slV�\,,G9`0pG<����o�V�����)W�B㓒1��N��z3ο�7�|I&���4�<�r�q�J�pbHpXd00y�8��y4�\�'�VV���Wqx�#/��,99#���R���<z|v�����I,D.�;=�b[|;ye:�Wm�%n���]�6	 'B6����<��]k�-������J�*yz��#W?(#?2��z�+cF�Q��u��u
B�%���&�n<�$�����/<A��IY��;
F�	wI�i�g��^h��r~���o���uKm�iw��,ą��H#i���Ob)��8kMS���ݷ�|5�j�v��^��x�q�4pNx�ϭ����}sN���W,�/�hB�}9�J+'q���.�r)���g4�W<
Ұ�2�u�@�Z�Y�Zn�03�I�JFz���۠98�ث#:�Ŋo��k���]�[x�{�_1IN�^�e�J�f�0楽W�����4��Ulf��9�U�RM0�i1�Zb��yp=�1'=j)��<�j����
Wy����j����`9�D�#֩������dܾ.�=h79�Y����S(������dlђi��^�"�v�f�T�s�i�ҎL��0S�R����~�Mi$\�J��Ȭ��=�ɓ�y`����w�Fs�KΊ��#9��j�����=_S<���ӝ��	��~5V$�<!�
<O�}sCYm_�9m�Eg1l�g''�|i�X\��<�y��BV#XN��z��)b��zҊ��3�j���b�^Aҥ��9��mĚg.���d�e^B�}*��L��P��ŕ"[Zxl��
����<�Ɨhw�
`o選���l��
�z�Ր�,EUx�7�g��jQ���Pc+��(ߊ|M�/	�KW�5��"�[ϱ��F\���}{��M;?��i_��|~�]s�{{��۳s��ʛ�6�㎢������|���^�4�k>+2j5%��P�c�"@X�@�k�:��=J�)��&�E2�����o��Zދ����ī���
�X�,n!bg�3���W蟃���i:����!�H������Vl��5і��k�F�۰H�+@���t�zͲ�xuW�h��!�VN��1W@��֮�qneN*�آF�0�Mw���3�1֚v2��f�)�G����P�b��&ԗk}���R����fb�SL� �Z���n`<�+?�<�;�����aI�E��5�.����M�nb'oݨ�FBm�2���D���trPք�ϔpN*���$M6 �Z�_ �b+$.�����x�c+j�p�\��l���C�g����V�#��ׯ�g��{�Euj�O����a7?��3g5tB�Y���F�e	�4��Lw�]T�[`��ҹ�sR��gԵ[+M� ��!�lWT��d.���^F:b�l_H��<J�x3}��G�+7A���<S�Ic��֚��}��r����·ͅ���#���-(¶}=ih4�s���m��uW� �G;���'��{rj�x����Yl�K�0�*����מ�kJ2��qm��SqQ)<�p����xE�C��ʶ�a�;( ޠc�����3e�KXϊ&�+8#Ӯ7��m�&E�6�q�b8�#W�݅��xu/�mN8S6��г*�) ��=��I�ѵC2f�ݝ�&#�F��y�
�M7��+髣J���L�̃8_��YIȡ�����6�	���MSO7�P[�dc9�@8
�<�6�һ�_v�
퇊�mNM�6�囯��<c�z]���Ŧ�Oq��o�4�8�22~c��=�^����i�]พ��+���\���#�8'$�A�x�f����ύ�n4�;X��Pm��2��a�\���u���E��Y��I�q�������#�:k׏��3�#�A{q���;���#L����{f��/
f���F�ou;�{�-m�7V�2��q������Os�O��
}Q��m`��!h�}��s�N�6�����֝�[Y�u��ῄh��yȍ/����x�8�߷$��c�m����q�]��x�2�E�@�,�N6�HTTP/1.1 200 OK
Server: nginx
Date: Tue, 16 Jun 2015 14:19:48 GMT
Content-Type: text/javascript
Content-Length: 22267
Last-Modified: Tue, 16 Jun 2015 10:08:35 GMT
Connection: keep-alive
ETag: "557ff5a3-56fb"
X-Powered-By: PleskLin
Accept-Ranges: bytes
```

I am about to put in a support request for this with the server hosting company but the first line ```����JFIF��;CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), quality = 90``` looks liek an image manipulation tag. Could this be related as well?

**Comment by reinink** [comment]
Are you seeing on on the preview tab in Chrome? Because I'm getting that for any image I load. I'm seeing that for any images, not just Glide images. Maybe the preview tab is broken on Chrome.

**Comment by scott-davidjones** [comment]
i was getting it as a response to a logged console error which was saying the jquery js file had ```Uncaught SyntaxError: Unexpected token ILLEGAL``` and when you view that file in the scripts tab thats what it shows at the top.. very odd (happens to various js files not all at the same time)

I will ask the server provider to look into that - I am going to install imagick and see if that resolves any issues as at present using GD

**Comment by scott-davidjones** [comment]
i see what you mean on the preview tab - I have raised a support request with the server provider.

**Comment by reinink** [comment]
I'm going to close this issue, since it's most likely not a Glide issue. However, if you can find any specific bugs that might be causing this, feel free to reopen, or start a new issue!

**Comment by scott-davidjones** [comment]
agreed, thanks for the help in diagnosing this - turns out it was an nginx issue (some reason server prodiver was running nginx as a reverse proxy to apache..)
