### ISSUE TITLE
Add the ability to define default image manipulations

### ISSUE THREAD

**Issue by reinink** [thephpleague/glide#74]
In certain situations you may want to define default image manipulations. For example, maybe you want to specify that all images are outputted as JPEGs (`fm=jpg`). Or maybe you have a watermark (coming soon) that you want on all images.

Example setup:

```php
$server->setDefaultManipulations([
    'mark' => 'billabong.png',
    'markscale' => 30,
    'markpad' => 3,
    'markpos' => 'top-right',
]);
```

These manipulations will be added to all requests. You can override any of them for a specific request simply by including that parameter in your request (`markpos=bottom-right`) or disable a feature entirely by setting it to blank (`mark=`).

**Comment by ADmad** [comment]
Along with default manipulations it would be nice to be able to have named manipulation presets. Then when requesting images one can just pass preset name in url like `/image.jpg?p=small`, `/image.jpg?p=big` instead of providing all manipulation params. 

This would also help with eagerly generating image variants as stated in #72.

Could also allow the possibility to _only_ use preset names in url and thereby prevent the possibility of miscreants generating images of any size by passing url params.

**Comment by reinink** [comment]
Yes, this is actually something @jasonvarga suggested once, and I think it's something that could be added. I like the idea of calling them `presets`, with `p` being the query parameter. They would be applied after the `default_manipulations`, allowing you to use both these features if you wanted.

```php
$server = ServerFactory::create([
    'default_manipulations' => [
        'mark' => 'billabong.png',
        'markscale' => 30,
        'markpad' => 3,
        'markpos' => 'top-right',
    ],
    'presents' => [
        'small' => [
            'w' => 250,
            'h' => 250,
            'fit' => 'crop'
        ],
        'medium' => [
            'w' => 500,
            'h' => 500,
            'fit' => 'crop'
        ],
    ]
]);
```

They could theoretically even be extended. For example: `/image.jpg?p=small&filt=sepia`. Or potentially even be grouped: `/image.jpg?p=small,aged`, where the later presets would take priority over the previous ones in the event of conflicts.

I'm not sure about the "only use presets" option...that could maybe work, but I sort of feel like this could be handled easily by the controller, by simply checking if `$_GET['p]` is set. Worth considering though.

**Comment by ADmad** [comment]
I agree thing everything above :)

**Comment by reinink** [comment]
I've added this feature as of f2a74a982699678609819660e83f22d6d7571b74. You can find the bulk of this feature in these [lines of code](https://github.com/thephpleague/glide/blob/develop/src/Server.php#L319-L332) which handle the merging of params. It's really quite simple, it goes like this:

1. Defaults
2. Preset 1, Preset 2, Preset 3, etc.
3. Query

Where the later values always take priority over the previous values.

**Comment by ADmad** [comment]
@reinink Thanks. Yup, it's quite simple :)

**Comment by reinink** [comment]
Defaults & presets have been added to Glide, and will be available in the upcoming 1.x release. Documentation can be found [here](http://glide.thephpleague.com/1.0/config/defaults-and-presets/).
