### ISSUE TITLE
Breaking API change (changing fit, crop and rect)

### ISSUE THREAD

**Issue by reinink** [thephpleague/glide#75]
I'm thinking about making a bigger breaking change to the image API in the next release. This is primarily to accommodate the new watermark features (#63), but I also think it just makes more sense.

**The current API:**

- `w` - sets the image width
- `h` - sets the image height
- `fit` - sets how the image is fitted to its target dimensions
    - `contain`
    - `max`
    - `stretch`
    - `crop`
- `crop` - sets where the image is cropped when the `fit` parameter is set to `crop`
    - `top-left`
    - `top`
    - `top-right`
    - `left`
    - `center`
    - `right`
    - `bottom-left`
    - `bottom`
    - `bottom-right`
- `rect` - crops the image to specific dimensions
    - width,height,x,y

**New proposed API:**

- `w` - sets the image width
- `h` - sets the image height
- `fit` - sets how the image is fitted to its target dimensions
    - `contain` *(default)*
    - `max`
    - `stretch`
    - `crop` *(same as `crop-center`)*
    - `crop-top-left`
    - `crop-top`
    - `crop-top-right`
    - `crop-left`
    - `crop-center`
    - `crop-right`
    - `crop-bottom-left`
    - `crop-bottom`
    - `crop-bottom-right`
    - `crop-face` *(future face recognition feature)*
    - `crop-50-50` *(future focal point feature)*
- `crop` - crops the image to specific dimensions
    - `width,height,x,y`
    - the former `rect`

I think this is a more logical API, and I love that you don't need two parameters when doing basic cropping. Further, it means we can use `crop` for actual cropping to specific dimensions, which I think just makes more sense than `rect`. This also has an added benefit of following the same system with the new watermark feature (`markw`, `markh` and `markfit`).

**Comment by jackmcdade** [comment]
Overall it looks great to me. I don't mind the breaking changes to have more flexibility and logic. 

Only question: `crop-50-50` - do those numbers represent percentages, pixels, or a literal string there?

**Comment by reinink** [comment]
Excellent, glad you like it.

As for the proposed focal point syntax, see #36. Probably makes the most sense to keep that discussion there.

**Comment by huglester** [comment]
Hello,

not sure into which of the Issues to write, so I'll write here.
I think it would be nice, to have a possibility, to position watermark also with those options like:

w-center-10-10
it means it it place watermark starting from center, will go 10px right, 10px bottom, and will draw the watermark.
Similar combos (more often used)
bottom right 15 10 - it bill go to very bottom right corner. but will make space of 15px on the right, and 10px in the bottom


Of course API syntax may change, etc, but I would like to share the way, we are currently putting watermarks in our similar project to glide (ours is veeery basic). We are just thinking switching to glide in later versions

**Comment by reinink** [comment]
@huglester You can mostly do this already in the upcoming 1.0 release, except not with centered watermarks. This is done using the `markx`, `marky` and `markpad` options. For example:

```php
<img src="kayaks.jpg?mark=logo.png&markpos=bottom-right&markx=20">
```

You can read more about this [here](http://glide.thephpleague.com/1.0/api/watermarks/).

However, as mentioned, this doesn't work for centered watermarks, and that's most because [Intervention](http://image.intervention.io/api/insert) doesn't do this.

**Comment by reinink** [comment]
Closing this, as all these features have been added to the upcoming version 1.x release, other than focal point support, which I've created another issue for here: #36. Hope to have this release out BEFORE 2016! :tada:
