### ISSUE TITLE
Out of memory bug when working with 3M+ images

### ISSUE THREAD

**Issue by nedens** [thephpleague/glide#79]
I receive the following when working with images 3M and larger. Tried tracing it down but had no luck. Any help appreciated.

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 12000 bytes) in /opt/bitnami/apache2/htdocs/glide/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php on line 115

**Comment by nedens** [comment]
Increasing memory to php from 128M to 512M per script seemed to fix the issue though not a great fix. 

It looks like maybe using ImageMagick to do processing for JPG large files may be more memory efficient than GD based on this thread http://stackoverflow.com/questions/12661/efficient-jpeg-image-resizing-in-php/4613341#4613341

**Comment by reinink** [comment]
Haha, I was just going to ask if you've tried increasing the available memory on that call:

```php
ini_set('memory_limit', '64M');
```

**Comment by reinink** [comment]
Yes, ImageMagick might be a better choice if you're running into memory issues. Good luck!
