### ISSUE TITLE
Content Type Incorrect on HHVM

### ISSUE THREAD

**Issue by croemmich** [thephpleague/glide#81]
For some reason the Content-Type header is coming back incorrectly as text/html on HHVM and correctly as image/png under fpm 5.6.10.

HHVM:
```
HTTP/1.1 200 OK
Server: nginx
Content-Type: text/html; charset=UTF-8
Content-Length: 292273
Connection: keep-alive
X-Powered-By: HHVM/3.7.1
Vary: Accept-Encoding
Cache-Control: max-age=31536000, public
Cache-Control: no-cache
Date: Thu, 09 Jul 2015 13:31:21 GMT
Date: Thu, 09 Jul 2015 13:31:21 GMT
Expires: Sat, 09 Jul 2016 13:31:21 GMT
Last-Modified: Thu, 09 Jul 2015 13:31:21 GMT
```

PHP
```
HTTP/1.0 200 OK
Host: localhost:8000
Connection: close
X-Powered-By: PHP/5.6.10
Cache-Control: max-age=31536000, public
Date: Thu, 09 Jul 2015 13:33:08 GMT
Content-Type: image/png
Content-Length: 292276
Expires: Sat, 09 Jul 2016 13:33:08 GMT
Last-Modified: Thu, 09 Jul 2015 13:33:08 GMT
```

Some of the headers are being duplicated in HHVM as well. .. not sure what that's about

Any thoughts?

**Comment by reinink** [comment]
Interesting, what version of Glide are you using? Right now Glide relies on HttpFoundation for this, and I'm not even certain that library has been optimized for HHVM.

To be totally honest, I haven't done much HHVM testing for Glide, beyond running the unit tests on it.

**Comment by croemmich** [comment]
Im using v.0.3.5.

**Comment by reinink** [comment]
I know this isn't very helpful, but I honestly could not tell you what's going wrong here. It must have something to do with HttpFoundation. I recommend getting the response object back (`$server->getImageResponse()` and analyzing it to see what's set.

Alternatively, you may want to try and simply send the response yourself using plain old PHP...errr...HHVM. Something like this:

```php
// Generate image
$this->makeImage($request);

// Get cache path
$path = $server->getCachePath($request);

// Output headers
header('Content-Type:'.$cache->getMimetype($path));
header('Content-Length:'.$cache->getSize($path));
header('Cache-Control:'.'max-age=31536000, public');
header('Expires:'.date_create('+1 years')->format('D, d M Y H:i:s').' GMT');

// Output content
$stream = $cache->readStream($path);
rewind($stream);
fpassthru($stream);
fclose($stream);
```

Where `$cache` would be an instance of your [cache filesystem](http://glide.thephpleague.com/0.3/config/source-and-cache/).

**Comment by croemmich** [comment]
I believe duplicate header issue an an HHVM bug, however Laravel was also part of my problem. I switched `return $server->outputImage($path, $request->query->all())` to `return $server->getImageResponse($path, $request->query->all());` and all is good. It appears the headers and content were being sent by outputImage which was followed by Laravel being helpful outputting them again :)

Thanks!

**Comment by reinink** [comment]
Good to hear, thanks for the update, that actually makes perfect sense. If you do use the `outputImage()` method, it's important to `exit` after you call it, otherwise Laravel will send a default response.
