### ISSUE TITLE
HTTP 502 behind Amazon Load Balancer

### ISSUE THREAD

**Issue by keithslater** [thephpleague/glide#84]
This is a weird situation I'm having. I am using Glide, loading images from S3 and displaying them. I am behind an Amazon Load Balancer.

The images work fine when I request them below about 700x700. If I go above 700px, then I get a 502 error. The images are saving to the cache and they look correct, so I don't think the problem is there.

From what I've read, Amazon's load balancer is pretty specific about headers and things it receives and that the response needs to conform to HTTP specifications.

Do I need to manually set the headers or does Glide set them? I dumped out headers_list() before the fpasstru in setContent() and the content type was showing as text/html.

Any insight here would be helpful. Thanks

**Comment by reinink** [comment]
Hmm, that is bizarre. Where are you saving the cached images? On S3 as well? And what version of Glide are you using? 0.3?

Glide does [set the headers](https://github.com/thephpleague/glide/blob/57a10a4b8049f9efb7debb5cfd9718f897e205d3/src/Http/ResponseFactory.php#L63-L70), and they shouldn't be set as text/html. But yeah, I've never used Glide behind a load balancer. How exact is the 700px rule? Like, 100%, or just sometimes?

**Comment by keithslater** [comment]
The cached images are being saved locally on EC2. I'm using Glide 0.3.1.

I figured out that the exact size that this happens at is 657x657. It happens every time. Anything 657x657 and over will cause the 502 error.

**Comment by reinink** [comment]
Seriously...so weird. So, if this is being caused by the headers being wrong for some reason, maybe try and set your own header and see if you can get around the issue. For example:

```php
// Get image response object
$response = $server->getImageResponse($request);

// Set custom headers
$response->headers->set('name', 'value);

// Send response
$response->send();
exit;
```

I'm having a really hard time guessing what is going wrong here. Given the size issue, I wonder if it has to do with the `Content-Length` header somehow. And given how consistent it is, it probably isn't related to any delay when streaming the data from S3.

**Comment by reinink** [comment]
The other thing I would maybe try is removing all the query parameters, and just hard coding them in, and see if that makes any difference. I wonder if the load balance is stripping them, and causing some strange issues.

Do that like this:

```php
$response = $server->getImageResponse('path/to/source/image.jpg', [
    'w' => 1000
    // whatever
]);

$response->send();
exit;
```

**Comment by keithslater** [comment]
I'm currently not set up to use Responses so I will have to work on the first option.

I did try the 2nd option and that didn't work.

I did set up my project to go around the load balancer and I can confirm that it works. So it's definitely something with the load balancer.

I also verified that $this->cache->getSize($this->path) matches the file size of the cached file.

**Comment by reinink** [comment]
> I'm currently not set up to use Responses so I will have to work on the first option.

Well, technically when you use `$glide->outputImage()`, it's actually just calling the `send` method on the response object. I almost want to you try and modify your local `glide/src/Http/ResponseFactory.php` file, and remove all headers that are not technically needed to display an image:

```php
public function setHeaders(StreamedResponse $response)
{
    $response->headers->set('Content-Type', $this->cache->getMimetype($this->path));
    $response->headers->set('Content-Length', $this->cache->getSize($this->path));

    /*
    $response->setPublic();
    $response->setMaxAge(31536000);
    $response->setExpires(date_create()->modify('+1 years'));
    $response->setLastModified(date_create()->setTimestamp($this->cache->getTimestamp($this->path)));
    $response->isNotModified($this->request);
    */

    return $response;
}
```

Are you able to give that a try?

**Comment by keithslater** [comment]
I tried that and no change... I believe it's something else in my project but I'm not sure what. We have another application on the same server behind the load balancer using glide and it seems to work fine. I'll report back once I figure something out.

**Comment by reinink** [comment]
Okay, that's be great, please do.

**Comment by keithslater** [comment]
Ok I found the cause but I'm not 100% sure why. In my htaccess I had this:

    <IfModule mod_deflate.c>
    SetOutputFilter DEFLATE
    SetEnvIfNoCase Request_URI \
    \.(?:gif|jpe?g|png)$ no-gzip dont-vary
    </IfModule>

My guess is some how mod_deflate was turned in a couple weeks ago which started it. For now I just commented this out. I'm guessing this tells it to not gzip but glide wants it to gzip. I'm also guessing this only happens once the image gets to a certain size.
