### ISSUE TITLE
Glide is stripping animated GIFs even when no functions/effects applied

### ISSUE THREAD

**Issue by maglfmn** [thephpleague/glide#87]
First off, thank you for all of the amazing work on this project! 

I have an implementation of Glide (I am using v1.0) where I do **not** want caching, so I use a  ```MemoryAdapter``` as the cache. This works well and I love the consistency that it brings. **Except** for animated gifs. 

If I request an animated gif without any manipulation parameters (size, effects, etc), I get back a version with only the first frame, and lose all of the rest. :cry: 

Now, I know that Glide doesn't support animated GIFS per se, but I would expect that upon requesting the original image w/o modification that it would return the working gif. If I request it with resize parameters or other manipulations, it would strip to the first frame.

Take this very tasteful animated gif, for example:
http://www.wired.com/images_blogs/design/2013/09/tumblr_inline_mqutgxtW2Z1qz4rgp.gif

Assuming that the file ```tumblr_inline_mqutgxtW2Z1qz4rgp.gif``` already exists in my local storage, I'm using this basic PHP code to serve it:
```php
use League\Flysystem\Filesystem as Filesystem;
use League\Flysystem\Adapter\Local as LocalAdapter;

$file = 'tumblr_inline_mqutgxtW2Z1qz4rgp.gif'; 
$server = League\Glide\ServerFactory::create([
  'source' => new Filesystem(new LocalAdapter('/some/dir')),
  'cache'  => new Filesystem(new MemoryAdapter())
]);
$server->outputImage($file, array());
```

What you'll get back is a static gif with no animations.

As far as I could tell, this has to do something with how the file is copied into the MemoryAdapter, but I can't be for certain. 

This is important for me because while Glide doesn't support animated gifs, I feel as though it should return unaltered data if no manipulations were requested. My workaround for this was to check if any manipulations were given and then manually feed back the image myself. This is essentially a copy of what ```Server->outputImage()``` is doing, but without the call to ```makeImage``` and then feeding it through the cache.

```php
if (sizeof($manipulation_params) == 0) {
    header('Content-Type:'.$source->getMimetype($file));
    header('Content-Length:'.$source->getSize($file));
    header('Cache-Control:'.'max-age=31536000, public');
    header('Expires:'.date_create('+1 years')->format('D, d M Y H:i:s').' GMT');

    $stream = $source->readStream($file);

    rewind($stream);
    fpassthru($stream);
    fclose($stream);
    exit;
}
```

This works perfectly for what I need, and returns my animated gifs correctly.

Thoughts on what could be done here? I am more than willing to provide additional information, sample assets, or code if you need it.

Thank you!

**Comment by reinink** [comment]
Hey! Thanks for your interest in Glide, and sorry for the LONG delay on responding. The behaviour you're describing makes sense, since Glide actually does not look at the original file format when generating the new image, which means even if you specify `fm=gif`, it will re-encode it anyway.

I could update Glide to check for any manipulations parameters, and if none are set to just use the original image. However, there is some challenges here as I also have to consider if any defaults are being set in the Glide configuration. I also sort of wonder why Glide is even being used at this point? I'm assuming for some consistency in how you deliver your images?

I actually think your solution here is a really good one for you use-case. Not sure I want to add additional checks at this time to enabled non-manipulated GIFs. Hope that makes sense! :+1:

**Comment by maglfmn** [comment]
@reinink Thank you for the response (and I understand the lag, don't worry about it). The workaround I suggested did work for us, but the issue I saw was that we lose out in all of the built-in error handling that's covered in the normal code path. Not impossible to overcome, but a bit of work. And I understand your reasoning for wanting to stay clear of animated GIFs. Thank you!

**Comment by paxperscientiam** [comment]
@maglfmn 

Thanks a lot for your comment. I got this whole 'gif' thing working finally because of your input. Much appreciated.

**Comment by jimmykane** [comment]
Any updates on this ? We also need gif support. Thanks

**Comment by tomschlick** [comment]
@reinink what would be your opinion on checking for an animated gif and simply passing it through with modification by default?

There seems to be [some simple solutions for detecting animated gifs](http://stackoverflow.com/questions/280658/can-i-detect-animated-gifs-using-php-and-gd).
