### ISSUE TITLE
Cache from S3 is very slow

### ISSUE THREAD

**Issue by zslabs** [thephpleague/glide#93]
Hi all,
If I set both the src and cache to my fileDriver (which is S3), I've noticed a significant decrease in speed grabbing these cached images from S3 instead of locally. This seems a bit odd, but any clarification on the subject would be greatly appreciated. Thanks!

**Comment by ADmad** [comment]
Uploading the cache image to S3 instead of saving to local filesystem is going to be considerably slower, so the overall decrease in speed is expected isn't it?

**Comment by zslabs** [comment]
It has nothing to do with saving them to S3, my issue is the slowness in retrieving the cached files from S3. I know it'd be a little slower, but it's pretty painful. Would the only option be hooking this up behind Fastly?

**Comment by zslabs** [comment]
Looking into a potential integration with Fastly to help this along https://docs.fastly.com/guides/integrations/amazon-s3 but am not sure if the Glide library would support these types of rewrites cc @reinink

**Comment by joshrhykerd** [comment]
@zslabs How painful is the slowness? I've been using v1.0 with both my initial asset and the cache stored on S3 and can process and display quite a few images very fast. Since we launched our code we've served well over 15million images using glide from S3. A slight slowness is expected, but are you sure your speed issue is S3 and not somewhere else potentially. I know at one time point I thought the same thing, but quickly realized it was the type of EC2 instance I was using and an improper nginx/php5-fpm configuration.

**Comment by zslabs** [comment]
@joshrhykerd Thanks for your thoughts on this. Care to elaborate on your EC2 Instance and nginx/php5-fpm config that may have caused the slowness on your end? Images on my end are about 4 to 5 times slower than they are from local cache.

**Comment by reinink** [comment]
Curious, is this happening in production, or is this in a virtual machine, like Vagrant? This sounds like more of a [Flysystem](http://flysystem.thephpleague.com/) issue, you may want to poke around in that library's past issues as well.

For what it's worth, Glide uses streams when pulling images down from S3 (basically whenever it can), which makes it possible to start outputting the cached image while still downloading it from S3.

**Comment by zslabs** [comment]
Hey @reinink,
This is happening both local (using the good 'ole MAMP) and also production; using Forge with servers provisioned on Digital Ocean. Definitely a bit odd, but I noticed a HUGE difference in performance when pulling from S3.

**Comment by reinink** [comment]
I'm going to close this issue, as I believe it's more of a Flysystem or even Amazon SDK issue. Sorry I cannot be more helpful than that.
