### ISSUE TITLE
Support For Color Profiles

### ISSUE THREAD

**Issue by joshrhykerd** [thephpleague/glide#94]
Is there any kind of support for color profiles. I'm using Glide successfully in my project and all is working as expected except for one thing and that is it's changing certain colors during conversions. For example I have a client who's primary important color is red and any type of conversion I do converts the red to pink! I need some way to pass in the -colorspace during a conversion like you can when using the command line imagemagick convert command. I don't know if this is possible or not. If someone could point me in the right direction I will definitely see what I can do in writing this code myself.

Thanks for any help

Josh

**Comment by reinink** [comment]
As noted in your PR, this is not possible with Glide at this time, and I'm not sure it's a feature that's needed in the core. Thanks either way! :+1:

**Comment by hellohereiam** [comment]
@joshrhykerd Did you find a good solution for this? It's an issue with intervention. I am still doing my research on the issue but I partially have terrible results, even with imagick as driver. Any pointers would be greatly appreciated. Thanks.
